Jenkinsfile, package.json
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-224)
Fixes the GitHub pages build
=> TE-224 Fix build steps in Jenkinsfile. Exclude js from semantic build.

Jenkinsfile
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-224)
Avoid conflicts when pushing to gh-pages
=> TE-224 Avoid conflicts when pushing to gh-pages

src/components/widgets/OwnerSignUp/Readme.md, src/components/widgets/OwnerSignUp/component.js, src/components/widgets/OwnerSignUp/component.spec.js, src/components/widgets/OwnerSignUp/index.js, styleguide/config/sections.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-219)
Create component, tests and examples for OwnerSignUp
=> TE-219 OwnerSignUp widget

src/components/elements/InputController/component.js, src/components/elements/InputController/component.spec.js, src/components/elements/TextArea/component.js, src/components/elements/TextArea/component.spec.js, src/components/elements/TextInput/Readme.md, src/components/elements/TextInput/component.js, src/components/elements/TextInput/component.spec.js, src/components/widgets/OwnerLogin/Readme.md, src/components/widgets/OwnerLogin/component.js, src/components/widgets/OwnerLogin/component.spec.js, src/components/widgets/OwnerLogin/index.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-220)
Create component, tests and examples for OwnerLogin.
Had to make a couple of changes to associated components (e.g. `tagName` and `type` for `InputController`).
=> TE-220 Owner login

Jenkinsfile
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-224)
Favours our changes in the case of conflicts when we try to pull the remote gh-pages branch.
=> TE-224 Further gh-pages build fixes

src/components/elements/Dropdown/Readme.md, src/components/elements/Dropdown/component.js, src/components/elements/Dropdown/component.spec.js, src/semantic/src/themes/livingstone/modules/dropdown.overrides, src/semantic/src/themes/livingstone/modules/dropdown.variables
Te 215 dropdown  with icon
Add prop to specify an icon for the dropdown list
=> Te 215 dropdown  with icon

.babelrc, src/components/collections/Form/component.js, src/components/collections/Form/component.spec.js, src/components/collections/Header/component.js, src/components/widgets/OwnerLogin/component.js, src/components/widgets/OwnerLogin/component.spec.js, src/components/widgets/OwnerSignUp/component.js, src/components/widgets/OwnerSignUp/component.spec.js, tools/eslint/rule-options/import.order.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-221)
Implements absolute paths for modules.
Once merged, rebase off production and change any remaining relative paths.
=> TE-221 absolute module paths

src/semantic/src/themes/livingstone/modules/dropdown.overrides, src/semantic/src/themes/livingstone/modules/dropdown.variables
Quick fix: Remove underline from links in submenu
=> Quick fix: Remove underline from submenu

src/semantic/src/themes/livingstone/collections/menu.overrides, src/semantic/src/themes/livingstone/collections/menu.variables
Quick fix: Remove pagination min-height
=> Quick fix: Remove pagination min-height

package.json, src/components/elements/DateRangePicker/Readme.md, src/components/elements/DateRangePicker/component.js, src/components/elements/DateRangePicker/component.spec.js, src/components/elements/DateRangePicker/index.js, src/components/elements/DateRangePicker/pickDatesFromState.js, src/components/elements/DateRangePicker/pickDatesFromState.spec.js, src/components/elements/InputController/component.js, src/components/elements/InputController/component.spec.js, src/components/elements/InputController/utils/getHasErrorMessage.js, src/components/elements/InputController/utils/getHasErrorMessage.spec.js, src/components/elements/InputController/utils/getValue.js, src/components/elements/InputController/utils/getValue.spec.js, src/components/elements/TextArea/component.js, src/components/elements/TextArea/component.spec.js, src/components/elements/TextInput/component.js, src/components/elements/TextInput/component.spec.js, src/semantic/src/themes/livingstone/elements/input.overrides, src/semantic/src/themes/livingstone/elements/input.variables, src/semantic/src/themes/livingstone/globals/site.variables, styleguide/webpack.config.js, tools/jest/jest.config.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-214)
Creates component, tests and examples for DateRangePicker
Required some consequent changes to `InputController` and input-type elements which consume `InputController`.
=> TE-214 DateRangePicker

src/components/elements/Button/component.js, src/components/elements/DateRangePicker/Readme.md, src/components/widgets/SearchBar/Readme.md, src/components/widgets/SearchBar/component.js, src/components/widgets/SearchBar/component.spec.js, src/components/widgets/SearchBar/index.js, src/components/widgets/SearchBar/mock-data/options.js, src/semantic/src/themes/livingstone/elements/button.variables, src/semantic/src/themes/livingstone/elements/input.overrides, src/semantic/src/themes/livingstone/elements/input.variables, src/semantic/src/themes/livingstone/modules/dropdown.overrides, src/semantic/src/themes/livingstone/modules/dropdown.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-234)
Creates component, tests and examples for SearchBar
Required a couple of consequent changes to existing styles.
=> TE-234 SearchBar

src/components/elements/Checkbox/component.js, src/components/elements/Checkbox/component.spec.js, src/components/elements/DateRangePicker/component.js, src/components/elements/DateRangePicker/component.spec.js, src/components/elements/Dropdown/component.js, src/components/elements/Dropdown/component.spec.js, src/components/elements/InputController/component.js, src/components/elements/InputController/component.spec.js, src/components/elements/RadioButton/Readme.md, src/components/elements/Submenu/adaptOptions.js, src/components/elements/Submenu/adaptOptions.spec.js, src/components/elements/Submenu/component.js, src/components/elements/Submenu/component.spec.js, src/semantic/src/themes/livingstone/collections/menu.variables, src/semantic/src/themes/livingstone/elements/input.overrides, src/semantic/src/themes/livingstone/elements/input.variables, src/semantic/src/themes/livingstone/modules/checkbox.overrides, src/semantic/src/themes/livingstone/modules/checkbox.variables, src/semantic/src/themes/livingstone/modules/dropdown.overrides, src/semantic/src/themes/livingstone/modules/dropdown.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-229)
Makes a number of fixes carried over from sprint six.
=> TE-229 Sprint six style fixes

src/components/elements/InputController/utils/getValue.js, src/components/elements/InputController/utils/getValue.spec.js
Fixes the value checking on InputController. This was causing a post-build bug in live.
=> Fix value checking for InputController

src/semantic/src/themes/livingstone/elements/button.variables, src/semantic/src/themes/livingstone/elements/input.overrides, src/semantic/src/themes/livingstone/modules/dropdown.variables
Change unset to auto && Remove units on zero values.
=> Respond to David PR comments.

package.json, src/components/elements/InputController/component.js, src/components/elements/InputController/component.spec.js, src/components/elements/InputController/utils/getValue.js, src/components/elements/InputController/utils/getValue.spec.js, src/components/elements/PhoneInput/Readme.md, src/components/elements/PhoneInput/component.js, src/components/elements/PhoneInput/component.spec.js, src/components/elements/PhoneInput/index.js, src/components/elements/PhoneInput/utils/getIconOrFlag.js, src/components/elements/PhoneInput/utils/getIconOrFlag.spec.js, src/components/elements/PhoneInput/utils/parseValue.js, src/components/elements/PhoneInput/utils/parseValue.spec.js, src/components/elements/PhoneInput/utils/validFlagNames.js, src/semantic/src/themes/livingstone/elements/input.overrides, src/semantic/src/themes/livingstone/elements/input.variables, src/semantic/src/themes/livingstone/globals/site.variables, src/semantic/src/themes/livingstone/modules/dropdown.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-213)
Adds PhoneInput component, tests and examples.
`props.icon` is a minor addition to InputController.
=> TE-213 PhoneInput

src/components/widgets/Image/Readme.md, src/components/widgets/Image/component.js, src/components/widgets/Image/component.spec.js, src/components/widgets/Image/constants.js, src/components/widgets/Image/index.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-239)
- The Image widget.
- Lazy loading or [react-graceful-image](https://github.com/linasmnew/react-graceful-image) similar techniques will be implemented later.
=> TE-239 Image

Readme.md, semantic.json
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-235)
Specifies components to include in semantic build. 
Added a little guidance to Readme
=> TE-235 Reduce semantic build

src/components/widgets/Video/Readme.md, src/components/widgets/Video/component.js, src/components/widgets/Video/utils/getVideoContent.js, src/components/widgets/Video/utils/getVideoContent.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-241)
- Fixes on the HTML source
=> TE-241 Fixes on the HTML input

semantic.json
Tiny fix to make sure Grid styles are in the semantic build.
=> Add grid to the semantic build

src/components/elements/IconCard/Readme.md, src/components/elements/IconCard/component.js, src/components/elements/IconCard/component.spec.js, src/components/elements/IconCard/index.js, src/semantic/src/themes/livingstone/elements/label.overrides, src/semantic/src/themes/livingstone/elements/label.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-270)
Creates component, styles, examples and tests for IconCard
=> TE-270 Icon card

src/components/collections/Form/Readme.md
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-253)
Adds examples demonstrating changing width of inputs within forms
=> TE-253 Input width examples

package.json, semantic.json
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-289)
Upgrade to semantic-ui v2.3.1
=> TE-289 Upgrade to semantic-ui v2.3.1

lib/expect-helpers/expectComponentToHaveChildren.js, lib/expect-helpers/expectComponentToHaveProps.js, lib/expect-helpers/index.js, src/components/elements/Button/component.spec.js
Create proposed expect helpers to check props and children.
=> TE-312 Sprint eight retrospective - Demo DRYer tests.

Jenkinsfile
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-313)
- After manually fixing the issue for the production deployment, also deleting these unneeded dotfiles is an improvement for the release process.
- After done #62, the #64 PR broke the production automatic release build job due a conflict when syncing CI job's git staged files version and origin's version. [A manual `gh-pages` merge has been executed](https://github.com/lodgify/lodgify-ui/commit/05aa7d24511d31f635dfb23fea59e8d045f968ea) so that the updated generated `index.html` has also then been pushed [here](https://github.com/lodgify/lodgify-ui/commit/f73da4d291c1e2e3434b842923905c32d6f25e6a) so that it gets fixed.
- Once Github cdn gets refreshed, Lodgify UI is accesible with up to date content. Meanwhile, add a …
=> TE-313 Removing unneeded dotfiles

Jenkinsfile
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-316)
Continuation of #77 
- Forcing to overwrite `origin` files with built ones
- See [git push](https://gitirc.eu/git-push.html).
=> TE-316 Force with lease to overwrite remote branch files

semantic.json, src/components/typography/Paragraph/Readme.md, src/components/typography/Paragraph/component.js, src/components/typography/Paragraph/component.spec.js, src/components/widgets/PaymentInformation/Readme.md, src/components/widgets/PaymentInformation/component.js, src/components/widgets/PaymentInformation/component.spec.js, src/components/widgets/PaymentInformation/index.js, src/semantic/src/theme.config, src/semantic/src/themes/livingstone/views/statistic.overrides, src/semantic/src/themes/livingstone/views/statistic.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-306)
- Creates the `PaymentInformation` widget.
- `Statistic` semantic-ui view is used.
=> TE-306 Payment Information widget

src/components/widgets/PropertyDescription/component.js, src/components/widgets/PropertyDescription/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-321)
Adds responsiveness to the PropertyDescription component
=> TE-327 PropertyDescription responsive

src/components/elements/Button/component.js, src/components/elements/Button/component.spec.js, src/components/widgets/Review/component.js, src/components/widgets/Review/component.spec.js, src/components/widgets/Reviews/component.js, src/components/widgets/Reviews/component.spec.js, src/semantic/src/themes/livingstone/elements/button.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-335)
Adds responsiveness to the Reviews component
Added a compact button variable so the vertical padding isn't changed when isCompact prop is added to the Button component.
This ticket required changes across the Review component, Reviews component and Button component.
=> TE-335 Reviews responsive

src/components/elements/Button/component.js, src/components/elements/Button/component.spec.js, src/semantic/src/themes/livingstone/elements/button.overrides, src/semantic/src/themes/livingstone/elements/button.variables
Makes consequent changes to Button element component and styles.
=> TE-301 Change button

src/components/elements/IconCard/component.js, src/components/elements/IconCard/component.spec.js, src/semantic/src/themes/livingstone/elements/label.overrides, src/semantic/src/themes/livingstone/elements/label.variables
Makes consequent changes to IconCard component, tests and styles.
=> TE-301 Change IconCard

src/components/elements/Modal/component.js, src/components/elements/Modal/component.spec.js, src/semantic/src/themes/livingstone/modules/modal.overrides, src/semantic/src/themes/livingstone/modules/modal.variables
Makes consequent changes to Modal component, tests and styles.
=> TE-301 Change Modal

src/components/elements/Pagination/component.js, src/components/elements/Pagination/component.spec.js, src/components/elements/Pagination/navigationMarkup.js, src/semantic/src/themes/livingstone/collections/menu.overrides, src/semantic/src/themes/livingstone/collections/menu.variables
Makes consequent changes to Pagination component, tests and styles.
=> TE-301 Change Pagination

src/components/elements/Submenu/component.js, src/components/elements/Submenu/component.spec.js
Makes consequent changes to Submenu component and tests.
=> TE-301 Change Submenu

src/components/elements/DateRangePicker/component.js, src/components/elements/DateRangePicker/component.spec.js, src/components/elements/Dropdown/component.js, src/components/elements/Dropdown/component.spec.js, src/components/elements/InputController/component.js, src/components/elements/InputController/component.spec.js, src/components/elements/PhoneInput/utils/getIconOrFlag.js, src/components/elements/PhoneInput/utils/getIconOrFlag.spec.js, src/semantic/src/themes/livingstone/elements/input.overrides, src/semantic/src/themes/livingstone/elements/input.variables, src/semantic/src/themes/livingstone/modules/dropdown.overrides, src/semantic/src/themes/livingstone/modules/dropdown.variables
Makes consequent changes to input-type elements.
=> TE-301 Change inputs

src/components/elements/Tooltip/component.js, src/components/elements/Tooltip/component.spec.js, src/components/elements/Tooltip/getTriggerMarkup.js
Makes consequent changes to Tooltip component and tests.
=> TE-301 Change Tooltip

src/components/widgets/FeaturedProperty/component.js, src/components/widgets/FeaturedProperty/component.spec.js, src/components/widgets/PropertySummary/component.js, src/components/widgets/PropertySummary/component.spec.js, src/semantic/src/themes/livingstone/modules/rating.overrides
Makes consequent changes to components consuming `Rating`, tests and styles.
=> TE-301 Change Rating

src/components/widgets/ResponsiveImage/component.js, src/components/widgets/SearchBar/component.js, src/components/widgets/SearchBar/component.spec.js, src/components/widgets/Slideshow/utils/renderNavButton.js, src/components/widgets/Slideshow/utils/renderNavButton.spec.js
Makes tweaks to Icon-consuming widgets and tests.
=> TE-301 Tweaks to Icon-consuming widgets

src/components/layout/Grid/component.spec.js, src/components/layout/GridColumn/component.spec.js, src/components/layout/GridRow/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-336)
- Adding tests to the only miserable missing components
=> TE-336 Grid, GridColumn and GridRow tests

src/components/widgets/PaymentInformation/component.js, src/components/widgets/PaymentInformation/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-334)
Gives the PaymentInformation widget a mobile friendly layout
=> TE-334 PaymentInformation responsive layout

src/components/collections/Form/Readme.md, src/components/widgets/CallMeBack/Readme.md, src/components/widgets/Contact/Readme.md, src/components/widgets/OwnerLogin/Readme.md, src/components/widgets/OwnerSignUp/Readme.md, src/semantic/src/themes/livingstone/collections/form.overrides, src/semantic/src/themes/livingstone/globals/site.variables, src/semantic/src/themes/livingstone/views/card.overrides, src/semantic/src/themes/livingstone/views/card.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-322)
Adds responsive styles for Form collection.
Tweaks examples which consume `Form`
=> TE-322 Form responsive

src/components/property-page-widgets/Description/component.js, src/components/property-page-widgets/Description/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-241)
Makes tweaks to Description to fix responsive behaviour.
=> TE-241 Description fixes

styleguide/styleguide-components/LogoRenderer/component.js, styleguide/styleguide-components/MobilePlaceholder/component.js, styleguide/styleguide-components/MobilePlaceholder/getMailToHref.js, styleguide/styleguide-components/MobilePlaceholder/index.js, styleguide/styleguide-components/StyleGuideRenderer/component.js, styleguide/styleguide-components/StyleGuideRenderer/getIsDevelopmentServer.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-351)
Adds placeholder screen for mobile view in production
=> TE-351 Add placeholder screen for mobile view in production

styleguide/config/options/styles.js, styleguide/config/options/theme.js, styleguide/styleguide-components/ComponentsListRenderer/component.js, styleguide/styleguide-components/ComponentsListRenderer/index.js, styleguide/styleguide-components/index.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-347)
Updates the sidebars typography and the sidebars link active states
=> TE-347 Sidebar Typography

lib/with-responsive/withResponsive.js, lib/with-responsive/withResponsive.spec.js, src/components/collections/Form/Readme.md, src/components/general-widgets/CallMeBack/Readme.md, src/components/general-widgets/Contact/Readme.md, src/components/general-widgets/OwnerLogin/Readme.md, src/components/general-widgets/OwnerSignUp/Readme.md, styleguide/config/base.js, styleguide/config/options/theme.js, styleguide/styleguide-components/AlphaFlag/component.js, styleguide/styleguide-components/PlaygroundRenderer/component.js, styleguide/styleguide-components/PlaygroundRenderer/index.js, styleguide/styleguide-components/StyleGuideRenderer/component.js, styleguide/styleguide-components/index.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-350)
Creates a side-by-side code editor panel on wide screens.
- on screens less than 1200px, it falls back on the previous editor setup.
- I am not as religious in the organisation of styleguidist components as I am with our own. I hope you don't tell me off too much.
**Hide/Show***
**Fallback on smaller screens***
=> TE-350 Side-by-side editor

styleguide/config/options/styles.js, styleguide/docs/getStarted.md, styleguide/styleguide-components/PlaygroundRenderer/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-355)
Adds some holding copy to the 'Get started' section.
=> TE-355 Add 'Get started' copy

package.json, styleguide/config/options/theme.js, styleguide/styleguide-components/PlaygroundRenderer/component.js, styleguide/styleguide-components/StyleGuideRenderer/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-359)
- Adds `background-blend-mode: soft-light` to the code panel
- Adds responsive padding to the content panel
- Adds transition management to the code editor blocks
=> TE-359 Fixes from sprint review

styleguide/styleguide-components/LogoRenderer/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-356)
Responds to https://github.com/lodgify/lodgify-ui/pull/132#discussion_r186267087
=> TE-356 Add alt text to Lodgify UI logo image

styleguide/styleguide-components/StyleGuideRenderer/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-359)
Responds to https://github.com/lodgify/lodgify-ui/pull/136#discussion_r186267310
=> TE-359 Add will-change to styleguide content panel

src/index.js, styleguide/config/options/sections.js, styleguide/docs/getStarted.md, styleguide/docs/introduction.md
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-362)
Adds the API for all the components to be consumed
Added documentation for importing the styles and the components
=> TE-362 Propose package api

.travis.yml
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-379)
Add branch:production condition to gh-pages deploy step
=> TE-379 Add branch:production condition to gh-pages deploy step

Readme.md, docs/CONTRIBUTING.md, docs/CONVENTIONS.md
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-372)
Updates the Readme to be more consumer facing not contributor facing
=> TE-372 Update readme

.travis.yml, package.json
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-376)
Adds test implementation of semantic-release to travis configuration
Depends implicitly on the following environment variables in travis settings...
=> TE-376 Test install semantic-release

.travis.yml
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-376)
Set semantic-release branch to production
=> TE-376 Set semantic-release branch to production

docs/CONTRIBUTING.md
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-383)
Fixes the broken link on the CONTRIBUTING.md to CONVENTIONS.md
=> TE-383 Fix CONTRIBUTING.md broken link

.travis.yml
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-384)
Adds Travis build slack notifications
Removes Travis build email notifications
=> TE-384 Add slack notification integration

package.json
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-392)
Add --no-save flag to npm install:peers script
=> TE-392 Add --no-save flag to npm install:peers script

package.json
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-391)
Adds Commitizen to enforce commit message conventions
no other notes
=> TE-391 Add Commitizen to enforce commit message conventions

src/components/collections/Table/Readme.md, src/components/collections/Table/component.js, src/components/collections/Table/component.spec.js, src/components/collections/Table/index.js, src/components/collections/Table/mock-data/props.js, src/styles/semantic/semantic.less, src/styles/semantic/theme.config, src/styles/semantic/themes/livingstone/collections/table.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-398)
Exposes a `Table` collection from Lodgify UI
=> TE-398 Add Table collection

package.json
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-401)
I slightly screwed up #166 . This fixes the path.
=> TE-401 Add semantic-release plugins

src/components/collections/Table/component.js, src/components/collections/Table/component.spec.js, src/components/collections/Table/utils/getTextAlign.js, src/components/collections/Table/utils/getTextAlign.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-406)
Aligns all table cells in the first column to the left and all others to the center
=> TE-406 Table text alignment

src/components/typography/Paragraph/Readme.md, src/components/typography/Paragraph/component.js, src/styles/semantic/themes/livingstone/globals/site.overrides, src/styles/semantic/themes/livingstone/globals/site.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-407)
Add heavy and light `Paragraph` weight variations
=> TE-407 Add heavy and light `Paragraph` weight variations

.travis.yml
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-384)
Remove the travis and slack integration
=> TE-384 Remove travis slack notifications

src/components/property-page-widgets/Rates/component.js, src/components/property-page-widgets/Rates/component.spec.js, src/components/property-page-widgets/Rates/mock-data/options.js, src/components/property-page-widgets/Rates/utils/getMobileRateRowMarkup.js, src/components/property-page-widgets/Rates/utils/getMobileRateRowMarkup.spec.js, src/components/property-page-widgets/Rates/utils/getRoomTypeDropdownMarkup.js, src/components/property-page-widgets/Rates/utils/getRoomTypeDropdownMarkup.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-409)
Add responsive layout to the Rates widget
=> TE-409 Rates widget responsive layout

src/components/general-widgets/FeaturedRoomType/Readme.md, src/components/general-widgets/FeaturedRoomType/component.js, src/components/general-widgets/FeaturedRoomType/component.spec.js, src/components/general-widgets/FeaturedRoomType/index.js, src/components/general-widgets/FeaturedRoomType/utils/getRoomTypeDescription.js, src/components/general-widgets/FeaturedRoomType/utils/getRoomTypeDescription.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-416)
Add FeaturedRoomType component and its unit test
=> TE-416-featured-room-type

src/components/general-widgets/CallMeBack/component.js, src/components/general-widgets/CallMeBack/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-438)
Fixes the CallMeBack widget by using the SingleDatePicker input
=> TE-438 Fix CallMeBack

src/components/media/Slideshow/Readme.md, src/components/media/Slideshow/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-436)
Adjusts which props are required
Included example props in the Readme
=> TE-436 Fix Slideshow props

styleguide/styleguide-components/PlaygroundRenderer/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-442)
Stops content in styleguide preview from collapsing
=> TE-442 Fix overflow on styleguide preview

src/components/general-widgets/Contact/component.js, src/components/general-widgets/Contact/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-445)
Expose `onChangePropertyDropdown` function on Contact widget
=> TE-445 Contact widget: Expose onChangePropertyDropdown

src/components/collections/Form/component.js, src/components/general-widgets/OwnerLogin/component.js, src/components/general-widgets/OwnerLogin/component.spec.js, src/components/general-widgets/OwnerLogin/utils/getForgotPasswordFormMarkup.js, src/components/general-widgets/OwnerLogin/utils/getForgotPasswordFormMarkup.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-446)
Add forgot password ui
=> TE-446 Add forgot password ui

src/styles/semantic/themes/livingstone/modules/modal.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-446)
Remove margin-top from .ui.modal > .ui.card
=> TE-446 Remove margin-top from .ui.modal > .ui.card

src/components/general-widgets/FeaturedRoomType/component.js, src/components/general-widgets/FeaturedRoomTypes/Readme.md, src/components/general-widgets/FeaturedRoomTypes/component.js, src/components/general-widgets/FeaturedRoomTypes/component.spec.js, src/components/general-widgets/FeaturedRoomTypes/index.js, src/index.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-450)
Add component, examples, tests and api for `FeaturedRoomTypes`
=> TE-450 FeaturedRoomTypes

src/components/general-widgets/FeaturedProperties/Readme.md, src/components/general-widgets/FeaturedProperties/component.js, src/components/general-widgets/FeaturedProperties/component.spec.js, src/components/general-widgets/FeaturedProperties/index.js, src/index.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-451)
Add component, examples and tests for `FeaturedProperties`
=> TE-451 FeaturedProperties

src/components/general-widgets/CallMeBack/component.spec.js, src/components/general-widgets/Contact/component.spec.js, src/components/general-widgets/OwnerLogin/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-441)
consume @lodgify/enzyme-jest-expect-helpers in the unit tests
=> TE-441 Contact, OwnerLogin and CallMeBack unit test refactor

src/components/inputs/Dropdown/component.js, src/components/inputs/Dropdown/utils/adaptOptions.js, src/components/inputs/Dropdown/utils/adaptOptions.spec.js, src/components/inputs/Dropdown/utils/getDefaultValue.js, src/components/inputs/Dropdown/utils/getDefaultValue.spec.js, src/components/inputs/Dropdown/utils/getHasImages.js, src/components/inputs/Dropdown/utils/getHasImages.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-461)
Unify options and optionsWithImages to cover a missing case where disabled wasn't checking optionsWithImages.
=> TE-461 Dropdown fix isDisabled

src/components/collections/Form/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-440)
Add check for input.props.onChange before call
=> TE-440 Add check for input.props.onChange before call

src/components/collections/Footer/component.js, src/components/elements/Submenu/component.js, src/components/general-widgets/CallMeBack/component.js, src/components/general-widgets/Contact/component.js, src/components/general-widgets/SearchBar/component.js, src/components/inputs/Dropdown/component.js, src/components/property-page-widgets/PropertySearchBar/component.js, src/components/property-page-widgets/Rates/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-498)
Fixes Dropdown value prop type and every component consuming Dropdown
=> TE-498 Fix Dropdown prop types

src/components/elements/Divider/component.spec.js, src/components/elements/Link/component.spec.js, src/components/property-page-widgets/Rates/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-527)
Refactor the old specs to use the new @lodgify/enzyme-jest-expect-helpers
=> TE-527 Link, Rates and Divider test refactor

src/components/inputs/Dropdown/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-536)
Refactors the Dropdown `component.spec.js` to use the @lodgify/enzym-jest-expect-helpers
=> TE-536 Refactor Dropdown spec

src/components/elements/Submenu/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-531)
Refactors the Submenu component.spec.js to use the @lodgify/enzym-jest-expect-helpers
=> TE-531 Refactor Submenu to use expect helpers

src/components/elements/Tooltip/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-532)
Updates Tooltip spec to use @lodgify expect helpers
=> TE-532 Refactor Tooltip spec

src/components/inputs/PhoneInput/component.spec.js, src/components/inputs/RadioButton/component.spec.js, src/components/inputs/TextArea/component.spec.js, src/components/inputs/TextInput/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-539)
Refactors PhoneInput, RadioButton, TextInput and TextArea to use the `@lodgify/enzym-jest-expect-helpers`
=> TE-539 PhoneInput, RadioButton, TextInput and TextArea unit test refactor

src/components/inputs/InputController/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-538)
Refactors the InputController component.spec.js to use the @lodgify/enzym-jest-expect-helpers
=> TE-538 Refactor InputController to use expect helpers

src/components/collections/Form/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-516)
Update form unit test to consume @lodgify/enzyme-jest-expect-helpers
=> TE-516 Form unit test refactor

src/components/collections/Header/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-552)
Update Header unit test to consume @lodgify/enzyme-jest-expect-helpers
=> TE-552 Header unit test refactor

src/components/elements/Modal/component.spec.js, src/components/elements/Pagination/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-528)
Updates Modal and Pagination unit tests to use @lodgify/enzym-jest-expect-helpers
=> TE-528 Modal and Pagination unit test refactor

src/components/general-widgets/MultiRoomType/Readme.md, src/components/general-widgets/MultiRoomType/component.js, src/components/general-widgets/MultiRoomType/component.spec.js, src/components/general-widgets/MultiRoomType/index.js, src/components/general-widgets/MultiRoomType/utils/getRatingMarkup.js, src/components/general-widgets/MultiRoomType/utils/getRatingMarkup.spec.js, src/components/general-widgets/MultiRoomType/utils/getRoomFeaturesMarkup.js, src/components/general-widgets/MultiRoomType/utils/getRoomFeaturesMarkup.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-578)
This update will make the MultiRoomType component responsive
=> TE-578 Make the MultiRoomType component responsive

src/components/inputs/CaptchaInput/component.spec.js, src/components/inputs/Checkbox/component.spec.js, src/components/inputs/ErrorMessage/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-537)
Updates ErrorMessage, CaptchaInput and Checkbox specs to use @lodgify/enzym-jest-expect-helpers
=> TE-537 ErrorMessage, CaptchaInput and Checkbox unit test refactor

src/components/media/Slideshow/component.js, src/components/media/Slideshow/component.spec.js, src/components/property-page-widgets/RoomType/component.js, src/components/property-page-widgets/RoomType/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-577)
- Exposes new props in `Slideshow` and refactors `RoomType` to use those props
- https://github.com/lodgify/lodgify-ui/pull/210/files#r200942858
- https://github.com/lodgify/lodgify-ui/pull/210/files#r200944671
- https://github.com/lodgify/lodgify-ui/pull/210/files#r200943233
=> TE-577 RoomType PR changes

src/components/elements/Icon/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-587)
Adds a missing proptype value to remove console warning
=> TE-587 Add Icon missing prop type value

src/components/general-widgets/FeaturedProperty/component.js, src/components/general-widgets/FeaturedProperty/component.spec.js, src/components/general-widgets/FeaturedRoomType/component.js, src/components/general-widgets/FeaturedRoomType/component.spec.js, src/components/property-page-widgets/RoomType/component.js, src/components/property-page-widgets/RoomType/component.spec.js, src/components/property-page-widgets/Summary/component.js, src/components/property-page-widgets/Summary/component.spec.js, src/utils/get-night-price-markup/getNightPriceMarkup.js, src/utils/get-night-price-markup/getNightPriceMarkup.spec.js, src/utils/get-night-price-markup/index.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-593)
Implements the `getNightPrice` util to the respective components and updates its unit tests
=> TE-593 Add getNightPrice markup util

src/components/collections/Footer/utils/getGroupedNavigationItems.spec.js, src/components/collections/Header/component.spec.js, src/components/property-page-widgets/RoomType/utils/getPluralString.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-602)
Adds the missing unit tests for `Header`, `getPluralString` and `Footer`.
=> TE-602 Improve overall test coverage

src/components/property-page-widgets/Availability/component.js, src/components/property-page-widgets/Availability/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-613)
Get availability component spec coverage to 100%
=> TE-613 Get availability component spec coverage to 100%

src/components/elements/Icon/component.spec.js, src/components/property-page-widgets/Amenities/Readme.md, src/components/property-page-widgets/Amenities/component.js, src/components/property-page-widgets/Amenities/component.spec.js, src/components/property-page-widgets/Amenities/utils/getCategoryMarkup.js, src/components/property-page-widgets/Amenities/utils/getCategoryMarkup.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-611)
Adds the responsive layout for the extended Amenities component
- Changed example icons
=> TE-611 Amenities responsive

src/components/elements/Icon/component.js, src/components/elements/Icon/component.spec.js, src/components/property-page-widgets/Amenities/Readme.md, src/components/property-page-widgets/Amenities/component.js, src/components/property-page-widgets/Amenities/component.spec.js, src/components/property-page-widgets/Amenities/mock-data/amenities.js, src/components/property-page-widgets/Amenities/utils/getCategoryMarkup.js, src/components/property-page-widgets/Amenities/utils/getCategoryMarkup.spec.js, src/components/property-page-widgets/Amenities/utils/getDefaultItems.js, src/components/property-page-widgets/Amenities/utils/getDefaultItems.spec.js, src/components/property-page-widgets/Amenities/utils/getFormattedAmenityItems.js, src/components/property-page-widgets/Amenities/utils/getFormattedAmenityItems.spec.js, src/components/property-page-widgets/Amenities/utils/hasExtraItems.js, src/components/property-page-widgets/Amenities/utils/hasExtraItems.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-610)
Reworks the Amenities component to allow for amenities to always be categorised 
- Expose labelWeight prop in `Icon`
=> TE-610 Extend Amenities

src/components/collections/Footer/component.js, src/components/collections/Footer/component.spec.js, src/components/elements/Icon/Readme.md, src/components/elements/Icon/component.js, src/components/elements/Icon/component.spec.js, src/components/general-widgets/SearchBar/component.js, src/components/property-page-widgets/Amenities/utils/getCategoryMarkup.js, src/components/property-page-widgets/Amenities/utils/getCategoryMarkup.spec.js, src/components/property-page-widgets/Availability/component.js, src/components/property-page-widgets/Availability/component.spec.js, src/components/property-page-widgets/Description/component.js, src/components/property-page-widgets/Description/component.spec.js, src/components/property-page-widgets/Description/mock-data/props.js, src/components/property-page-widgets/RoomType/Readme.md, src/components/property-page-widgets/RoomType/component.js, src/components/property-page-widgets/RoomType/component.spec.js, src/components/property-page-widgets/RoomType/utils/getModalContentMarkup.js, src/components/property-page-widgets/RoomType/utils/getModalContentMarkup.spec.js, src/components/property-page-widgets/RoomType/utils/getRoomFeaturesMarkup.js, src/components/property-page-widgets/RoomType/utils/getRoomFeaturesMarkup.spec.js, src/components/property-page-widgets/Rules/component.js, src/components/property-page-widgets/Rules/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-614)
Update `Icon` prop from `label` to `labelText` for clarity
=> TE-614 Rename Icon label prop

package.json, styleguide/config/base.js, styleguide/config/options/sections.js, styleguide/docs/getStarted.md, styleguide/styleguide-components/ComponentsListRenderer/component.js
Fixes broken slugs in styleguidist.
Tiny fix to a bad heading in `getStarted.md` in there too.
=> TE-620 Fix broken slugs

src/components/media/Slideshow/Readme.md, src/components/media/Slideshow/component.js, src/components/media/Slideshow/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-618)
Add headingText to Slideshow
=> TE-618 Add headingText to Slideshow

src/components/property-page-widgets/Amenities/Readme.md, src/components/property-page-widgets/Amenities/component.js, src/components/property-page-widgets/Amenities/component.spec.js, src/components/property-page-widgets/Amenities/index.js, src/components/property-page-widgets/RoomType/Readme.md, src/components/property-page-widgets/RoomType/component.js, src/components/property-page-widgets/RoomType/component.spec.js, src/components/property-page-widgets/RoomType/utils/getModalContentMarkup.js, src/components/property-page-widgets/RoomType/utils/getModalContentMarkup.spec.js, src/components/property-page-widgets/RoomType/utils/getRatingMarkup.js, src/components/property-page-widgets/RoomType/utils/getRoomFeaturesMarkup.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-626)
Standardise amenities array in RoomType component
And add a prop to amenities to determine if the amenity items should be stacked
=> TE-626 Standardise amenities array in component

src/components/elements/Modal/Readme.md, src/components/elements/Modal/component.js, src/components/elements/Modal/component.spec.js, src/styles/semantic/themes/livingstone/modules/modal.overrides, src/styles/semantic/themes/livingstone/modules/modal.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-640)
Add fullscreen option to modal
=> TE-640 Add fullscreen option to modal

src/components/collections/Header/component.js, src/components/collections/Header/component.spec.js, src/components/collections/Header/index.js, src/components/collections/Header/utils/getDesktopMenuMarkup.js, src/components/collections/Header/utils/getDesktopMenuMarkup.spec.js, src/components/collections/Header/utils/getLinkMarkup.js, src/components/collections/Header/utils/getLinkMarkup.spec.js, src/components/collections/Header/utils/getLogoMarkup.js, src/components/collections/Header/utils/getLogoMarkup.spec.js, src/components/collections/Header/utils/getMobileMenuMarkup.js, src/components/collections/Header/utils/getMobileMenuMarkup.spec.js, src/styles/semantic/semantic.less, src/styles/semantic/themes/livingstone/collections/menu.overrides, src/styles/semantic/themes/livingstone/collections/menu.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-630)
Adds responsive structure and styles for `Header`
=> TE-630 `Header` responsive

src/styles/semantic/definitions/third-party-components/react-image-gallery.less, src/styles/semantic/semantic.less, src/styles/semantic/theme.config, src/styles/semantic/themes/default/third-party-components/react-image-gallery.variables, src/styles/semantic/themes/livingstone/collections/menu.overrides, src/styles/semantic/themes/livingstone/collections/menu.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-659)
Move `react-image-gallery` styles into its own definition file in `third-party-components`
=> TE-659: Create definition files for the image gallery

package.json
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-696)
Fixes vulnerabilities reported by `npm audit`
- I could not fully resolve the vulnerabilities as this would involve a major update of `less` to `3.8.0`, this introduces breaking changes.
- This change involves removing `npm` as a dependency. We should specific the version of npm, with the `engines` option in package.json https://docs.npmjs.com/files/package.json
=> TE-696: Fix vulnerabilities reported by npm audit

src/components/general-widgets/Promotion/Readme.md, src/components/general-widgets/Promotion/component.js, src/components/general-widgets/Promotion/component.spec.js, src/components/general-widgets/Promotion/index.js, src/index.js, src/styles/semantic/themes/livingstone/elements/segment.overrides, src/styles/semantic/themes/livingstone/elements/segment.variables, src/styles/semantic/themes/livingstone/views/statistic.overrides, src/styles/semantic/themes/livingstone/views/statistic.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-711)
Implements the Promotion component
- CSS has been used to handle the hover blur effect and to displays the hover state button
- CSS has been used to overlay the image with a dark mask, this will make the text more readable
- The PR will also improve the styling for the Statistic component
__Preview__
__Code Coverage__
=> TE-711: Implement the Promotion component

src/components/property-page-widgets/Description/component.js, src/components/property-page-widgets/Description/component.spec.js, src/components/property-page-widgets/Description/utils/getEllipsis.js, src/components/property-page-widgets/Description/utils/getEllipsis.spec.js, src/components/property-page-widgets/Description/utils/isDescriptionDisplayingWithEllipsis.js, src/components/property-page-widgets/Description/utils/isDescriptionDisplayingWithEllipsis.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-476)
Update the `Description` component with the `getDescriptionWithElipsis`util
=> TE-476 `Description`: Add ellipsis to end of `descriptionText`

src/components/collections/Header/Readme.md, src/components/collections/Header/utils/getMobileMenuMarkup.js, src/components/collections/Header/utils/getMobileMenuMarkup.spec.js, src/components/collections/Header/utils/hasSearchBarOptions.js, src/components/collections/Header/utils/hasSearchBarOptions.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-742)
Renders `SearchBar` only if the relevant options props are defined and populated.
=> TE-742 `Header` search bar options

src/components/collections/Header/utils/getDesktopMenuMarkup.spec.js, src/components/collections/Header/utils/getMobileMenuMarkup.spec.js, src/components/general-widgets/SearchBar/component.spec.js, src/components/property-page-widgets/Description/component.spec.js, src/components/property-page-widgets/Description/utils/formatParagraphWithModal.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-793)
Updates specs to ignore Fragments
=> TE-793 Refactor fragment test cases

src/components/collections/Footer/component.js, src/components/elements/Button/component.js, src/components/elements/Icon/component.js, src/components/elements/IconCard/component.js, src/components/property-page-widgets/Amenities/component.js, src/components/property-page-widgets/Description/component.js, src/components/property-page-widgets/KeyFacts/component.js, src/components/property-page-widgets/Location/component.js, src/components/property-page-widgets/RoomType/component.js, src/components/property-page-widgets/SleepingArrangements/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-790)
Updates references to the semantic ui icon list
Adds missing prop descriptions for RoomType component
=> TE-790 Update icon list references

src/components/layout/GridColumn/component.js, src/components/layout/GridColumn/component.spec.js, src/utils/with-responsive/withResponsive.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-798)
Adds width as a prop for GridColumn
=> TE-798: Add width as a prop for GridColumn

src/components/property-page-widgets/Location/Readme.md, src/components/property-page-widgets/Location/component.js, src/components/property-page-widgets/Location/component.spec.js, src/utils/default-strings/constants.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-886)
Exposes the string prop for the `Location`
__Preview__
=> TE-886: Expose string prop for Location

src/components/general-widgets/OwnerSignUp/Readme.md
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-920)
Fixes a typo I missed yesterday 🙊
=> TE-920 Fix typo in OwnerSignUp example

src/components/property-page-widgets/Description/Readme.md, src/components/property-page-widgets/Description/component.js, src/components/property-page-widgets/Description/component.spec.js, src/utils/default-strings/constants.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-926)
Exposes `homeHighlightHeadingText` string prop, adds respective unit tests and examples.
=> TE-926 Description expose string prop

src/components/collections/Form/Readme.md, src/components/collections/Form/component.js, src/components/collections/Form/utils/getValidationWithDefaults.js, src/components/collections/Form/utils/getValidationWithDefaults.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-930)
Expose isRequiredMessage on Form
=> TE-930 Expose isRequiredMessage on Form

src/components/collections/Form/Readme.md, src/components/collections/Form/component.js, src/components/collections/Form/component.spec.js, src/components/collections/Form/utils/getEmptyRequiredInputs.js, src/components/collections/Form/utils/getEmptyRequiredInputs.spec.js, src/components/collections/Form/utils/getIsSubmitButtonDisabled.js, src/components/collections/Form/utils/getIsSubmitButtonDisabled.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-929)
Disable `Form` submit if inputs have errors
=> TE-929 Disable `Form` submit if inputs have errors

src/styles/semantic/definitions/third-party-components/react-dates-datepicker.less, src/styles/semantic/themes/livingstone/views/card.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-909)
Removes overflow hidden from the form card container
- Makes the button selector more inclusive, since the buttons are now `div` elements in the latest React dates version (17.2.0)
__Before__
__After__
=> TE-909: fix issues with the Datepicker style

src/styles/semantic/themes/livingstone/views/card.overrides, src/styles/semantic/themes/livingstone/views/card.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-953)
Adds styles to center the form and limits it's max width
=> TE-953: Form fix max-width

src/styles/semantic/themes/livingstone/elements/segment.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-956)
Changes the colour from dark yellow to yellow
=> TE-956: Fix Promotion discount background colour

src/styles/semantic/themes/livingstone/collections/menu.overrides, src/styles/semantic/themes/livingstone/collections/menu.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-976)
Fix the hover state of the social media icons
=> TE-976 Social icon hover state

src/components/general-widgets/FeaturedRoomType/Readme.md, src/styles/semantic/themes/livingstone/views/card.overrides, src/styles/semantic/themes/livingstone/views/card.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-990)
Fix height of featured cards to 400px and image to fill available space
- Updated some docs which got forgotten about
=> TE-990 Featured cards fix height

src/components/collections/Footer/component.js, src/components/collections/Footer/component.spec.js, src/styles/semantic/themes/livingstone/collections/menu.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-983)
Enables a user to select the copyright data, phone number and property address
=> TE-983 Highlight Footer content

src/index.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1054)
Exports the `Hero` component
=> TE-1054: export the `Hero` component

src/components/collections/Footer/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1048)
Adds `size` from lodash in to `socialMediaLinks` to make the code more stable agains `null` and `undefined`
=> TE-1048 Fix socialMediaLinks

src/components/collections/HomepageHero/utils/getSearchBarMarkup.js, src/components/collections/HomepageHero/utils/getSearchBarMarkup.spec.js, src/components/general-widgets/SearchBar/Readme.md, src/components/general-widgets/SearchBar/component.js, src/components/general-widgets/SearchBar/utils/getFormFieldMarkup.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1080)
Changes the HomepageHero dropdowns to always open above.
=> TE-1080 HomepageHero search bar dropdowns

src/components/property-page-widgets/Summary/Readme.md, src/components/property-page-widgets/Summary/component.js, src/components/property-page-widgets/Summary/component.spec.js, src/components/property-page-widgets/Summary/index.js, src/components/property-page-widgets/Summary/utils/getHeadingMarkup.js, src/components/property-page-widgets/Summary/utils/getHeadingMarkup.spec.js, src/components/property-page-widgets/Summary/utils/getLocationNameMarkup.js, src/components/property-page-widgets/Summary/utils/getLocationNameMarkup.spec.js, src/components/property-page-widgets/Summary/utils/getRatingAndNightPriceMarkup.js, src/components/property-page-widgets/Summary/utils/getRatingAndNightPriceMarkup.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1066)
Adapts the `Summary` component to mobile resolution
=> TE-1066 Adapt Summary component for mobile

src/components/collections/Header/Readme.md, src/components/collections/Header/component.js, src/components/collections/Header/component.spec.js, src/styles/semantic/themes/livingstone/collections/menu.overrides, src/styles/semantic/themes/livingstone/globals/site.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1082)
Exposes `isBackgroundFilled` on `Header`
=> TE-1082 Expose `isBackgroundFilled` on `Header` 

src/components/collections/Header/Readme.md, src/components/collections/Header/component.js, src/components/collections/Header/utils/getMobileMenuMarkup.js, src/components/collections/Header/utils/getMobileMenuMarkup.spec.js, src/components/collections/Hero/Readme.md, src/components/collections/Hero/component.js, src/components/collections/Hero/component.spec.js, src/components/general-widgets/HomepageHero/Readme.md, src/components/general-widgets/HomepageHero/component.js, src/components/general-widgets/HomepageHero/component.spec.js, src/components/general-widgets/SearchBar/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1103)
Exposes additional props that are required by the SearchBar in `Heading`, `Hero` and `HomepageHero`.
=> TE-1103 Align Header, Hero and HomepageHero props

src/components/collections/Header/component.js, src/components/collections/Header/utils/getMobileMenuMarkup.js, src/components/collections/Header/utils/getMobileMenuMarkup.spec.js, src/components/collections/Hero/component.js, src/components/collections/Hero/component.spec.js, src/components/general-widgets/HomepageHero/component.js, src/components/general-widgets/HomepageHero/component.spec.js, src/components/property-page-widgets/PropertyPageHero/Readme.md, src/components/property-page-widgets/PropertyPageHero/component.js, src/components/property-page-widgets/PropertyPageHero/component.spec.js, src/components/property-page-widgets/PropertyPageHero/mock-data/mock-data.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1103)
Exposes additional props on the PropertyPageHero component
=> TE-1103 Expose additional props in PropertyPageHero

src/components/general-widgets/HomepageHero/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1146)
Remove requirement from `locationOptions` as it's not present in a single property site
=> TE-1146 Remove requirement from locationOptions

src/components/media/Video/component.js, src/components/media/Video/component.spec.js, src/styles/semantic/definitions/third-party-components/react-player.less
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1150)
When `props.isResponsive === true` iframes now also respect their container.
- Slight refactor of `spec` and `component`.
=> TE-1150 Video overflowing fix

src/components/collections/Header/utils/getDesktopMenuMarkup.js, src/components/collections/Header/utils/getDesktopMenuMarkup.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1184)
Makes the CTA button in the header have rounded corners
=> TE-1184 Make CTA in header rounded

src/components/general-widgets/SearchBar/component.js, src/components/property-page-widgets/PropertyPageSearchBar/Readme.md, src/components/property-page-widgets/PropertyPageSearchBar/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageSearchBar/component.js, src/components/property-page-widgets/PropertyPageSearchBar/component.spec.js, src/components/property-page-widgets/PropertyPageSearchBar/index.js, src/components/property-page-widgets/PropertyPageSearchBar/mock-data/options.js, src/index.js, src/styles/semantic/themes/livingstone/globals/site.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1216)
Implements the new `PropertyPageSearchBar` component and its unit tests. It will serve as a responsive wrapper for the `SearchBar` component with the particularity of being displayed always as fixed. 
* The wrapper of the `SearchBar` component was also slightly modified in order to fix unintended width behaviour.
=> TE-1216 Improve the SearchForm when displayed fixed

src/components/collections/Header/utils/__snapshots__/getDesktopMenuMarkup.spec.js.snap, src/components/collections/Header/utils/__snapshots__/getMobileMenuMarkup.spec.js.snap, src/components/collections/Header/utils/getDesktopMenuMarkup.spec.js, src/components/collections/Header/utils/getMobileMenuMarkup.spec.js, src/components/layout/ShowOnDesktop/__snapshots__/component.spec.js.snap, src/components/layout/ShowOnDesktop/component.spec.js, src/components/layout/ShowOnMobile/__snapshots__/component.spec.js.snap, src/components/layout/ShowOnMobile/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1252)
Updates some snapshot tests to use `Mount` rather than `Shallow`
=> TE-1252: When snapshot testing, use mount and not shallow

src/components/collections/Hero/__snapshots__/component.spec.js.snap, src/components/collections/Hero/component.js, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/component.js, src/components/general-widgets/Promotion/__snapshots__/component.spec.js.snap, src/components/general-widgets/Promotion/component.js, src/components/media/FullBleed/__snapshots__/component.spec.js.snap, src/components/media/FullBleed/component.js, src/components/media/Gallery/component.js, src/components/property-page-widgets/Pictures/component.js, src/components/property-page-widgets/PropertyPageHero/component.js, src/styles/semantic/themes/livingstone/elements/segment.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1299)
All the components that are consuming ResponsiveImage have the ability to gracefully load it's image/images
=> TE-1299 Image components prop alignment

package.json, src/styles/semantic/themes/default/third-party-components/react-dates-datepicker.variables, src/styles/semantic/themes/livingstone/collections/grid.variables, src/styles/semantic/themes/livingstone/collections/menu.variables, src/styles/semantic/themes/livingstone/elements/icon.variables, src/styles/semantic/themes/livingstone/elements/input.overrides, src/styles/semantic/themes/livingstone/globals/site.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1307)
Unpins the Stylelint version since `https://github.com/stylelint/stylelint/issues/3749` has been resolved
- Also fixed a few linting issues that were being reported from the new version of Stylelint
=> TE-1307: Unpin Stylelint and fix any lint issues

src/components/general-widgets/CallMeBack/Readme.md, src/components/general-widgets/CallMeBack/__snapshots__/component.spec.js.snap, src/components/general-widgets/CallMeBack/component.js, src/components/general-widgets/CallMeBack/component.spec.js, src/components/general-widgets/Contact/Readme.md, src/components/general-widgets/Contact/__snapshots__/component.spec.js.snap, src/components/general-widgets/Contact/component.js, src/components/general-widgets/Contact/component.spec.js, src/components/general-widgets/OwnerLogin/Readme.md, src/components/general-widgets/OwnerLogin/__snapshots__/component.spec.js.snap, src/components/general-widgets/OwnerLogin/component.js, src/components/general-widgets/OwnerLogin/component.spec.js, src/components/general-widgets/OwnerLogin/utils/__snapshots__/getForgotPasswordFormMarkup.spec.js.snap, src/components/general-widgets/OwnerLogin/utils/getForgotPasswordFormMarkup.js, src/components/general-widgets/OwnerLogin/utils/getForgotPasswordFormMarkup.spec.js, src/components/general-widgets/OwnerSignUp/Readme.md, src/components/general-widgets/OwnerSignUp/__snapshots__/component.spec.js.snap, src/components/general-widgets/OwnerSignUp/component.js, src/components/general-widgets/OwnerSignUp/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1377)
Applies the success message and error message props to the form based components
- The bundle size limit has been increased to allow for the changes.
- Refactored a few specs to use snapshot testing.
---
<h3 align="center">Preview of success state and the error state</h3>
__CallMeBack__
__Contact__
__OwnerLogin__
__OwnerLogin with forgot password__
__OwnerSignup__
---
<h3 align="center">Bundle size impact</h3>
```
Package size: 255.98 KB
Size limit:   256 KB
With all dependencies, minified and gzipped
```
```
Package size: 256.43 KB
Size limit:   257 KB
With all dependencies, minified and gzipped
```
=> TE-1377: Add success and error state to the forms

src/styles/semantic/themes/livingstone/elements/input.overrides, src/styles/semantic/themes/livingstone/elements/input.variables, src/styles/semantic/themes/livingstone/modules/dropdown.overrides, src/styles/semantic/themes/livingstone/modules/dropdown.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1379)
Implements the missing styles for the dropdowns. It's meant to fix `text ellipsis` and `width` issues
=> TE-1379 Implement styles to handle dropdown ellipsis

src/components/inputs/Dropdown/component.js, src/components/inputs/Dropdown/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1421)
If the value 0 is set in the Dropdown, the field will be populated
=> TE-1421: The value 0 will set the dropdown as populated

package.json, src/components/property-page-widgets/Availability/Readme.md, src/components/property-page-widgets/Availability/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Availability/component.js, src/components/property-page-widgets/Availability/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1409)
Hides the dropdown when there are no roomTypes passed to component
- Adds a variation example
- Adds unit testing
=> TE-1409 Availability hide dropdown when 0 roomTypes

src/components/property-page-widgets/Availability/component.js, src/components/property-page-widgets/Availability/utils/__snapshots__/isDayBlockedOrBeforeCurrentDate.spec.js.snap, src/components/property-page-widgets/Availability/utils/isDayBlockedOrBeforeCurrentDate.js, src/components/property-page-widgets/Availability/utils/isDayBlockedOrBeforeCurrentDate.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1423)
Greys out the dates that are in the past.
=> TE-1423 block dates that are in the past

src/components/collections/Header/component.js, src/components/collections/Header/utils/__snapshots__/getMobileMenuMarkup.spec.js.snap, src/components/collections/Header/utils/getMobileMenuMarkup.js, src/components/collections/Header/utils/getMobileMenuMarkup.spec.js, src/components/collections/Hero/__snapshots__/component.spec.js.snap, src/components/collections/Hero/component.js, src/components/collections/Hero/component.spec.js, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/component.js, src/components/general-widgets/HomepageHero/component.spec.js, src/components/general-widgets/SearchBar/component.js, src/components/general-widgets/SearchBar/component.spec.js, src/components/property-page-widgets/PropertyPageHero/component.js, src/components/property-page-widgets/PropertyPageHero/component.spec.js, src/components/property-page-widgets/PropertyPageSearchBar/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageSearchBar/component.js, src/components/property-page-widgets/PropertyPageSearchBar/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1442)
Implements a new prop in the `SearchForm` to trigger on input field change.
This update is related to the implementation of the availability endpoint in the `SearchForm`. When an input field updates in the form, we want the availability shown to the user in the date picker to update.
- Updated any component consuming the `SearchForm` to expose the input change prop
=> TE-1442: Add function to trigger on input field change in SearchForm

src/components/elements/GoogleMap/component.js, src/components/property-page-widgets/Location/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Location/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1477)
Exposes `GoogleMap.props.apiKey` and provides graceful default key.
=> TE-1477 Fix `GoogleMap` API key

src/components/property-page-widgets/PropertyPageSearchBar/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageSearchBar/component.js, src/components/property-page-widgets/PropertyPageSearchBar/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1506)
PropertyPageSearchBar exposes getIsDayBlocked and onSubmit props.
=> TE-1506 PropertyPageSearchBar exposes additional props

src/components/property-page-widgets/Reviews/Readme.md, src/components/property-page-widgets/Reviews/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Reviews/component.js, src/components/property-page-widgets/Reviews/mock-data/options.js, src/components/property-page-widgets/Reviews/utils/__snapshots__/getModalFormMarkup.spec.js.snap, src/components/property-page-widgets/Reviews/utils/getModalFormMarkup.js, src/components/property-page-widgets/Reviews/utils/getModalFormMarkup.spec.js, src/utils/default-strings/constants.js
Corrects references to `apartment*` and `property*` to `roomType*` in the `Reviews component.
=> TE-1540 Reviews: correct references to `roomType`

src/components/property-page-widgets/Reviews/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1546)
Implements the remaining `props.validation` entries for the `Reviews` component
=> TE-1546 Add all field names to documentation for `props.validation`

src/components/property-page-widgets/PropertyPageSearchBar/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1563)
Modal on submit has the same action as the search bar's on submit.
=> TE-1563 Property page search bar on submit fix

src/styles/semantic/themes/default/third-party-components/react-dates-datepicker.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1620)
`DateRangePicker`: Allow for valid icon in input width calculation
=> TE-1620 `DateRangePicker`: Allow for valid icon in input width calculation

src/components/property-page-widgets/PolicyAndNotes/Readme.md, src/components/property-page-widgets/PolicyAndNotes/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PolicyAndNotes/component.js, src/components/property-page-widgets/PolicyAndNotes/component.spec.js, src/components/property-page-widgets/PolicyAndNotes/utils/__snapshots__/getRuleMarkup.spec.js.snap, src/components/property-page-widgets/PolicyAndNotes/utils/getRuleMarkup.js, src/components/property-page-widgets/PolicyAndNotes/utils/getRuleMarkup.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1650)
`PolicyAndNotes` accepts a list of rules for `Payment schedule`, `Damage deposit` and `Cancellation policy`.
=> TE-1650 PolicyAndNotes accepts array

src/styles/semantic/themes/livingstone/modules/dropdown.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1661)
Aligns the input label to the left.
=> TE-1661 Fix the position of labels for inputs

.travis.yml, Readme.md, docs/CONTRIBUTING.md, docs/CONVENTIONS.md, src/components/collections/Footer/component.js, src/components/elements/Button/component.js, src/components/elements/Icon/component.js, src/components/elements/IconCard/component.js, src/components/property-page-widgets/Amenities/component.js, src/components/property-page-widgets/Description/component.js, src/components/property-page-widgets/KeyFacts/component.js, src/components/property-page-widgets/Location/component.js, src/components/property-page-widgets/RoomType/component.js, src/components/property-page-widgets/SleepingArrangements/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1694)
Keeps branch naming consistent across projects.
=> TE-1694 Kill production

src/components/property-page-widgets/PropertyPageSearchBar/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1684)
PropertyPageSearchBar has a component description that displays in the docs.
=> TE-1684 PropertyPageSearchBar Description

src/components/collections/Header/component.js, src/components/general-widgets/CallMeBack/component.js, src/components/general-widgets/Contact/component.js, src/components/general-widgets/HomepageHero/component.js, src/components/general-widgets/SearchBar/component.js, src/components/property-page-widgets/PropertyPageHero/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1687)
Adds `indent` to location dropdowns.
=> TE-1687 Location props include indentation

src/components/property-page-widgets/PropertyPageHero/Readme.md, src/components/property-page-widgets/PropertyPageHero/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageHero/component.js, src/components/property-page-widgets/PropertyPageHero/component.spec.js, src/components/property-page-widgets/PropertyPageHero/mock-data/mock-data.js, src/components/property-page-widgets/PropertyPageHero/utils/__snapshots__/getGalleryMarkup.spec.js.snap, src/components/property-page-widgets/PropertyPageHero/utils/getGalleryMarkup.js, src/components/property-page-widgets/PropertyPageHero/utils/getGalleryMarkup.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1647)
Hides the `PropertyPageHero` gallery when there are fewer than two images
=> TE-1647 Hide gallery with less than two images

src/styles/semantic/themes/livingstone/collections/menu.overrides, src/styles/semantic/themes/livingstone/modules/dropdown.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1676)
Fixes the a mistake introduced in #494 where only the first hovered item gets the theme color
=> TE-1676 Fix header dropdown items hover

src/components/property-page-widgets/Availability/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Availability/component.js, src/components/property-page-widgets/Availability/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1713)
Changes the default value for `props.roomOptionsWithImages` to `null` and refactors the check for showing the dropdown.
=> TE-1713 Availability: change default prop value and check on props.roomOptionsWithImages

src/components/media/Thumbnail/Readme.md, src/components/media/Thumbnail/__snapshots__/component.spec.js.snap, src/components/media/Thumbnail/component.js, src/components/property-page-widgets/HostProfile/Readme.md, src/components/property-page-widgets/HostProfile/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/HostProfile/component.js, src/components/property-page-widgets/Pictures/__snapshots__/component.spec.js.snap, src/styles/semantic/themes/livingstone/elements/image.overrides, src/styles/semantic/themes/livingstone/globals/site.overrides, src/styles/semantic/themes/livingstone/globals/site.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1702)
Fixes `Thumbnail` so that:
- the image fills the thumbnail (provided that the image passed has sufficient width)
- the image is centered in the thumbnail
I changed `HostProfile` to consume `Thumbnail` as it was distorting the avatar image.
=> TE-1702 Fix `Thumbnail`

src/components/elements/BlockPlaceholder/Readme.md, src/components/elements/BlockPlaceholder/__snapshots__/component.spec.js.snap, src/components/elements/BlockPlaceholder/component.js, src/components/elements/BlockPlaceholder/component.spec.js, src/components/elements/BlockPlaceholder/index.js, src/components/elements/TextPlaceholder/Readme.md, src/components/elements/TextPlaceholder/__snapshots__/component.spec.js.snap, src/components/elements/TextPlaceholder/component.js, src/components/elements/TextPlaceholder/component.spec.js, src/components/elements/TextPlaceholder/index.js, src/index.js, src/styles/semantic/themes/livingstone/globals/site.overrides, src/styles/semantic/themes/livingstone/globals/site.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1737)
Exposes Text and Block placeholders
=> TE-1737 Expose block and text placeholders

src/styles/semantic/themes/livingstone/collections/menu.overrides, src/styles/semantic/themes/livingstone/modules/dropdown.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1801)
Dropdown: apply theme colors to all items in all states
=> TE-1801 Dropdown: apply theme colors to all items in all states

src/components/inputs/Dropdown/component.js, src/components/inputs/Dropdown/component.spec.js, src/components/inputs/Dropdown/utils/getIsOpenAfterChange.js, src/components/inputs/Dropdown/utils/getIsOpenAfterChange.spec.js, src/styles/semantic/themes/livingstone/modules/dropdown.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1781)
`Dropdown` enable arrow key navigation of options
=> TE-1781 Dropdown: enable arrow key navigation of options

src/components/collections/Footer/Readme.md, src/components/collections/Footer/__snapshots__/component.spec.js.snap, src/components/collections/Footer/component.js, src/components/collections/Footer/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1818)
Removes the language and currency `Submenu` from the `Footer` when `languageOptions` and `currencyOptions` aren't passed; then, updates the mentioned cases in the docs.
=> TE-1818 Footer can accept no props.languageOptions and props.currencyOptions

src/components/general-widgets/FeaturedRoomType/Readme.md, src/components/general-widgets/FeaturedRoomType/__snapshots__/component.spec.js.snap, src/components/general-widgets/FeaturedRoomType/component.js, src/components/general-widgets/FeaturedRoomType/component.spec.js, src/components/general-widgets/FeaturedRoomTypes/Readme.md, src/components/general-widgets/FeaturedRoomTypes/__snapshots__/component.spec.js.snap, src/components/general-widgets/FeaturedRoomTypes/component.js, src/components/general-widgets/FeaturedRoomTypes/component.spec.js, src/components/general-widgets/FeaturedRoomTypes/constants.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1753)
FeaturedRoomTypes and FeaturedRoomType can display as its placeholder.
=> TE-1753 FeaturedRoomTypes placeholders

src/components/general-widgets/Review/Readme.md, src/components/general-widgets/Review/__snapshots__/component.spec.js.snap, src/components/general-widgets/Review/component.js, src/components/general-widgets/Review/component.spec.js, src/components/property-page-widgets/Reviews/Readme.md, src/components/property-page-widgets/Reviews/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Reviews/component.js, src/components/property-page-widgets/Reviews/component.spec.js, src/components/property-page-widgets/Reviews/constants.js, src/components/property-page-widgets/Reviews/utils/__snapshots__/getModalFormMarkup.spec.js.snap, src/components/property-page-widgets/Reviews/utils/getModalFormMarkup.js, src/components/property-page-widgets/Reviews/utils/getModalFormMarkup.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1728)
Adds placeholders to `Reviews`
=> TE-1728 Add placeholders to `Reviews`

src/components/collections/Form/__snapshots__/component.spec.js.snap, src/components/collections/Form/component.js, src/components/collections/Form/component.spec.js, src/components/property-page-widgets/Reviews/utils/__snapshots__/getModalFormMarkup.spec.js.snap
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1860)
The `Form` submit button uses default text if it's passed an empty string.
- Updates spec to use snapshots for unit testing the rendered structure
=> TE-1860 Submit button regression

src/components/general-widgets/Promotion/__snapshots__/component.spec.js.snap, src/components/general-widgets/Promotion/component.js, src/components/general-widgets/Promotion/component.spec.js
**Desktop**
**Mobile**
**Desktop**
**Mobile**
**Desktop**
**Mobile**
=> Te 1861 promotion fixes

src/index.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1872)
Exposes `CookieAlert` to package API
=> TE-1872 Expose `CookieAlert` to package API

src/components/inputs/Dropdown/utils/isValueValid.js, src/components/property-page-widgets/Rates/component.js, src/components/property-page-widgets/Rates/utils/__snapshots__/getRoomTypeDropdownMarkup.spec.js.snap, src/components/property-page-widgets/Rates/utils/getRoomTypeDropdownMarkup.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1830)
`Rates`: pass props.value not props.currentValue
=> TE-1830 `Rates`: pass props.value not props.currentValue

src/components/general-widgets/Contact/__snapshots__/component.spec.js.snap, src/components/general-widgets/Contact/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1880)
DateRangePicker is on its own row and email and guests inputs are on the same row.
=> TE-1880 Contact DateRangePicker

src/components/collections/Header/utils/__snapshots__/getHiddenMenuMarkup.spec.js.snap, src/components/collections/Header/utils/getHiddenMenuMarkup.js, src/components/collections/Header/utils/getHiddenMenuMarkup.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1931)
Implements a `Button` in the collapsed header navbar.
=> TE-1931 Show the Book Now button in the collapsed header navbar for single property websites

src/styles/semantic/themes/livingstone/collections/menu.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1954)
Header: apply opacity transition to child menu not header
=> TE-1954 Header: apply opacity transition to child menu not header

src/components/general-widgets/FeaturedProperties/__snapshots__/component.spec.js.snap, src/components/general-widgets/FeaturedProperties/component.js, src/components/general-widgets/FeaturedProperty/__snapshots__/component.spec.js.snap, src/components/general-widgets/FeaturedProperty/component.js, src/components/general-widgets/FeaturedRoomType/__snapshots__/component.spec.js.snap, src/components/general-widgets/FeaturedRoomType/component.js, src/components/general-widgets/FeaturedRoomTypes/__snapshots__/component.spec.js.snap, src/components/general-widgets/FeaturedRoomTypes/component.js, src/styles/semantic/themes/livingstone/views/card.overrides, src/styles/semantic/themes/livingstone/views/card.variables, src/utils/get-card-placeholder-markup/__snapshots__/getCardPlaceholderMarkup.spec.js.snap, src/utils/get-card-placeholder-markup/getCardPlaceholderMarkup.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1611)
For `Featured*` components...
- adds ellipsis for overflowing text
- removes grid and handles responsive behaviour with width styling
=> TE-1611 Fix `Featured*s` responsive behaviour

src/components/property-page-widgets/PropertyPageSearchBar/Readme.md, src/components/property-page-widgets/PropertyPageSearchBar/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageSearchBar/component.js, src/components/property-page-widgets/PropertyPageSearchBar/component.spec.js, src/components/property-page-widgets/PropertyPageSearchBar/utils/__snapshots__/getSummaryMarkup.spec.js.snap, src/components/property-page-widgets/PropertyPageSearchBar/utils/getSummaryMarkup.js, src/components/property-page-widgets/Summary/Readme.md, src/components/property-page-widgets/Summary/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Summary/component.js, src/components/property-page-widgets/Summary/utils/__snapshots__/getNightPriceAndRatingMarkup.spec.js.snap, src/components/property-page-widgets/Summary/utils/__snapshots__/getNightPriceRatingAndLocationMarkup.spec.js.snap, src/components/property-page-widgets/Summary/utils/getNightPriceAndRatingMarkup.js, src/components/property-page-widgets/Summary/utils/getNightPriceAndRatingMarkup.spec.js, src/components/property-page-widgets/Summary/utils/getNightPriceRatingAndLocationMarkup.js, src/components/property-page-widgets/Summary/utils/getNightPriceRatingAndLocationMarkup.spec.js, src/styles/semantic/themes/livingstone/elements/segment.overrides, src/styles/semantic/themes/livingstone/elements/segment.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1957)
PropertyPageSearchBar exposes `isShowingPlaceholder` to control it's placeholder state.
=> TE-1957 PropertyPageSearchBar placeholders

src/components/general-widgets/CallMeBack/__snapshots__/component.spec.js.snap, src/components/general-widgets/Contact/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/OwnerLogin/__snapshots__/component.spec.js.snap, src/components/general-widgets/OwnerSignUp/__snapshots__/component.spec.js.snap, src/components/general-widgets/SearchBar/__snapshots__/component.spec.js.snap, src/components/inputs/CaptchaInput/__snapshots__/component.spec.js.snap, src/components/inputs/DateRangePicker/__snapshots__/component.spec.js.snap, src/components/inputs/InputController/component.js, src/components/inputs/NumberInput/__snapshots__/component.spec.js.snap, src/components/inputs/PhoneInput/__snapshots__/component.spec.js.snap, src/components/inputs/RatingInput/__snapshots__/component.spec.js.snap, src/components/inputs/SingleDatePicker/__snapshots__/component.spec.js.snap, src/components/inputs/TextArea/__snapshots__/component.spec.js.snap, src/components/inputs/TextInput/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageSearchBar/__snapshots__/component.spec.js.snap, src/styles/semantic/definitions/third-party-components/react-image-gallery.less, src/styles/semantic/themes/default/third-party-components/react-dates-datepicker.variables, src/styles/semantic/themes/default/third-party-components/react-image-gallery.variables, src/styles/semantic/themes/livingstone/collections/form.variables, src/styles/semantic/themes/livingstone/elements/input.overrides, src/styles/semantic/themes/livingstone/elements/input.variables, src/styles/semantic/themes/livingstone/elements/segment.overrides, src/styles/semantic/themes/livingstone/elements/segment.variables, src/styles/semantic/themes/livingstone/globals/site.variables, src/styles/semantic/themes/livingstone/modules/dropdown.overrides, src/styles/semantic/themes/livingstone/modules/dropdown.variables, src/styles/semantic/themes/livingstone/modules/modal.overrides, src/styles/semantic/themes/livingstone/modules/modal.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1966)
Creates a global z-index map and consumes the map in relevant components.
=> TE-1966 Fix z indices

src/styles/semantic/themes/livingstone/modules/rating.overrides, src/styles/semantic/themes/livingstone/modules/rating.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1943)
Removes obsolete styles for rating input
=> TE-1943 Remove obsolete styles for rating inputs

src/components/collections/Footer/Readme.md, src/components/collections/Footer/__snapshots__/component.spec.js.snap, src/components/collections/Footer/component.js, src/components/collections/Footer/component.spec.js, src/styles/semantic/themes/livingstone/modules/dropdown.overrides, src/styles/semantic/themes/livingstone/modules/dropdown.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1982)
[Related YouTrack issue](https://youtrack.lodgify.net/agiles/86-18/87-1073?issue=TE-1980)
- Hide the navigation container if there are no navigation items.
- Aligns the searchable dropdown in the footer
=> TE-1982 Footer hide container

src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/component.js, src/components/general-widgets/SearchBar/Readme.md, src/components/general-widgets/SearchBar/__snapshots__/component.spec.js.snap, src/components/general-widgets/SearchBar/component.js, src/components/general-widgets/SearchBar/component.spec.js, src/components/general-widgets/SearchBar/utils/getFormFieldMarkup.js, src/components/general-widgets/SearchBar/utils/getInitialValue.js, src/components/general-widgets/SearchBar/utils/getInitialValue.spec.js, src/components/property-page-widgets/PropertyPageSearchBar/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageSearchBar/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2085)
Makes `SearchBar` controllable
=> TE-2085 Controllable `SearchBar`

src/styles/semantic/themes/livingstone/collections/menu.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2047)
Implements overflow for menu dropdowns.
=> fix(menu.overrides): 

src/components/collections/Form/__snapshots__/component.spec.js.snap, src/components/collections/Form/component.js, src/components/collections/Header/utils/__snapshots__/getHiddenMenuMarkup.spec.js.snap, src/components/collections/Header/utils/__snapshots__/getStandardMenuMarkup.spec.js.snap, src/components/collections/Hero/__snapshots__/component.spec.js.snap, src/components/elements/Button/component.js, src/components/elements/Button/component.spec.js, src/components/elements/Link/component.js, src/components/elements/Link/component.spec.js, src/components/general-widgets/CallMeBack/__snapshots__/component.spec.js.snap, src/components/general-widgets/Contact/__snapshots__/component.spec.js.snap, src/components/general-widgets/CookieAlert/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/OwnerLogin/__snapshots__/component.spec.js.snap, src/components/general-widgets/OwnerSignUp/__snapshots__/component.spec.js.snap, src/components/general-widgets/Promotion/__snapshots__/component.spec.js.snap, src/components/general-widgets/SearchBar/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Pictures/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PolicyAndNotes/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageHero/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageHero/utils/__snapshots__/getGalleryMarkup.spec.js.snap, src/components/property-page-widgets/PropertyPageSearchBar/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Reviews/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Reviews/utils/__snapshots__/getModalFormMarkup.spec.js.snap, src/components/property-page-widgets/RoomType/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/RoomType/utils/__snapshots__/getModalContentMarkup.spec.js.snap, src/components/property-page-widgets/RoomType/utils/getModalContentMarkup.spec.js, src/components/property-page-widgets/RoomTypes/__snapshots__/component.spec.js.snap
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2064)
Stops forms submitting when the action link is clicked.
=> TE-2064 Form: stop bad submission

src/components/elements/Button/component.spec.js, src/components/general-widgets/SearchBar/__snapshots__/component.spec.js.snap, src/components/general-widgets/SearchBar/component.js, src/components/property-page-widgets/PropertyPageSearchBar/component.js, src/styles/semantic/themes/livingstone/elements/button.overrides
`Link`: stop browser native styles pollution. I broke this one PR ago 🙈
=> TE-2064 Link: stop browser native styles pollution

docs/CONTRIBUTING.md
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2014)
Adds a section on creating commits in the project.
=> TE-2014 Commit conventions

src/components/general-widgets/CallMeBack/__snapshots__/component.spec.js.snap, src/components/general-widgets/Contact/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/OwnerLogin/__snapshots__/component.spec.js.snap, src/components/general-widgets/OwnerSignUp/__snapshots__/component.spec.js.snap, src/components/general-widgets/SearchBar/__snapshots__/component.spec.js.snap, src/components/inputs/Checkbox/Readme.md, src/components/inputs/Checkbox/__snapshots__/component.spec.js.snap, src/components/inputs/Checkbox/component.js, src/components/inputs/Checkbox/component.spec.js, src/components/inputs/Checkbox/utils/adaptOnChangeEvent.js, src/components/inputs/Checkbox/utils/adaptOnChangeEvent.spec.js, src/components/inputs/Checkbox/utils/mapValueToProps.js, src/components/inputs/Checkbox/utils/mapValueToProps.spec.js, src/components/inputs/DateRangePicker/__snapshots__/component.spec.js.snap, src/components/inputs/InputController/component.js, src/components/inputs/NumberInput/__snapshots__/component.spec.js.snap, src/components/inputs/PhoneInput/__snapshots__/component.spec.js.snap, src/components/inputs/RatingInput/__snapshots__/component.spec.js.snap, src/components/inputs/SingleDatePicker/__snapshots__/component.spec.js.snap, src/components/inputs/TextArea/__snapshots__/component.spec.js.snap, src/components/inputs/TextInput/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageSearchBar/__snapshots__/component.spec.js.snap, src/styles/semantic/themes/livingstone/elements/input.overrides, src/styles/semantic/themes/livingstone/modules/checkbox.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2162)
`<Checkbox />` component has an error state.
=> TE-2162 Checkbox error state

src/components/property-page-widgets/Availability/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1953)
The dropdown can be controlled by the value of `roomOptionsValue` prop.
=> TE-1953 Availability control room options value

src/components/collections/Footer/Readme.md, src/components/collections/Footer/__snapshots__/component.spec.js.snap, src/components/collections/Footer/component.js, src/components/collections/Footer/component.spec.js, src/components/collections/Footer/utils/getHrefFaxString.js, src/components/collections/Footer/utils/getHrefFaxString.spec.js, src/components/collections/Footer/utils/getHrefMailToString.js, src/components/collections/Footer/utils/getHrefMailToString.spec.js, src/styles/semantic/themes/livingstone/collections/menu.overrides, src/styles/semantic/themes/livingstone/collections/menu.variables, src/styles/semantic/themes/livingstone/elements/input.overrides, src/styles/semantic/themes/livingstone/globals/site.variables, src/utils/default-strings/constants.js, styleguide/config/options/styles.js, styleguide/config/options/theme.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2131)
Email and Fax can be displayed in the footer.
Header button is aligned to burger menu.
Style guide code editor font is monotype.
=> TE-2131 Footer accept fax contact

src/components/property-page-widgets/Description/Readme.md, src/components/property-page-widgets/Description/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Description/component.js, src/components/property-page-widgets/Description/utils/__snapshots__/getDescriptionWithExtraDescription.spec.js.snap, src/components/property-page-widgets/Description/utils/__snapshots__/getDescriptionWithHTMLExtraDescription.spec.js.snap, src/components/property-page-widgets/Description/utils/__snapshots__/getExtraDescriptionModal.spec.js.snap, src/components/property-page-widgets/Description/utils/__snapshots__/getHTMLDescriptionWithExtraDescription.spec.js.snap, src/components/property-page-widgets/Description/utils/__snapshots__/getHTMLDescriptionWithHTMLExtraDescription.spec.js.snap, src/components/property-page-widgets/Description/utils/formatParagraphWithModal.spec.js, src/components/property-page-widgets/Description/utils/getDescriptionWithExtraDescription.js, src/components/property-page-widgets/Description/utils/getDescriptionWithExtraDescription.spec.js, src/components/property-page-widgets/Description/utils/getDescriptionWithHTMLExtraDescription.js, src/components/property-page-widgets/Description/utils/getDescriptionWithHTMLExtraDescription.spec.js, src/components/property-page-widgets/Description/utils/getDescriptions.js, src/components/property-page-widgets/Description/utils/getDescriptions.spec.js, src/components/property-page-widgets/Description/utils/getExtraDescriptionModal.js, src/components/property-page-widgets/Description/utils/getExtraDescriptionModal.spec.js, src/components/property-page-widgets/Description/utils/getHTMLDescriptionWithExtraDescription.js, src/components/property-page-widgets/Description/utils/getHTMLDescriptionWithExtraDescription.spec.js, src/components/property-page-widgets/Description/utils/getHTMLDescriptionWithHTMLExtraDescription.js, src/components/property-page-widgets/Description/utils/getHTMLDescriptionWithHTMLExtraDescription.spec.js, src/components/property-page-widgets/HostProfile/component.js, src/components/property-page-widgets/HostProfile/utils/__snapshots__/getDescription.spec.js.snap, src/components/property-page-widgets/HostProfile/utils/getDescription.js, src/components/property-page-widgets/HostProfile/utils/getDescription.spec.js, src/components/property-page-widgets/Location/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Location/component.js, src/components/property-page-widgets/Location/component.spec.js, src/styles/semantic/themes/livingstone/globals/site.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2137)
Location, Description and HostProfile accept HTML
=> TE-2137 Location, Description and HostProfile accept html

src/components/collections/Footer/__snapshots__/component.spec.js.snap, src/components/collections/Footer/component.js, src/components/general-widgets/CallMeBack/__snapshots__/component.spec.js.snap, src/components/general-widgets/Contact/__snapshots__/component.spec.js.snap, src/components/general-widgets/EmailCapture/Readme.md, src/components/general-widgets/EmailCapture/__snapshots__/component.spec.js.snap, src/components/general-widgets/EmailCapture/component.js, src/components/general-widgets/EmailCapture/component.spec.js, src/components/general-widgets/EmailCapture/index.js, src/components/general-widgets/EmailCapture/utils/__snapshots__/getPrivacyCheckboxMarkup.spec.js.snap, src/components/general-widgets/EmailCapture/utils/getPrivacyCheckboxMarkup.js, src/components/general-widgets/EmailCapture/utils/getPrivacyCheckboxMarkup.spec.js, src/components/general-widgets/OwnerSignUp/__snapshots__/component.spec.js.snap, src/components/inputs/Checkbox/__snapshots__/component.spec.js.snap, src/components/inputs/Checkbox/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2195)
Footer has an optional privacy checkbox.
=> TE-2195 Newsletter privacy consent

package.json, src/components/general-widgets/HTML/Readme.md, src/components/general-widgets/HTML/component.js, src/components/general-widgets/HTML/component.spec.js, src/components/media/Video/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2213)
Lodgify-ui no longer sanitises html strings.
=> TE-2213 Remove dompurify

src/components/collections/Hero/__snapshots__/component.spec.js.snap, src/components/collections/Hero/component.spec.js, src/components/general-widgets/HomepageHero/Readme.md, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/component.js, src/components/general-widgets/HomepageHero/component.spec.js, src/components/general-widgets/HomepageHero/mock-data/mock-data.js, src/components/general-widgets/SearchBar/Readme.md, src/components/general-widgets/SearchBar/__snapshots__/component.spec.js.snap, src/components/general-widgets/SearchBar/component.js, src/components/general-widgets/SearchBar/component.spec.js, src/components/general-widgets/SearchBar/mock-data/options.js, src/components/general-widgets/SearchBar/utils/__snapshots__/getFormFieldMarkup.spec.js.snap, src/components/general-widgets/SearchBar/utils/getFormFieldMarkup.js, src/components/general-widgets/SearchBar/utils/getFormFieldMarkup.spec.js, src/components/general-widgets/SearchBar/utils/getWillLocationDropdownOpenAbove.js, src/components/general-widgets/SearchBar/utils/getWillLocationDropdownOpenAbove.spec.js, src/components/property-page-widgets/PropertyPageSearchBar/Readme.md, src/components/property-page-widgets/PropertyPageSearchBar/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageSearchBar/component.js, src/components/property-page-widgets/PropertyPageSearchBar/component.spec.js, src/components/property-page-widgets/PropertyPageSearchBar/mock-data/options.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2273)
The guest options input in the `SearchBar` has been changed to a number input instead of a dropdown.
=> TE-2273 SearchBar guests input

src/components/general-widgets/PropertySearchResultList/Readme.md, src/components/general-widgets/PropertySearchResultList/__snapshots__/component.spec.js.snap, src/components/general-widgets/PropertySearchResultList/component.js, src/components/general-widgets/PropertySearchResultList/component.spec.js, src/styles/semantic/definitions/lodgify-ui-components/flex-container.less
PropertySearchResultList: add dropdown input
I had to add some specifity to existing styles for headings nested in flex containers.
=> TE-2355 PropertySearchResultList: add dropdown input

src/styles/semantic/themes/livingstone/modules/checkbox.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2368)
Stop checkbox from translating when focussed.
=> TE-2368 Checkbox translating bug

src/components/elements/Message/Readme.md, src/components/elements/Message/__snapshots__/component.spec.js.snap, src/components/elements/Message/component.js, src/components/elements/Message/component.spec.js, src/components/elements/Message/index.js, src/components/general-widgets/PropertySearchResultList/Readme.md, src/components/general-widgets/PropertySearchResultList/__snapshots__/component.spec.js.snap, src/components/general-widgets/PropertySearchResultList/component.js, src/components/general-widgets/PropertySearchResultList/component.spec.js, src/styles/semantic/themes/livingstone/collections/message.overrides, src/styles/semantic/themes/livingstone/collections/message.variables
Shows an optional `Message` in `PropertySearchResultList`
=> TE-2379 TE-2380 Show `Message` in `PropertySearchResultList`

src/components/collections/TextInputSegment/Readme.md, src/components/collections/TextInputSegment/__snapshots__/component.spec.js.snap, src/components/collections/TextInputSegment/component.js, src/components/collections/TextInputSegment/component.spec.js, src/components/collections/TextInputSegment/index.js, src/index.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2369)
Expose TextInputSegment to library api.
=> TE-2369 TextInputSegment

src/components/collections/Footer/__snapshots__/component.spec.js.snap, src/components/collections/TextInputSegment/__snapshots__/component.spec.js.snap, src/components/collections/ToggleInputSegment/Readme.md, src/components/collections/ToggleInputSegment/__snapshots__/component.spec.js.snap, src/components/collections/ToggleInputSegment/component.js, src/components/collections/ToggleInputSegment/component.spec.js, src/components/collections/ToggleInputSegment/index.js, src/components/general-widgets/CallMeBack/__snapshots__/component.spec.js.snap, src/components/general-widgets/Contact/__snapshots__/component.spec.js.snap, src/components/general-widgets/EmailCapture/__snapshots__/component.spec.js.snap, src/components/general-widgets/EmailCapture/utils/__snapshots__/getPrivacyCheckboxMarkup.spec.js.snap, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/OwnerLogin/__snapshots__/component.spec.js.snap, src/components/general-widgets/OwnerSignUp/__snapshots__/component.spec.js.snap, src/components/general-widgets/SearchBar/__snapshots__/component.spec.js.snap, src/components/inputs/Checkbox/__snapshots__/component.spec.js.snap, src/components/inputs/Checkbox/component.js, src/components/inputs/DateRangePicker/__snapshots__/component.spec.js.snap, src/components/inputs/InputController/component.js, src/components/inputs/NumberInput/__snapshots__/component.spec.js.snap, src/components/inputs/PhoneInput/__snapshots__/component.spec.js.snap, src/components/inputs/RatingInput/__snapshots__/component.spec.js.snap, src/components/inputs/SingleDatePicker/__snapshots__/component.spec.js.snap, src/components/inputs/TextArea/__snapshots__/component.spec.js.snap, src/components/inputs/TextInput/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageSearchBar/__snapshots__/component.spec.js.snap, src/index.js, src/styles/semantic/themes/livingstone/elements/input.overrides, src/styles/semantic/themes/livingstone/elements/segment.overrides, src/styles/semantic/themes/livingstone/modules/checkbox.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2369)
Exposes ToggleInputSegment to the library api.
=> TE-2369 ToggleInputSegment

src/components/general-widgets/PropertySearchResultList/__snapshots__/component.spec.js.snap, src/components/general-widgets/PropertySearchResultList/component.js, src/components/general-widgets/PropertySearchResultList/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2352)
Fixes a little bug where updated search results were not being picked up in the list.
=> TE-2352 fix(PropertyPageSearchResultList): respect updates to search results

src/components/general-widgets/EmailCapture/__snapshots__/component.spec.js.snap, src/components/general-widgets/EmailCapture/component.js, src/components/general-widgets/EmailCapture/utils/constants.js, src/components/general-widgets/EmailCapture/utils/getTextAlign.js, src/components/general-widgets/EmailCapture/utils/getTextAlign.spec.js, src/styles/semantic/themes/livingstone/elements/input.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2445)
Success and Error messages show above the email input.
The privacy policy button is aligned with the text
=> TE-2445 EmailCapture messaging

src/components/collections/CounterInputSegment/Readme.md, src/components/collections/CounterInputSegment/__snapshots__/component.spec.js.snap, src/components/collections/CounterInputSegment/component.js, src/components/collections/CounterInputSegment/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2372)
Expose `labelText` to component api.
=> TE-2372 Counter label

src/components/elements/Marker/Readme.md, src/components/elements/Marker/__snapshots__/component.spec.js.snap, src/components/elements/Marker/component.js, src/components/elements/Marker/component.spec.js, src/components/elements/Marker/index.js, src/components/elements/Marker/utils/getToggledState.js, src/components/elements/Marker/utils/getToggledState.spec.js, src/index.js, src/styles/semantic/definitions/lodgify-ui-components/marker.less, src/styles/semantic/lodgify-ui.less, src/styles/semantic/marker.less, src/styles/semantic/theme.config, src/styles/semantic/themes/default/lodgify-ui-components/marker.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2420)
Creates a new `Marker` component
=> TE-2420 marker component

src/components/layout/FixedContainer/Readme.md, src/components/layout/FixedContainer/component.js, src/components/layout/FixedContainer/component.spec.js, src/components/layout/FixedContainer/index.js, src/index.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2426)
FixedContainer: create component with tests and examples
=> TE-2426 FixedContainer: create component with tests and examples

src/components/general-widgets/PropertySearchResult/__snapshots__/component.spec.js.snap, src/components/general-widgets/PropertySearchResult/component.js, src/components/general-widgets/PropertySearchResult/component.spec.js, src/components/general-widgets/PropertySearchResult/utils/getPropertyTypeWithDot.js, src/components/general-widgets/PropertySearchResult/utils/getPropertyTypeWithDot.spec.js, src/styles/semantic/themes/livingstone/views/card.overrides, src/utils/react-google-maps/utils/getReactGoogleMapsRequiredProps.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2510)
Hides stars and the rating if the property has no reviews
=> TE-2510 Hide stars and the rating if the property has no reviews

src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/component.js, src/components/general-widgets/SearchBar/Readme.md, src/components/general-widgets/SearchBar/__snapshots__/component.spec.js.snap, src/components/general-widgets/SearchBar/component.js, src/components/general-widgets/SearchBar/utils/__snapshots__/getFormFieldMarkup.spec.js.snap, src/components/general-widgets/SearchBar/utils/getFormFieldMarkup.js, src/components/property-page-widgets/PropertyPageSearchBar/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageSearchBar/component.js, src/styles/semantic/themes/livingstone/collections/form.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2503)
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2466)
- SearchBar exposes translation strings for it's inputs.
- Links within forms take theme action colour instead of link colour.
=> TE-2503 SearchBar strings

src/components/general-widgets/Contact/Readme.md, src/components/general-widgets/Contact/__snapshots__/component.spec.js.snap, src/components/general-widgets/Contact/component.js, src/components/general-widgets/Contact/component.spec.js, src/components/general-widgets/Contact/mock-data/options.js
Removes `Contact.props.roomOptions`
=> feat(Contact): remove roomoptions

src/styles/semantic/themes/livingstone/modules/sidebar.overrides, src/styles/semantic/themes/livingstone/modules/sidebar.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2515)
Increases  the `z-index` on sidebar cross icon by 1.
=> TE-2515 Search App - Sidebar content covers cross

src/components/collections/Header/component.js, src/components/collections/Header/component.spec.js, src/components/collections/Header/constants.js, src/components/collections/Header/utils/getIsMenuHidden.js, src/components/collections/Header/utils/getIsMenuHidden.spec.js, src/components/collections/Header/utils/getLogoWidth.js, src/components/collections/Header/utils/getLogoWidth.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2521)
Allows the hamburger menu to be triggered properly on `Ipad Pro`.
=> TE-2521 Hamburger menu on the header is not being correctly applied

src/components/general-widgets/SearchBar/__snapshots__/component.spec.js.snap, src/components/general-widgets/SearchBar/component.js, src/components/property-page-widgets/PropertyPageSearchBar/__snapshots__/component.spec.js.snap
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2549)
Fixed search bars can now be submitted
⬅️After and Before ➡
=> TE-2549 Search bar submit regression

src/components/elements/Icon/constants.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2418)
Adds `LIST` to the icon names exposed by the library
=> TE-2418 Icon: add LIST to icon names

src/components/inputs/DateRangePicker/utils/getIsVisible.js, src/components/inputs/DateRangePicker/utils/getIsVisible.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2554)
Fixes a mispelling wot I done
=> TE-2554 fix(DateRangePicker): spellcheck ting

src/components/elements/GoogleMap/Readme.md, src/components/elements/GoogleMap/component.js, src/components/elements/PriceLabel/__snapshots__/component.spec.js.snap, src/components/elements/PriceLabel/component.js, src/components/elements/PriceLabel/component.spec.js, src/styles/semantic/themes/livingstone/elements/label.overrides, src/utils/react-google-maps/component.js
GoogleMap: Add offset to map markers
=> TE-2423 GoogleMap: Add offset to map markers

src/components/elements/Pagination/__snapshots__/component.spec.js.snap, src/components/elements/Pagination/component.js, src/components/elements/Pagination/component.spec.js, src/components/general-widgets/PropertySearchResultList/__snapshots__/component.spec.js.snap, src/components/general-widgets/PropertySearchResultList/component.js, src/components/general-widgets/PropertySearchResultList/utils/getActivePage.js, src/components/general-widgets/PropertySearchResultList/utils/getActivePage.spec.js, src/utils/google-map-react/components/GoogleMapReact/component.js, src/utils/google-map-react/components/GoogleMapReact/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2501)
Pagination accepts controlled activePage
I fixed a little bug in `GoogleMap` at the same time.
=> TE-2501 Pagination accepts controlled activePage

src/components/general-widgets/PropertySearchResultList/__snapshots__/component.spec.js.snap, src/components/general-widgets/PropertySearchResultList/component.js, src/components/general-widgets/PropertySearchResultList/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2501)
PropertySearchResultList: make the controlled pagination work
=> TE-2501 PropertySearchResultList: make the controlled pagination work

src/components/elements/GoogleMap/component.js, src/components/elements/Marker/component.js, src/components/elements/PriceLabel/component.js, src/components/general-widgets/Contact/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/PropertySearchResult/component.js, src/components/inputs/DateRangePicker/component.js, src/components/inputs/DateRangePicker/component.spec.js, src/components/property-page-widgets/PropertyPageSearchBar/__snapshots__/component.spec.js.snap, src/styles/semantic/themes/livingstone/elements/label.overrides, src/styles/semantic/themes/livingstone/elements/label.variables, src/utils/google-map-react/components/GoogleMapReact/__snapshots__/component.spec.js.snap, src/utils/google-map-react/components/GoogleMapReact/component.js, src/utils/google-map-react/components/GoogleMapReact/component.spec.js, src/utils/google-map-react/components/GoogleMapReact/utils/adaptENSWtoNESW.js, src/utils/google-map-react/components/GoogleMapReact/utils/getCenterFromBounds.js, src/utils/google-map-react/components/GoogleMapReact/utils/getZoomedState.js, src/utils/google-map-react/components/GoogleMapReact/utils/getZoomedState.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2570)
A handful of small fixes and optimisations
=> TE-2570 Fixes and optimisations

src/styles/semantic/definitions/lodgify-ui-components/property-search-result-list.less
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2570)
- Scrollbar width is none in firefox.
- Dropdown container height is auto in firefox.
=> TE-2570 Search App optimisations

src/components/collections/CheckboxInputSegment/__snapshots__/component.spec.js.snap, src/components/collections/CheckboxInputSegment/component.js, src/components/collections/ToggleInputSegment/__snapshots__/component.spec.js.snap, src/components/collections/ToggleInputSegment/component.js, src/components/collections/ToggleInputSegment/component.spec.js, src/styles/semantic/themes/livingstone/elements/segment.overrides, src/styles/semantic/themes/livingstone/modules/checkbox.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2377)
- `ToggleInputSegment` controls toggle value.
- `CheckboxInputSegment` grid fills it's container.
- `Checkbox` label color is black.
=> TE-2377 Instant booking

src/components/inputs/Dropdown/component.js, src/components/inputs/Dropdown/component.spec.js, src/components/inputs/InputController/component.js, src/components/inputs/InputController/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2603)
Controls dirty state of dropdown and inputs.
=> TE-2603 Input dirty state

src/styles/semantic/themes/livingstone/elements/label.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2611)
`PriceLabel` text contrasts with background color.
=> TE-2611 PriceLabel contrast

src/components/general-widgets/PropertySearchResultList/__snapshots__/component.spec.js.snap, src/components/general-widgets/PropertySearchResultList/component.js, src/components/general-widgets/PropertySearchResultList/utils/getResultsCountText.js, src/components/general-widgets/PropertySearchResultList/utils/getResultsCountText.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2618)
Exposes `renderResultsCountText` prop
=> TE-2618 Property results count

src/components/collections/ToggleInputSegment/component.js, src/components/collections/ToggleInputSegment/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2377)
ToggleInputSegment onClick is passed this.props.name, toggle value and the event.
=> TE-2377 Instant booking filter

src/utils/google-map-react/components/GoogleMapReact/component.js, src/utils/google-map-react/constants/constants.js, src/utils/google-map-react/constants/index.js, src/utils/google-map-react/utils/getMapOptions.js, src/utils/google-map-react/utils/getMapOptions.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2645)
It will set the minZoom for GoogleMap wrapper in order to don't use the default one that is 3.
=> TE-2645 set the minZoom for GoogleMap

.gitignore, src/components/collections/Footer/__snapshots__/component.spec.js.snap, src/components/collections/TextInputSegment/__snapshots__/component.spec.js.snap, src/components/general-widgets/CallMeBack/__snapshots__/component.spec.js.snap, src/components/general-widgets/Contact/__snapshots__/component.spec.js.snap, src/components/general-widgets/EmailCapture/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/OwnerLogin/__snapshots__/component.spec.js.snap, src/components/general-widgets/OwnerSignUp/__snapshots__/component.spec.js.snap, src/components/general-widgets/SearchBar/__snapshots__/component.spec.js.snap, src/components/inputs/Dropdown/Readme.md, src/components/inputs/Dropdown/__snapshots__/component.spec.js.snap, src/components/inputs/Dropdown/component.js, src/components/inputs/Dropdown/component.spec.js, src/components/inputs/InputController/component.js, src/components/inputs/InputController/component.spec.js, src/components/inputs/NumberInput/Readme.md, src/components/inputs/NumberInput/__snapshots__/component.spec.js.snap, src/components/inputs/PhoneInput/Readme.md, src/components/inputs/PhoneInput/utils/CountrySelectComponent/__snapshots__/component.spec.js.snap, src/components/inputs/RatingInput/__snapshots__/component.spec.js.snap, src/components/inputs/TextArea/__snapshots__/component.spec.js.snap, src/components/inputs/TextInput/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageSearchBar/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Rates/__snapshots__/component.spec.js.snap
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2659)
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2667)
It will fix the bahviour of the label of InputContainers and Dropdown when the value is set on mount
|before|after|
|-|-|
|<img width="182" alt="image" src="https://user-images.githubusercontent.com/49396812/65606157-a65c1e00-dfaa-11e9-97e1-2d1c02703d7c.png">|<img width="179" alt="image" src="https://user-images.githubusercontent.com/49396812/65606188-b5db6700-dfaa-11e9-92cf-2e6836d3bf1b.png">|
=> TE-2659 fix input behaviour for initial Value

src/components/inputs/Dropdown/component.js, src/components/inputs/Dropdown/component.spec.js, src/components/inputs/InputController/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2659)
try to fix again the problem due ssr related update issue
=> TE-2659 fix dirty behaviour for SSR

src/utils/google-map-react/constants/constants.js, src/utils/google-map-react/utils/getMapOptions.js, src/utils/google-map-react/utils/getMapOptions.spec.js, styleguide/styleguide-components/LogoRenderer/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2627)
Restrict google map bounds to prevent repeating.
=> TE-2627 Restrict map bounds

src/components/general-widgets/CallMeBack/__snapshots__/component.spec.js.snap, src/components/inputs/PhoneInput/utils/CountrySelectComponent/__snapshots__/component.spec.js.snap, src/components/inputs/PhoneInput/utils/CountrySelectComponent/component.js, src/components/inputs/SingleDatePicker/__snapshots__/component.spec.js.snap, src/components/inputs/SingleDatePicker/component.js, src/styles/semantic/themes/livingstone/elements/input.overrides, src/styles/semantic/themes/livingstone/elements/input.variables, src/styles/semantic/themes/livingstone/modules/checkbox.overrides, src/styles/semantic/themes/livingstone/modules/dropdown.overrides, src/styles/semantic/themes/livingstone/modules/dropdown.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2667)
Remove unused styles after change label in dropdown and InputController
=> TE-2667 Remove unused style

src/utils/google-map-react/constants/constants.js, src/utils/google-map-react/utils/getMapOptions.js, src/utils/google-map-react/utils/getMapOptions.spec.js
This reverts commit 8ca846ae49bc61deeba331540fb7ac4066ee498d.
=> TE-2627 Restrict google maps bounds

.travis.yml, package.json, src/components/collections/RangeInputSegment/__snapshots__/component.spec.js.snap, src/components/elements/GoogleMap/__snapshots__/component.spec.js.snap, src/components/elements/GoogleMap/component.js, src/components/inputs/Range/__snapshots__/component.spec.js.snap, src/components/inputs/Range/component.js, src/components/property-page-widgets/Location/__snapshots__/component.spec.js.snap, src/utils/google-map-react/components/GoogleMapReact/__snapshots__/component.spec.js.snap, src/utils/google-map-react/components/GoogleMapReact/component.js, src/utils/google-map-react/components/GoogleMapReact/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2627)
exposes google api prop.
=> TE-2627 Google map bounds

src/utils/google-map-react/components/GoogleMapReact/__snapshots__/component.spec.js.snap, src/utils/google-map-react/components/GoogleMapReact/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2684)
Set marker width
=> TE-2684 Set marker width

src/styles/semantic/definitions/lodgify-ui-components/search-bar.less, src/styles/semantic/themes/default/lodgify-ui-components/search-bar.variables
Sets a static width for both location and guest inputs.
=> TE-2566 Search box - when I click on location dropdown all inputs are resized

src/components/elements/PriceLabel/Readme.md, src/components/elements/PriceLabel/__snapshots__/component.spec.js.snap, src/components/elements/PriceLabel/component.js, src/components/elements/PriceLabel/component.spec.js, src/styles/semantic/definitions/lodgify-ui-components/search-bar.less, src/styles/semantic/themes/livingstone/elements/label.overrides, src/styles/semantic/themes/livingstone/elements/label.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2722)
Refactors the `PriceLabel` in order to make it more consistent and flexible to translation demands.
* Additionally, justifies the inputs of the search-bar component to the centre.
=> TE-2722 SearchApp - Marker arrow is not aligned

src/components/property-page-widgets/PolicyAndNotes/Readme.md, src/components/property-page-widgets/PolicyAndNotes/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PolicyAndNotes/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2610)
Parse notes with HTML and render that
|before|after|
|-|-|
|![image](https://user-images.githubusercontent.com/5032333/66893921-758e6800-efef-11e9-819f-79c714c8a64c.png)|![image](https://user-images.githubusercontent.com/5032333/66893975-9d7dcb80-efef-11e9-8ad0-75a7c1b54b7d.png)|
=> TE-2610 parse HTML inside policy notes

src/styles/semantic/definitions/third-party-components/react-dates-datepicker.less
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2759)
Date range picker has more space for dates and placeholder text.
=> TE-2759 Date range picker ellipsis

src/components/collections/CheckboxInputSegment/__snapshots__/component.spec.js.snap, src/components/collections/CounterInputSegment/__snapshots__/component.spec.js.snap, src/components/collections/Header/__snapshots__/component.spec.js.snap, src/components/collections/Header/utils/HiddenMenu/__snapshots__/component.spec.js.snap, src/components/collections/Header/utils/__snapshots__/getLogoMarkup.spec.js.snap, src/components/collections/Hero/__snapshots__/component.spec.js.snap, src/components/collections/RangeInputSegment/__snapshots__/component.spec.js.snap, src/components/collections/TextInputSegment/__snapshots__/component.spec.js.snap, src/components/collections/ToggleInputSegment/__snapshots__/component.spec.js.snap, src/components/elements/PriceLabel/__snapshots__/component.spec.js.snap, src/components/elements/SummaryCard/__snapshots__/component.spec.js.snap, src/components/general-widgets/CookieAlert/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/PropertySearchResult/__snapshots__/component.spec.js.snap, src/components/general-widgets/PropertySearchResultList/__snapshots__/component.spec.js.snap, src/components/inputs/Counter/__snapshots__/component.spec.js.snap, src/components/layout/FlexContainer/component.js, src/components/property-page-widgets/HostProfile/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageHero/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageHero/utils/__snapshots__/getGalleryMarkup.spec.js.snap, src/components/property-page-widgets/Rates/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Rates/utils/__snapshots__/getRoomTypeDropdownMarkup.spec.js.snap
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2704)
Exposes `className` for `FlexContainer`.
=> TE-2704 Expose className for FlexContainer

src/components/collections/CounterInputSegment/Readme.md, src/components/collections/CounterInputSegment/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/component.js, src/components/general-widgets/SearchBar/__snapshots__/component.spec.js.snap, src/components/general-widgets/SearchBar/component.js, src/components/general-widgets/SearchBar/components/SearchFields/__snapshots__/component.spec.js.snap, src/components/general-widgets/SearchBar/components/SearchFields/component.js, src/components/inputs/Counter/Readme.md, src/components/inputs/Counter/__snapshots__/component.spec.js.snap, src/components/inputs/Counter/component.js, src/components/inputs/Counter/component.spec.js, src/components/inputs/CounterDropdown/Readme.md, src/components/inputs/CounterDropdown/__snapshots__/component.spec.js.snap, src/components/inputs/CounterDropdown/component.js, src/components/inputs/CounterDropdown/component.spec.js, src/components/property-page-widgets/PropertyPageSearchBar/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageSearchBar/component.js, src/styles/semantic/themes/livingstone/globals/site.variables, src/styles/semantic/themes/livingstone/modules/dropdown.overrides, src/styles/semantic/themes/livingstone/modules/popup.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2743)
Refactor counter dropdown to use popup instead of dropdown to prevent setting state during render (semantic ui react)
=> TE-2743 Search counter dropdown

src/components/general-widgets/SearchBar/__snapshots__/component.spec.js.snap, src/components/inputs/CounterDropdown/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2743)
Add styles for when the input has a dirty value
=> TE-2743 Search counter dirty styles

package.json
=> Remove license

src/components/general-widgets/FeaturedRoomType/utils/getRoomTypeDescription.js, src/components/general-widgets/FeaturedRoomType/utils/getRoomTypeDescription.spec.js, src/styles/semantic/themes/livingstone/views/card.overrides, src/styles/semantic/themes/livingstone/views/card.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2816)
FeaturedRoomTypes without a number of beds don't show the beds label in the description.
=> TE-2816 Featured room type beds count

src/styles/semantic/themes/livingstone/views/card.overrides, src/styles/semantic/themes/livingstone/views/card.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2772)
FeaturedRoomtype and FeaturedProperty cards are aligned when there is no heading.
=> TE-2772 FeaturedProperty alignment

src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/SearchBar/__snapshots__/component.spec.js.snap, src/components/general-widgets/SearchBar/component.js, src/components/general-widgets/SearchBar/components/SearchModal/__snapshots__/component.spec.js.snap, src/components/general-widgets/SearchBar/components/SearchModal/component.js, src/components/general-widgets/SearchBar/components/SearchModal/component.spec.js, src/components/property-page-widgets/PropertyPageSearchBar/__snapshots__/component.spec.js.snap
[Related YouTrack issue](https://youtrack.lodgify.net/issue/WEB-631)
Searchbar as a modal opens as a modal when search is clicked.
=> WEB-631 Search bar on mobile

src/styles/semantic/themes/livingstone/elements/icon.overrides, src/styles/semantic/themes/livingstone/elements/icon.variables, src/styles/semantic/themes/livingstone/elements/list.overrides, src/styles/semantic/themes/livingstone/globals/site.overrides
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-495)
Icons text in RoomType widget is the same as all other paragraphs
=> WEB-495: RoomType icon text size

src/components/general-widgets/HTML/Readme.md, src/styles/semantic/definitions/lodgify-ui-components/html.less, src/styles/semantic/themes/default/lodgify-ui-components/html.variables
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-522)
Show border in the tables when are inserted in the HTML widget
=> WEB-522: Add border style to table in HTML

src/components/collections/Characteristics/Readme.md, src/components/collections/Characteristics/__snapshots__/component.spec.js.snap, src/components/collections/Characteristics/component.js, src/components/collections/Characteristics/component.spec.js, src/components/collections/Characteristics/index.js, src/components/collections/Characteristics/mock-data/props.js, src/components/property-page-widgets/Description/Readme.md, src/components/property-page-widgets/Description/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Description/component.js, src/components/property-page-widgets/Description/component.spec.js, src/components/property-page-widgets/Description/mock-data/props.js, src/index.js
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-651)
=> WEB-651 Hide the main icons guests/bedrooms/bathrooms when property has room types.

src/components/property-page-widgets/Availability/constants.js, src/components/property-page-widgets/Availability/utils/__snapshots__/renderMonthHeader.spec.js.snap, src/components/property-page-widgets/Availability/utils/renderMonthHeader.js
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-473)
The order of the days of the week are based on the locale
=> WEB-473 Availability weekday alignment

src/components/collections/Header/__snapshots__/component.spec.js.snap, src/components/collections/Header/component.js, src/components/collections/Hero/__snapshots__/component.spec.js.snap, src/components/collections/Hero/component.js, src/components/collections/SlideshowHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/component.js, src/components/property-page-widgets/PropertyPageHero/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageHero/component.js
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-710)
expose className for Header and other component that contain Header in order to be allow to override the css
=> WEB-710: expose className for Header and other component that contain Header

src/components/collections/Header/component.js, src/components/collections/Hero/component.js, src/components/general-widgets/HomepageHero/component.js, src/components/media/FullBleed/__snapshots__/component.spec.js.snap, src/components/media/FullBleed/component.js, src/components/property-page-widgets/PropertyPageHero/component.js
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-712)
Add className to props on FullBleed in order to override styles
=> WEB-712: add className as prop on FullBleed

src/components/collections/Hero/__snapshots__/component.spec.js.snap, src/components/collections/Hero/component.js, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/component.js, src/components/property-page-widgets/PropertyPageHero/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageHero/component.js
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-716)
HomepageHero header can have a filled background color
=> WEB-716 Hero header can be a filled color

src/components/collections/SlideshowHero/__snapshots__/component.spec.js.snap, src/components/media/Slideshow/__snapshots__/component.spec.js.snap, src/components/media/Slideshow/component.js, src/components/property-page-widgets/Pictures/Readme.md, src/components/property-page-widgets/RoomType/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/RoomType/utils/__snapshots__/getModalContentMarkup.spec.js.snap, src/components/property-page-widgets/RoomTypes/__snapshots__/component.spec.js.snap
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-720)
* Exposes className for the `Slideshow` component.
* Removes unused prop in `Pictures`.
=> WEB-720 Expose className for Slideshow component

src/components/property-page-widgets/Pictures/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Pictures/component.js, src/styles/semantic/definitions/lodgify-ui-components/gallery.less, src/styles/semantic/definitions/third-party-components/react-image-gallery.less, src/styles/semantic/themes/default/lodgify-ui-components/gallery.variables, src/styles/semantic/themes/default/third-party-components/react-image-gallery.variables
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-725)
* Fixes the responsive issues happening in the `Gallery` component.
* Makes active thumnails for the `Gallery` more visible; also, including arrows and close button.
* Adds a dark background for all images in the `Gallery` in case an image is not loaded. 
* Makes
=> WEB-725 Fix height responsiveness

src/components/general-widgets/MinimalPromotion/component.js, src/components/media/Gallery/component.js, src/components/property-page-widgets/RoomType/component.js, src/components/property-page-widgets/RoomType/utils/getModalContentMarkup.js, src/styles/semantic/definitions/lodgify-ui-components/minimal-promotion.less
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-695)
MinimalPromotion has a background colour so that when there is no image prop the text is still visible.
=> WEB-695 Add default background

src/components/property-page-widgets/Pictures/Readme.md, src/styles/semantic/definitions/lodgify-ui-components/gallery.less, src/styles/semantic/themes/default/lodgify-ui-components/gallery.variables
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-725)
Changes the way the `Slideshow` resizes for small viewports.
=> WEB-725 Fix slideshow height on small viewports

src/components/collections/Header/components/HeaderLogo.js, src/components/collections/Header/components/__snapshots__/HeaderLogo.spec.js.snap, src/styles/semantic/themes/livingstone/collections/menu.overrides, src/styles/semantic/themes/livingstone/elements/icon.variables, src/styles/semantic/themes/livingstone/globals/site.variables
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-697)
Add max-width and ellipsis to the sub text in the header in order to avoid it to push the Menu icon outside the viewport
=> WEB-697: add ellipsis for subText in the header

.travis.yml, docs/CONTRIBUTING.md, package.json, src/styles/semantic/definitions/lodgify-ui-components/search-bar.less, src/styles/semantic/definitions/third-party-components/react-dates-datepicker.less, src/styles/semantic/themes/livingstone/elements/input.overrides, src/styles/semantic/themes/livingstone/modules/dropdown.overrides, src/styles/semantic/themes/livingstone/modules/dropdown.variables
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-732)
the height of the search bar inputs are controlled by the height of the font.
=> WEB-732 Search bar height

src/components/elements/Avatar/Readme.md, src/components/elements/Avatar/component.js, src/components/elements/Avatar/component.spec.js, src/components/elements/Avatar/index.js, src/components/property-page-widgets/HostProfile/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/HostProfile/component.js, src/styles/semantic/avatar.less, src/styles/semantic/definitions/lodgify-ui-components/avatar.less, src/styles/semantic/definitions/lodgify-ui-components/host-profile.less, src/styles/semantic/host-profile.less, src/styles/semantic/lodgify-ui.less, src/styles/semantic/theme.config, src/styles/semantic/themes/default/lodgify-ui-components/avatar.variables
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-488)
create a Avatar component and use that in HostProfile
=> WEB-488: Avatar component and update Host Profile

src/components/collections/StickyMenu/Readme.md, src/components/collections/StickyMenu/component.js, src/components/collections/StickyMenu/component.spec.js, src/components/collections/StickyMenu/constants.js, src/components/collections/StickyMenu/index.js, src/components/collections/StickyMenu/mock-data/mock-data.js, src/components/collections/StickyMenu/utils/getActiveOnScroll.js, src/components/collections/StickyMenu/utils/getActiveOnScroll.spec.js, src/components/collections/StickyMenu/utils/getComponentTopCoordinates.js, src/components/collections/StickyMenu/utils/getComponentTopCoordinates.spec.js, src/hooks/mocks/testHook.js, src/hooks/useScroll.js, src/hooks/useScroll.spec.js, src/index.js, src/styles/semantic/definitions/lodgify-ui-components/sticky-menu.less, src/styles/semantic/lodgify-ui.less, src/styles/semantic/sticky-menu.less, src/styles/semantic/theme.config, src/styles/semantic/themes/default/lodgify-ui-components/sticky-menu.variables, tools/jest/jest.config.js
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-739)
* Implements `StickyMenu`.
* Implements `useScroll` custom hook.
* A small part of the component test has been commented using `Istanbul ignore`. Behavioural test for this particular case will be added in the future using cypress.
=> WEB-739 Implement StickyMenu

src/styles/semantic/themes/default/lodgify-ui-components/slideshow-hero.variables
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-788)
|before|after|
|-|-|
|<img width="947" alt="image" src="https://user-images.githubusercontent.com/5032333/70904740-641f0780-2002-11ea-9452-00bf635cd69b.png">|<img width="946" alt="image" src="https://user-images.githubusercontent.com/5032333/70904712-55385500-2002-11ea-9553-ab8bad92dd27.png">|
=> WEB-788: adjust the height of SlideshowHero according to the specification

src/components/collections/StickyMenu/component.js, src/components/collections/StickyMenu/component.spec.js, src/components/collections/StickyMenu/mock-data/mock-data.js, src/components/collections/StickyMenu/utils/getComponentTopCoordinates.js
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-740)
Modifies the `StickyMenu` items shape to fit with the model.
=> WEB-740 Modify sticky menu shape

src/components/property-page-widgets/Rates/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Rates/component.js, src/utils/default-strings/constants.js
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-851)
Add a title to Rates component
=> WEB-851: rates title

src/components/property-page-widgets/Reviews/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Reviews/component.js, src/components/property-page-widgets/Reviews/utils/getModalFormMarkup.js, src/utils/default-strings/constants.js
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-842)
=> WEB-842 Remove roomtype dropdown from Reviews

src/components/general-widgets/ContactHomeHero/Readme.md, src/components/general-widgets/ContactHomeHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/ContactHomeHero/component.js, src/components/general-widgets/ContactHomeHero/component.spec.js, src/components/general-widgets/ContactHomeHero/constants.js, src/components/general-widgets/ContactHomeHero/index.js, src/components/general-widgets/ContactHomeHero/mock-data/mock-data.js, src/index.js, src/styles/semantic/definitions/lodgify-ui-components/contact-header.less, src/styles/semantic/definitions/lodgify-ui-components/horizontal-menu.less
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-858)
Eposes provisionally a `ContactHomeHero` component for the capucine template.
=> WEB-858 Expose ContactHomeHero component

src/components/general-widgets/ContactHomeHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/ContactHomeHero/component.js, src/components/property-page-widgets/ContactPropertyHero/Readme.md, src/components/property-page-widgets/ContactPropertyHero/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/ContactPropertyHero/component.js, src/components/property-page-widgets/ContactPropertyHero/component.spec.js, src/components/property-page-widgets/ContactPropertyHero/constants.js, src/components/property-page-widgets/ContactPropertyHero/index.js, src/components/property-page-widgets/ContactPropertyHero/mock-data/mock-data.js, src/index.js
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-859)
Exposes a provisional ContactPropertyHero
=> WEB-859 Expose ContactPropertyHero

src/index.js, src/styles/semantic/themes/default/lodgify-ui-components/contact-header.variables, src/styles/semantic/themes/livingstone/modules/modal.overrides, src/styles/semantic/themes/livingstone/modules/modal.variables
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-813)
Fixes the regression in the `Modal` component which affected its background color and it color of the dropdowns.
=> WEB-813 Fix Modal transparency.

src/styles/semantic/definitions/lodgify-ui-components/gallery.less, src/styles/semantic/definitions/lodgify-ui-components/slideshow-hero.less, src/styles/semantic/definitions/third-party-components/react-image-gallery.less, src/styles/semantic/themes/default/third-party-components/react-image-gallery.variables
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-901)
Fix slideshow/gallery image dimension when is open
=> WEB-901:Fix slideshow/gallery image dimension when is open

src/components/collections/Header/__snapshots__/component.spec.js.snap, src/components/collections/Hero/__snapshots__/component.spec.js.snap, src/components/collections/SlideshowHero/__snapshots__/component.spec.js.snap, src/components/elements/Logo/component.js, src/components/elements/Logo/component.spec.js, src/components/elements/Logo/constants.js, src/components/general-widgets/ContactHomeHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageHero/__snapshots__/component.spec.js.snap
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-553)
Add a class to Logo main container
=> WEB-553: add a class to Logo in order to be targeted in custom code

src/components/collections/Footer/__snapshots__/component.spec.js.snap, src/components/collections/Footer/component.js, src/components/collections/Footer/component.spec.js, src/components/collections/Footer/utils/getGroupedNavigationItems.js, src/components/collections/Footer/utils/getGroupedNavigationItems.spec.js, src/styles/semantic/themes/livingstone/collections/menu.overrides, src/styles/semantic/themes/livingstone/collections/menu.variables
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-881)
Footer menu headers can be links.
=> WEB-881 Footer link

src/styles/semantic/definitions/lodgify-ui-components/contact-header.less
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-913)
Removes unnecessary padding from sub menu items in the `ContactHeader`
=> WEB-913 Remove padding from submenu items for Capucine

src/components/collections/Footer/component.js
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-881)
Submenu parent links can have a target.
=> WEB-881 Footer submenu links

src/styles/semantic/definitions/lodgify-ui-components/contact-header.less
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-913)
Fixes the error where the padding was not being properly removed
=> WEB-913 Remove padding from contact menu dropdowns

src/components/general-widgets/SearchBar/__snapshots__/component.spec.js.snap, src/components/general-widgets/SearchBar/component.js, src/components/general-widgets/SearchBar/component.spec.js, src/components/general-widgets/SearchBar/components/SearchFields/component.js, src/components/inputs/CounterDropdown/component.js, tools/webpack/entries.js
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-480)
Pass custom id from the search bar to the guests popup.
=> WEB-480 availability psb

.github/workflows/node.js.yaml
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-1662)
- Add support for semantic-release
=> WEB-1662-fix-sematic-release

.github/workflows/node.js.yaml
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-1662)
* Attempt to fix semantic release
=> fix(semantic-release): trigger through npx

package.json, tools/semantic-release/release.config.js
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-1662)
* Remove semantic-release plugin
=> fix(semantic-release): remove plugin
