src/components/collections/Form/Readme.md
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-212)
Fixes the references to `submitButtonText` and `actionLink` in the examples for the Form component.
=> TE-212 Fix form examples

package.json, tools/eslint/config.js, tools/eslint/rule-options/react.jsx-filename-extension.js
Add linting rules to enforce no default exports and no .jsx filenames
=> Implement conventions in linting

src/components/elements/Divider/Readme.md, src/components/elements/Divider/component.js, src/components/elements/Divider/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-267)
Adds the `hasLine` prop to the Divider component.
=> TE-267 Divider hasLine prop

src/components/widgets/PropertyPictures/Readme.md, src/components/widgets/PropertyPictures/component.js, src/components/widgets/PropertyPictures/component.spec.js, src/components/widgets/PropertyPictures/index.js, src/components/widgets/PropertyPictures/mock-data/pictures.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-276)
Creates component, examples and tests for PropertyPictures.
At the moment the 'Explore all pictures' link/button has no funcionality. This can be added when we know what it does.
=> TE-276 PropertyPictures

src/components/widgets/PropertyDescription/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-272)
Makes fixes requested in PR #52 :
- Coerce `extraDescriptionText` to `false` in the conditional render block.
=> TE-272 Fixes for PR #52

Jenkinsfile
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-316)
- Deleting also `build/` so that the latest build JS file is added on each release.
=> TE-316 Deleting build folder so only the latest is added

lib/expect-helpers/expectComponentToBe.js, lib/expect-helpers/expectComponentToHaveDisplayName.js, lib/expect-helpers/index.js, src/components/elements/Button/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-314)
Adds `expectComponentToBe` and `expectComponnentToHaveDisplayName` 
There's a little demo in the Button tests.
=> TE-314 More expect helpers

src/components/widgets/PropertyRules/component.js, src/components/widgets/PropertyRules/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-332)
Gives the PropertyRules widget a mobile friendly layout
=> TE-332 Property Rules Responsive

src/components/widgets/KeyFacts/Readme.md, src/components/widgets/KeyFacts/component.js, src/components/widgets/KeyFacts/component.spec.js, src/semantic/src/themes/livingstone/elements/label.overrides, src/semantic/src/themes/livingstone/elements/label.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-328)
Gives the `KeyFacts` widget a mobile friendly layout
=> TE-328 Responsive keyfacts

src/components/widgets/SleepingArrangements/Readme.md, src/components/widgets/SleepingArrangements/component.js, src/components/widgets/SleepingArrangements/component.spec.js, src/components/widgets/SleepingArrangements/mock-data/sleepingArrangements.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-329)
Presenting the responsive version of the `SleepingArrangements` widget.
=> TE-329 Sleeping Arrangements responsive

src/components/elements/DateRangePicker/Readme.md, src/components/elements/DateRangePicker/component.js, src/components/elements/DateRangePicker/component.spec.js, src/components/elements/DateRangePicker/utils/getOpenDirection.js, src/components/elements/DateRangePicker/utils/getOpenDirection.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-337)
Exposes a new prop on `DateRangePicker` to get the calendar to open above the input.
=> TE-337 DateRangePicker open up

src/components/general-widgets/Review/component.js, src/components/general-widgets/Review/component.spec.js, src/components/property-page-widgets/Reviews/component.js, src/components/property-page-widgets/Reviews/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-346)
Adds a breakpoint for the tablet size so columns don't go out of line
Did the same fix for the Review component as well
Desktop
Tablet
Mobile
Desktop
Tablet
Mobile
=> TE-346 PropertyReviews responsive fix

src/components/elements/IconCard/component.js, src/components/elements/IconCard/component.spec.js, src/semantic/src/themes/livingstone/elements/label.overrides, src/semantic/src/themes/livingstone/elements/label.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-338)
Fixes the breaking change on Semantic UI .ui.label
Something *is* right...
=> TE-338 Fix label

src/components/property-page-widgets/Rules/component.js, src/components/property-page-widgets/Rules/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-343)
Fixes errors in the responsive behaviour of the Rules widget.
I agreed with Julio to use a simple `Icon` with a label for Checkin/Checkout. Saves a bunch of complication.
Desktop
Tablet
Mobile
=> TE-343 Rules fixes

src/components/elements/IconCard/Readme.md, src/components/elements/IconCard/component.js, src/components/elements/IconCard/component.spec.js, src/semantic/src/themes/livingstone/elements/label.overrides, src/semantic/src/themes/livingstone/elements/label.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-348)
Changes `IconCard` to accept multiline strings as `props.label`
=> TE-348 Multiline Label

src/components/property-page-widgets/Location/component.js, src/components/property-page-widgets/Location/component.spec.js, src/components/property-page-widgets/Location/index.js, src/components/property-page-widgets/Location/utils/getGoogleMapHeight.js, src/components/property-page-widgets/Location/utils/getGoogleMapHeight.spec.js, src/components/property-page-widgets/Location/utils/getTransportOptionLabel.js, src/components/property-page-widgets/Location/utils/getTransportOptionLabel.spec.js, src/components/property-page-widgets/Location/utils/getTransportOptionsMarkup.js, src/components/property-page-widgets/Location/utils/getTransportOptionsMarkup.spec.js, src/semantic/src/themes/livingstone/elements/label.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-341)
Implements fixes for the Location widget.
- I was able to simplify the markup a little by using `withResponsive` `isUserOnMobile` to modify the `GoogleMap` height.
- I switched to using Semantic UI `Label.Group` to wrap the `IconCards`, which is simpler and reacts more gracefully on awkward screen widths (see screenshots).
**Desktop**
**Tablet**
**Mobile**
**Graceful failure**
=> TE-341 Location fixes

src/components/property-page-widgets/Rules/component.js, src/components/property-page-widgets/Rules/utils/getCheckInOrOutTimeLabel.js, src/components/property-page-widgets/Rules/utils/getCheckInOurOutTimeLabel.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-343)
Isolate getCheckInOrOutTimeLabel as a util. Responds to comment in #122
=> TE-343 Isolate getCheckInOrOutTimeLabel as a util

styleguide/styleguide-components/StyleGuideRenderer/getIsDevelopmentServer.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-351)
Fix. Refer to webpackHotUpdate as a property of the global object.
=> TE-351 Refer to webpackHotUpdate as a property of the global object.

styleguide/styleguide-components/AlphaFlag/component.js, styleguide/styleguide-components/MobilePlaceholder/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-357)
It puts the alpha ribbon behind the mobile placeholder screen but still in front of the code blocks.
=> TE-357 Alpha ribbin z-index fix

styleguide/config/options/theme.js, styleguide/styleguide-components/AlphaFlag/component.js, styleguide/styleguide-components/MobilePlaceholder/component.js, styleguide/styleguide-components/StyleGuideRenderer/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-369)
Adds two variables for z-indexing the components.
After researching mixins in less and looking at the z-indices we already have in lodgify-ui/semantic it seems this is the best alternative to avoid conflicts.
=> TE-369 Add z-index map on style guide components

.gitignore, styleguide/docs/getStarted.md
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-362)
Update the heading sizes on the Get Started section in the documentation 
Removed the second `DS_Store` on the `.gitignore`
=> TE-362 Update heading size of the getting started documentation

package.json
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-389)
Removes an unnecessary dependency (babel) because we are using babel-cli
If you get the `babel: command not found` error message then you'll need to delete node modules
=> TE-389 Remove the babel dependency

src/components/property-page-widgets/Rates/utils/getRateCategoryHeadingMarkup.js, src/components/property-page-widgets/Rates/utils/getRateCategoryHeadingMarkup.spec.js, src/components/property-page-widgets/Rates/utils/getRoomTypeDropdownMarkup.js, src/components/property-page-widgets/Rates/utils/getRoomTypeDropdownMarkup.spec.js, src/components/typography/Paragraph/component.js, src/components/typography/Paragraph/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-408)
Implements the new typography into the Rates component
- Updates Paragraph to accept a node or an array of nodes
- Changes the Icon in the Rates header from `users` to `guests`
=> TE-408 Implement new typography to rates widget

styleguide/styleguide-components/PlaygroundRenderer/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-442)
This reverts commit e90442c6d88ffdfee26c5c800b7f485285f94dc7.
The e90442c commit introduced other overflow issues that went unnoticed at the point of merging the commit into staging.
=> TE-442 Revert PlaygroundRenderer overflow commit

src/components/inputs/Dropdown/Readme.md, src/components/inputs/Dropdown/component.js, src/components/inputs/Dropdown/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-461)
Exposes the disabled prop from Semantic UI's Dropdown, adds unit tests and adds an example.
=> TE-461 Dropdown isDisabled

src/components/inputs/Dropdown/component.js, src/components/inputs/Dropdown/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-461)
Removes the isRequired from the `options` prop
`disabled` prop is now also controlled by whether the `options` prop is an empty array
=> TE-461 Dropdown options

src/components/collections/Footer/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-470)
Stops the footer displaying a `0` when `props.socialMediaLinks.length` is equal to 0.
=> TE-470 Fix the footer social media menu

src/components/collections/Form/component.spec.js, src/components/collections/Header/component.spec.js, src/components/elements/Divider/component.spec.js, src/components/elements/GoogleMap/component.spec.js, src/components/elements/Icon/component.spec.js, src/components/elements/Modal/component.spec.js, src/components/elements/Pagination/component.spec.js, src/components/elements/Quote/component.spec.js, src/components/elements/Submenu/component.spec.js, src/components/elements/Tooltip/component.spec.js, src/components/inputs/CaptchaInput/component.spec.js, src/components/inputs/Checkbox/component.spec.js, src/components/inputs/Dropdown/component.spec.js, src/components/inputs/ErrorMessage/component.spec.js, src/components/inputs/InputController/component.spec.js, src/components/inputs/PhoneInput/component.spec.js, src/components/inputs/RadioButton/component.spec.js, src/components/inputs/TextArea/component.spec.js, src/components/inputs/TextInput/component.spec.js, src/components/inputs/Toggle/component.spec.js, src/components/media/FullBleed/component.spec.js, src/components/media/Slideshow/component.spec.js, src/components/property-page-widgets/Description/component.spec.js, src/components/property-page-widgets/PaymentInformation/component.spec.js, src/components/property-page-widgets/Pictures/component.spec.js, src/components/property-page-widgets/Reviews/component.spec.js, src/components/property-page-widgets/SleepingArrangements/component.spec.js, src/components/typography/Heading/component.spec.js, src/components/typography/Paragraph/component.spec.js, src/utils/react-google-maps/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-574)
Replaces all the displayName unit tests that were using `.toBe` with `expectComponentToHaveDisplayName`
=> TE-574 Use displayName expect helpers

package.json, src/styles/semantic/definitions/third-party-components/react-dates-datepicker.less, src/styles/semantic/themes/default/third-party-components/react-dates-datepicker.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-601)
Upgrades the dependency, `react-dates`, from v16 to v17
A number of breaking changes have been introduced in this upgrade.
1. Default styling has been removed from custom navigation buttons, because of this we need to add our own CSS to resolve this issue
2. The datepicker height is now computed using the number of weeks rather than the computed height, so the datepicker assumes the height of the cells will always be the same and due to our custom stying, a white space will appear after the dates. So the fix is to expand the height of the table cells to respect this assumption.
__Preview of the datepickers with the new version__
=> TE-601 Update ReactDates to v17

package.json, src/components/property-page-widgets/Availability/component.js, src/components/property-page-widgets/Availability/constants.js, src/components/property-page-widgets/Availability/utils/renderMonthHeader.js, src/components/property-page-widgets/Availability/utils/renderMonthHeader.spec.js, src/styles/semantic/definitions/third-party-components/react-dates-datepicker.less, src/styles/semantic/themes/default/third-party-components/react-dates-datepicker.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-604)
Adds weekday mapping to Availability calendars
I wish the dependency React Dates handled this for us, but it looks like we need to construct the weekday mapping header ourselves.
I have used the same classes they have applied in the datepicker components they provide, this will help us inherit any styles they provide to better allow the header template to sit naturally in the availability component.
I had to also introduce a new dependency to add support for the moment object in PropTypes.
=> TE-604 Add week day mapping to Availability calendars

src/components/general-widgets/FeaturedProperty/component.js, src/components/general-widgets/FeaturedProperty/utils/getPropertyDescription.js, src/components/general-widgets/FeaturedProperty/utils/getPropertyDescription.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-615)
Remove `.isRequired` from `bedroomsNumber` on `FeaturedProperty`
Note that the ticket says remove the prop altogether. I don't think this is necessary - we can leave it on here as we/others may or may not consume the prop later.
=> TE-615 Remove `.isRequired` from `bedroomsNumber` on `FeaturedProperty`

src/components/collections/Form/component.js, src/components/general-widgets/Contact/Readme.md, src/components/general-widgets/Contact/component.js, src/components/general-widgets/Contact/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-617)
Extends the Contact component to have the ability to only show the necessary dropdowns
- Fixed a issue in the Form component when `React.createElement` and `React.cloneElement` was trying to clone or create `null` or `undefined`.
=> TE-617 Extend Contact component

src/components/general-widgets/SearchBar/Readme.md, src/components/general-widgets/SearchBar/component.js, src/components/general-widgets/SearchBar/component.spec.js, src/components/general-widgets/SearchBar/utils/getFormFieldMarkup.js, src/components/general-widgets/SearchBar/utils/getFormFieldMarkup.spec.js, src/styles/semantic/themes/livingstone/modules/modal.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-609)
Updates the search bar to appear in a modal when on mobile.
The mock-up can be found here zpl.io/awYNvBg
This update includes:
1. Placeing the search bar in a modal and stacks the fields
2. Adding a prop to determine if the search bar should be in a modal
3. Adding a prop to set the modal trigger element, a default is set in case this prop is not set
4. Adding a clear fix to all content containers in the Modal component
=> TE-609 Make the search bar responsive

src/components/media/Video/component.js, src/components/media/Video/utils/getPlayerCss.js, src/components/media/Video/utils/getPlayerCss.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-703)
Convert props, Width and Height, to type number
=> TE-703: Video, Width and height props should be type number

src/styles/semantic/themes/livingstone/modules/modal.overrides, src/styles/semantic/themes/livingstone/modules/modal.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-777)
Removes the height `100% - 1px` CSS to fix the fullscreen bug
- Also had to remove the margin from the fullscreen modal to ensure it is 100% fullscreen.
__The `margin: 0 !important` fixes:__
__Preview of fullscreen modal with device toolbar open in Chrome devtools__
=> TE-777: clean up fullscreen version of Modal

src/styles/semantic/themes/livingstone/elements/segment.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-812)
Removes the mobile padding from the Promotion component
__before__
__after__
=> TE-812: remove mobile padding from Promotion

src/components/collections/Form/utils/getFormChild.js, src/components/general-widgets/Contact/Readme.md, src/components/general-widgets/Contact/component.js, src/components/general-widgets/Contact/component.spec.js, src/utils/default-strings/constants.js, src/utils/default-strings/index.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-839)
Exposes strings props on `Contact`.
Please review this carefully as the agreed solution will be followed across all components.
I considered two approaches for exposing strings props...
1. Expose a single `strings` prop, being an object containing each of the necessary strings; and
1. Expose a single prop for each of the necessary strings.
I opted for 2., for the following reasons...
- Flat string props are great for rerendering on update. There are no complications associated with object identity.
- It makes use of the top level React `defaultProps` API with no intermediate steps. This is great both for simplicity of code and for props documentation in Styleguidist. 
- It is the simplest solution, requiring the minimum …
=> TE-839 Expose strings props on `Contact`

src/components/general-widgets/CallMeBack/Readme.md, src/components/general-widgets/CallMeBack/component.js, src/components/general-widgets/Contact/component.js, src/components/general-widgets/OwnerLogin/Readme.md, src/components/general-widgets/OwnerLogin/component.js, src/components/general-widgets/OwnerLogin/component.spec.js, src/components/general-widgets/OwnerLogin/utils/getForgotPasswordFormMarkup.js, src/components/general-widgets/OwnerLogin/utils/getForgotPasswordFormMarkup.spec.js, src/components/general-widgets/OwnerSignUp/Readme.md, src/components/general-widgets/OwnerSignUp/component.js, src/components/general-widgets/Promotion/component.js, src/components/property-page-widgets/HostProfile/Readme.md, src/components/property-page-widgets/HostProfile/component.js, src/components/property-page-widgets/HostProfile/utils/getStringWithColonSuffix.js, src/components/property-page-widgets/HostProfile/utils/getStringWithColonSuffix.spec.js, src/components/property-page-widgets/KeyFacts/Readme.md, src/components/property-page-widgets/KeyFacts/component.js, src/components/property-page-widgets/Location/Readme.md, src/components/property-page-widgets/Location/component.js, src/components/property-page-widgets/PaymentInformation/Readme.md, src/components/property-page-widgets/PaymentInformation/component.js, src/components/property-page-widgets/Pictures/Readme.md, src/components/property-page-widgets/Pictures/component.js, src/components/property-page-widgets/Reviews/Readme.md, src/components/property-page-widgets/Reviews/component.js, src/components/property-page-widgets/Rules/component.js, src/components/property-page-widgets/SleepingArrangements/Readme.md, src/components/property-page-widgets/SleepingArrangements/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-920)
Makes strings props names and documentation consistent
We must focus on the following things to save our API from becoming confusing to use...
These PRs featured two or more variations for naming the same thing. 
Some examples:
- `formHeadingText`, `headingText`, `[widgetNameSpace]headingText` can all be `headingText`
- `propertyInputLabel`, `propertyDropdownLabel` can be `propertyInputLabel`
- `formButtonText`, `submitButtonText` can be `submitButtonText`
Copy and paste is your friend. 
No need for `paymentInformationHeadingText` inside `PaymentInformation`. Just use `headingText`.
Prop documentation isn't an afterthought. It's the most important thing. 
- Don't be lazy when writing prop documentation. Things like `/** …
=> TE-920 Tweaks for string prop naming

src/components/general-widgets/FeaturedRoomType/Readme.md, src/components/general-widgets/FeaturedRoomType/component.js, src/components/general-widgets/FeaturedRoomType/component.spec.js, src/components/general-widgets/FeaturedRoomType/utils/getRoomTypeDescription.js, src/components/general-widgets/FeaturedRoomType/utils/getRoomTypeDescription.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-899)
Exposes bedsLabel and guestsLabel string props to allow for internationalisation
=> TE-899 FeaturedRoomType string props

src/components/general-widgets/FeaturedProperty/component.js, src/components/general-widgets/FeaturedRoomType/component.js, src/styles/semantic/themes/livingstone/views/card.overrides, src/styles/semantic/themes/livingstone/views/card.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-955)
adds styling for the featured properties such as:
1. Sets the height of the feature property cards to 155px
2. Updates the spacing between the star icons is 4px
Please refer to the ticket for more information.
__Preview of featured property__
__Preview of feature room type__
---
__Before, Preview of featured property__
=> TE-955: Add styles for featured cards

src/styles/semantic/themes/livingstone/modules/rating.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-958)
Sets the rating icon to 14px for any component that consumes the `Rating` component, this will set the spacing between each icon to 4px
__Before__
__After__
=> TE-958: Set spacing between icons to 4px for Rating

src/components/collections/Header/component.js, src/styles/semantic/themes/livingstone/collections/menu.variables
Removes the box shadow and border from the menu if it is used in `Header` and has the class `borderless`
- The `text` prop will add the class `text` to the menu, more info here https://react.semantic-ui.com/collections/menu/#types-text
__Before__
__After__
=> TE-960: remove border and shadow from Menu if in Header

src/components/collections/Footer/component.js, src/components/collections/Footer/component.spec.js, src/components/collections/Header/component.js, src/components/collections/Header/component.spec.js, src/styles/semantic/themes/livingstone/collections/menu.overrides, src/styles/semantic/themes/livingstone/collections/menu.variables, src/styles/semantic/themes/livingstone/elements/container.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-962)
Applies the `Container` to the `Header` and `Footer`
- I had to slightly refactor the `Footer` to accommodate the `Container`, I added two divs with the classes `.bottom-navigation` and `.top-navigation` to contain the `Menu` components
- The content of the `Header` and `Footer` will now be restricted to `1040px`
__Before__
__After__
__Before__
__After__
=> TE-962: Apply the Container to the Header & Footer

.travis.yml, package.json
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1017)
Creates a new `test:ci` that runs `npm run test` with an extra `--runInBand` flag so each unit test is ran sequentially and updates travis config to use that command. 
https://jestjs.io/docs/en/troubleshooting.html#tests-are-extremely-slow-on-docker-and-or-continuous-integration-ci-server
=> TE-1017 Fix Travis build

src/styles/semantic/themes/livingstone/views/card.overrides, src/styles/semantic/themes/livingstone/views/card.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-990)
Adds a height to the images so the image mixed with flex grow doesn't stretch to 100% of it's container. 
- Object fit is not fully supported by IE 11 but as a fallback the image doesn't maintain it's proportions but this gives us a nice fallback for when the image src is portrait.
=> TE-990: Stop featured images from growing to 100% of container

src/components/property-page-widgets/Amenities/Readme.md, src/components/property-page-widgets/Amenities/component.js, src/components/property-page-widgets/Amenities/component.spec.js, src/components/property-page-widgets/Amenities/utils/getExtraItemsMarkup.js, src/components/property-page-widgets/Amenities/utils/getExtraItemsMarkup.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1007)
Add prop to render extra items after default items or render extra items in modal
This part of the design improvements for the room type, more info can be found here https://youtrack.lodgify.net/issue/TE-999
__Preview__
=> TE-1007: amenities all

src/components/inputs/Dropdown/Readme.md, src/components/inputs/Dropdown/component.js, src/components/inputs/Dropdown/mock-data/options.js, src/components/inputs/Dropdown/utils/adaptOptions.js, src/components/inputs/Dropdown/utils/getHasIndentedOptions.js, src/components/inputs/Dropdown/utils/getHasIndentedOptions.spec.js, src/styles/semantic/themes/livingstone/modules/dropdown.overrides, src/styles/semantic/themes/livingstone/modules/dropdown.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-988)
Adds ability to indent dropdown options, unit tests and adds an example.
- Added the accepted values in documentation because nested shapes don't get the "One of: " documentation.
=> TE-988 Nested dropdown options

src/styles/semantic/themes/livingstone/collections/menu.overrides, src/styles/semantic/themes/livingstone/collections/menu.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1034)
Fixes active link style for inverted `Menu`
__Before__
__After__
=> TE-1034: active link inherit background color for inverted `Menu`

src/components/property-page-widgets/Amenities/Readme.md, src/components/property-page-widgets/Amenities/component.js, src/components/property-page-widgets/Amenities/component.spec.js, src/components/property-page-widgets/Amenities/utils/getAmenityMarkup.js, src/components/property-page-widgets/Amenities/utils/getAmenityMarkup.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1033)
Allows the vertical spacing to be optional in `Amenities`
- Since Amenities may exist nested in another component, we need to remove the spacing
- Since Amenities can appear as a primary component in our pages, we need to keep the padding
__Before__
__After__
=> TE-1033: Allows the vertical spacing to be optional in `Amenities`

src/components/general-widgets/Review/component.js, src/components/general-widgets/Review/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1020)
Removes the vertical spacing for the `Review`
__Before__
__After__
=> TE-1020: remove vertical padding for `Review`

src/styles/semantic/themes/livingstone/elements/button.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1035)
updates icon width in Button
__Before__
__After__
=> TE-1035: icon should be the correct width in Button

src/components/layout/Grid/Readme.md, src/components/layout/Grid/component.js, src/components/layout/Grid/component.spec.js, src/components/property-page-widgets/Amenities/utils/getAmenityMarkup.js, src/styles/semantic/themes/livingstone/collections/grid.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1041)
Updates the amenities to ensure items always display in a three column grid
1. This involved adding the prop `isStrict` to the Grid
__Before__
__After__
=> TE-1041: Ensure items in Amenities always display in a 3 column grid

src/components/collections/Header/utils/hasSearchBarOptions.js, src/components/collections/Header/utils/hasSearchBarOptions.spec.js, src/components/general-widgets/SearchBar/Readme.md, src/components/general-widgets/SearchBar/component.js, src/components/general-widgets/SearchBar/component.spec.js, src/components/general-widgets/SearchBar/utils/getFormFieldMarkup.js, src/components/general-widgets/SearchBar/utils/getFormFieldMarkup.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1046)
Removes `props.isShowingLocationDropdown` from SearchBar as we can just check if there are any being passed into the component and updates the Header to correctly render the SearchBar depending on the options available
=> TE-1046 Header and SearchBar LocationOptions

src/styles/semantic/themes/livingstone/collections/menu.overrides, src/styles/semantic/themes/livingstone/collections/menu.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1091)
Adds a max width and height to the header's logo
=> TE-1091 Fix the max height and width of header logo

src/components/elements/Quote/component.js, src/components/elements/Quote/component.spec.js, src/components/general-widgets/Promotion/component.js, src/components/general-widgets/Promotion/component.spec.js, src/components/layout/GridColumn/component.js, src/components/layout/GridColumn/component.spec.js, src/components/media/Gallery/Readme.md, src/components/media/Gallery/component.js, src/components/media/Gallery/component.spec.js, src/components/media/Gallery/index.js, src/components/property-page-widgets/Amenities/utils/getCategoryMarkup.js, src/components/property-page-widgets/Amenities/utils/getExtraItemsMarkup.js, src/components/property-page-widgets/Availability/component.js, src/components/property-page-widgets/Description/component.js, src/components/property-page-widgets/Rates/component.js, src/index.js, src/styles/semantic/themes/livingstone/modules/modal.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1100)
Exposes `Gallery` component with tests and examples
=> TE-1100 Gallery: expose component with tests and examples

src/components/collections/Footer/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1106)
Ensure 0 is not rendered in the Footer if no social items exist
__Before__
__After__
=> TE-1106: ensure 0 is not rendered in the social menu for the Footer

src/components/collections/Footer/component.js, src/components/collections/Footer/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1105)
Hide phone icon if phone string is empty
__Before__
__After__
=> TE-1105: if phone is empty string, do not show icon in Footer

src/styles/semantic/themes/livingstone/elements/segment.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1109)
The children in the `Hero` should appear above the background shadow
__Before__
__After__
=> TE-1109: children should have a higher z-index in the Hero

src/components/collections/Header/utils/getDesktopMenuMarkup.js, src/components/elements/Submenu/component.js, src/components/elements/Submenu/component.spec.js, src/components/elements/Submenu/utils/getValueProp.js, src/components/elements/Submenu/utils/getValueProperty.js, src/components/elements/Submenu/utils/getValueProperty.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1128)
Fixes the selected state being applied when a link is clicked in the `Dropdown` menu in the `Header`
- The `Dropdown` component is meant to return with a selected value, it is not meant to contain a link
- The solution was to add an option to set the value of the dropdown and to ensure the value never changed, to achieve this, I just set a numeric value that wouldn't match the existing options
- Another important rule to follow here was to only apply the value prop if the value prop was to be set to disable the options, this introduced the get value property utility in the `Submenu`
*Please note that the white page is displayed after the click because the page does not exist
__Before__
__After__
=> TE-1128: Fix the Submenu click style in the Header

src/utils/get-gallery-heading-markup/getGalleryHeadingMarkup.js
Ensure if the rating value is 0, the 0 does not appear in the `PropertyPageHero`
__Before__
__After__
=> TE-1138: ensure the condition does not leak in the PropertyPageHero

src/components/typography/Heading/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1111)
Set the default value for textAlign to null
__Before__
__After__
=> TE-1111: textAlign value default to null for Heading

src/styles/semantic/themes/livingstone/elements/segment.overrides, src/styles/semantic/themes/livingstone/elements/segment.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1152)
Ensure the Header is above the content in the `Hero`
__Before__
__After__
=> TE-1152: In Hero the Header dropdown should be above the content

src/components/elements/Icon/component.js, src/components/elements/Icon/component.spec.js, src/components/property-page-widgets/RoomType/component.js, src/components/property-page-widgets/RoomType/component.spec.js, src/components/property-page-widgets/RoomType/utils/getModalContentMarkup.js, src/components/property-page-widgets/RoomType/utils/getRoomFeaturesMarkup.js, src/components/property-page-widgets/RoomType/utils/getRoomFeaturesMarkup.spec.js, src/styles/semantic/themes/livingstone/collections/grid.overrides, src/styles/semantic/themes/livingstone/elements/icon.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1164)
Cleans up the mobile appearance of the `RoomType`
__Ideally review commit by commit__
- Stacks the GridColumns for Amenities on mobile
- Improves the padding around the list items
- Allows for content in the icon to expand
=> TE-1164: Cleanup the mobile version of `RoomType`

src/components/collections/Footer/component.js, src/components/general-widgets/FeaturedProperties/component.js, src/components/general-widgets/FeaturedRoomTypes/component.js, src/components/property-page-widgets/RoomTypes/Readme.md, src/components/property-page-widgets/RoomTypes/component.js, src/components/property-page-widgets/RoomTypes/component.spec.js, src/components/property-page-widgets/RoomTypes/index.js, src/components/property-page-widgets/RoomTypes/mock-data/roomTypes.js, src/index.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1168)
Adds the `RoomTypes` component to display a collection of `RoomType`
__Preview__
=> TE-1168: Add the `RoomTypes` component

src/components/media/Gallery/component.js, src/components/property-page-widgets/Pictures/__snapshots__/component.spec.js.snap, src/styles/semantic/themes/livingstone/elements/container.variables, src/styles/semantic/themes/livingstone/globals/site.variables, src/styles/semantic/themes/livingstone/modules/modal.overrides, src/styles/semantic/themes/livingstone/modules/modal.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1170)
Places the close icon on the right side of the modal in the `Gallery` to align with the horizontal gutter
- Extracted out the horizontal gutter max width since it is needed in the Modal styles
- Discussed with Julio, if `isFullscreen` is true, we can assume the `HorizontalGutters` are being applied.
- The mobile version should keep the icon in the same position, the top right
- This has been tested with the  `Header` and `SearchForm` fullscreen modals
=> TE-1170: Move the close icon in the Gallery

src/components/property-page-widgets/Amenities/component.js, src/components/property-page-widgets/Amenities/component.spec.js, src/components/property-page-widgets/Amenities/utils/getExtraItems.js, src/components/property-page-widgets/Amenities/utils/getExtraItems.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1224)
Ensure items in Amenities are not being duplicated when applying extra items
=> TE-1224: stop items from being duplicated in the Amenities

src/components/collections/Hero/__snapshots__/component.spec.js.snap, src/components/collections/Hero/component.js, src/components/collections/Hero/component.spec.js, src/components/collections/Table/component.js, src/components/elements/Divider/component.js, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/media/FullBleed/__snapshots__/component.spec.js.snap, src/components/media/FullBleed/component.js, src/components/media/FullBleed/component.spec.js, src/components/media/ResponsiveImage/__snapshots__/component.spec.js.snap, src/components/media/ResponsiveImage/component.js, src/components/media/ResponsiveImage/component.spec.js, src/components/media/Thumbnail/component.js, src/components/property-page-widgets/Pictures/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Rates/__snapshots__/component.spec.js.snap, src/styles/semantic/themes/livingstone/elements/segment.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1205)
Removes className prop from FullBleed, Hero, ResponsiveImage and Table components because lodgify-ui doesn't support this functionality.
- Thumbnail and Divider need the className prop so they can use the responsive wrappers `ShowOnMobile` and `ShowOnDesktop` but they have been removed from the documentation.
=> TE-1205 Refactor out className

src/styles/semantic/themes/livingstone/elements/segment.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1236)
Update the promotion code button to display centered when the `Promotion` component is to be displayed as stacked
=> TE-1236: Fix the promotion code button when displayed as stacked

src/components/layout/ShowOnDesktop/component.js, src/components/layout/ShowOnMobile/component.js, src/components/property-page-widgets/PropertyPageSearchBar/component.js, src/components/property-page-widgets/Rates/component.js, src/styles/semantic/themes/livingstone/globals/site.overrides, src/styles/semantic/themes/livingstone/globals/site.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1209)
Responds to the comments in a closed PR
Comments left over slack message: 
[Here](https://github.com/lodgify/lodgify-ui/pull/391/commits/a4f3eaee71b131339f8a5bc53bdb287ad2c2148d#diff-9db5ca13d272f5d2fb6018e39a280aa5R439) you can use `@media @tabletScreen`
And would be good to use a similar pattern [here](https://github.com/lodgify/lodgify-ui/pull/391/commits/a4f3eaee71b131339f8a5bc53bdb287ad2c2148d#diff-9db5ca13d272f5d2fb6018e39a280aa5R431)
So.. define a `@computerScreen: only screen and (min-width: @smallestComputerBreakpoint);`
and use it as `@media @computerScreen`
[Here](https://github.com/lodgify/lodgify-ui/pull/391/commits/a20261712971871a8e0f84b8a32f60d244371cc8#diff-4010bda9d045c2b812a8fa90b381336dR44) i suggest …
=> TE-1209 ShowOn`Device` PR response

src/styles/semantic/themes/livingstone/collections/menu.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1283)
The menu items underline is determined by the theme's primary colour.
=> TE-1283 Add theming to menu item underlines

src/components/media/Gallery/component.js, src/components/property-page-widgets/Pictures/__snapshots__/component.spec.js.snap, src/styles/semantic/themes/livingstone/modules/modal.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1170)
Cleans up the selectors for the headings in the `Gallery` modal
- There is no visual difference with this change
- In the previews below, only the highlighted headings are reduced
__Previews of reduce headings__
__Responsive preview__
- No need to reduce the heading width because of where the close icon is positioned
=> TE-1170: Update the CSS selectors in the gallery modal

src/styles/semantic/themes/livingstone/globals/site.overrides, src/styles/semantic/themes/livingstone/globals/site.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1260)
Set the line height for each of the Headings, sizes are listed in the ticket
__Before__
__After__
__Before__
__After__
=> TE-1260: set the line height for the Headings

.babelrc, package.json
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1275)
Adds `babel-plugin-lodash` which takes >23 KB off the library size.
```sh
Package size: 343.32 KB
Size limit:   350 KB
```
```sh
Package size: 320.06 KB
Size limit:   350 KB
```
=> TE-1275 Add `babel-plugin-lodash`

.babelrc, package.json
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1277)
Add `transform-react-remove-prop-types`.
This doesn't have a direct impact on library build size but allows consumers of the library to shave off ~4 KB.
=> TE-1277 Add `transform-react-remove-prop-types`

package.json
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1291)
Move `moment` from dependencies to peerDependencies
Since `moment` objects are exposed at the `@lodgify/ui` interface, the library ought to be a peer dependency.
This also reduce the 'library' size significantly. It is up to the consumer of the library how the choose to optimise `moment`. There are a bunch of optimisations which can be made.
```sh
Package size: 320.06 KB
Size limit:   350 KB
```
```sh
Package size: 251.59 KB
Size limit:   321 KB
```
=> TE-1291 Move `moment` from dependencies to peerDependencies

.babelrc, package.json
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1276)
Reduces the overall build size by converting our Semantic UI React imports into path imports when babel transforms our code.
- This plugin for Babel was implemented since the official plugin does not yet support Babel 7 https://www.npmjs.com/package/babel-plugin-semantic-ui-react-transform-imports
- Discussed here `https://github.com/skleeschulte/babel-plugin-transform-semantic-ui-react-imports/pull/2`
```
Package size: 251.82 KB
Size limit:   256 KB
```
```
Package size: 246.4 KB
Size limit:   247 KB
```
=> TE-1276: Add babel import plugin for Semantic Ui React components

package.json
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1296)
Pins `stylelint` to version 9.6.0 while the bug reported at https://github.com/stylelint/stylelint/issues/3749 is patched
=> TE-1296 Pin stylelint to v9.6.0 while bug is patched

src/components/collections/Hero/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/Promotion/__snapshots__/component.spec.js.snap, src/components/media/FullBleed/__snapshots__/component.spec.js.snap, src/components/media/ResponsiveImage/Readme.md, src/components/media/ResponsiveImage/__snapshots__/component.spec.js.snap, src/components/media/ResponsiveImage/component.js, src/components/media/Thumbnail/__snapshots__/component.spec.js.snap, src/components/media/Thumbnail/component.js, src/components/media/Thumbnail/component.spec.js, src/components/property-page-widgets/Pictures/__snapshots__/component.spec.js.snap, src/styles/semantic/themes/livingstone/elements/image.overrides, src/styles/semantic/themes/livingstone/globals/site.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1303)
Gives the Thumbnail the capability to gracefully load
**Before**
**After**
=> TE-1303 Thumbnail to use ResponsiveImage

.babelrc, package.json
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1311)
This will import the Semantic Ui React components with commonjs instead of Es modules
- This is a requirement since TemplatesSSR will render the components on the server where Es modules are not yet supported.
=> TE-1311: Use commonjs when getting Semantic UI react components

src/components/property-page-widgets/RoomType/Readme.md, src/components/property-page-widgets/RoomType/component.js, src/components/property-page-widgets/RoomType/utils/__snapshots__/getModalContentMarkup.spec.js.snap, src/components/property-page-widgets/RoomType/utils/getModalContentMarkup.js, src/components/property-page-widgets/RoomType/utils/getModalContentMarkup.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1332)
The props `description` and `ratingNumber` should be optional in the `RoomType` component
- Also refactored the `getModalContentMarkup` utility specs to use snapshot testing.
- Cleaned up the Readme documentation, we had an example showing props we no longer support
- When the props `ratingNumber` and `description` are null
=> TE-1332: Make description and ratingNumber optional in the RoomType component

src/components/property-page-widgets/RoomType/component.js, src/components/property-page-widgets/RoomType/utils/getRoomFeaturesMarkup.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1375)
Corrects the prop structure of the `features` and `extraFeatures` in `RoomType`
=> TE-1375: Correct the props in features and extraFeatures in RoomType

src/components/collections/Header/utils/getDesktopMenuMarkup.js, src/components/collections/Header/utils/getMobileMenuMarkup.js, src/components/elements/Icon/component.js, src/components/general-widgets/Promotion/Readme.md, src/components/general-widgets/Promotion/__snapshots__/component.spec.js.snap, src/components/general-widgets/Promotion/component.js, src/components/general-widgets/Promotion/component.spec.js, src/components/inputs/Dropdown/component.js, src/styles/semantic/themes/livingstone/elements/segment.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1389)
Makes the Promotion component responsive and removes the `isDisplayedStacked` prop
- Fixes any lint issues that have been introduced from a recent update to `prettier`
=> TE-1389: Make the Promotion component responsive

src/components/media/ResponsiveImage/component.js, src/components/media/ResponsiveImage/component.spec.js, src/components/media/ResponsiveImage/utils/__snapshots__/getPlaceHolderImageMarkup.spec.js.snap, src/components/media/ResponsiveImage/utils/getPlaceHolderImageMarkup.spec.js, src/components/media/ResponsiveImage/utils/getPlaceholderImageMarkup.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1393)
Removes the blur from components, that didn't have a component lifecycle method, when the image has loaded.
These screenshots are taken from running the node server locally. Which is the closest I could get to staging.
=> TE-1393 Remove blur from graceful images

src/components/collections/Form/utils/getValidationWithDefaults.js, src/components/collections/Form/utils/getValidationWithDefaults.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1385)
This will ensure if a field contains the value `0`, the field will not be seen to have an empty value in the form
- Some spec coverage has also been added for `getIsEmpty`.
=> TE-1385: ensure getIsEmpty returns false if value is 0

src/styles/semantic/themes/livingstone/elements/segment.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1389)
Fixes the rendering of the Promotion component for the mobile viewport when the component is nested in a `Grid`
- Also, when the Promotion is shown on mobile, the discount section will now have the padding correctly applied
- Conflicting CSS rules were being applied to a nested Grid in the Promotion component when the component was being rendered in TemplatesSSR, this update will override these conflicting CSS rules.
In the following previews, the promotion component is nested in a `Grid`
=> TE-1389: The Promotion appears as expected if nested under Grid

src/components/collections/Form/utils/getValidationWithDefaults.js, src/components/collections/Form/utils/getValidationWithDefaults.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1422)
Ensures the default required message string is used if the passed `isRequiredMessage` contains an empty string
- This is causing the Forms to appear without field validation
- This is currently an issue since the translated messages are returning empty strings
=> TE-1422: Use default required message if the passed prop is an empty string

src/components/media/ResponsiveImage/__snapshots__/component.spec.js.snap, src/components/media/ResponsiveImage/component.js, src/components/media/ResponsiveImage/component.spec.js, src/components/media/ResponsiveImage/utils/__snapshots__/getPlaceHolderImageMarkup.spec.js.snap, src/components/media/ResponsiveImage/utils/getImageMarkup.js, src/components/media/ResponsiveImage/utils/getPlaceHolderImageMarkup.spec.js, src/components/media/ResponsiveImage/utils/getPlaceholderImageMarkup.js, src/styles/semantic/themes/livingstone/elements/image.overrides, src/styles/semantic/themes/livingstone/elements/image.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1406)
If the image is in the cache, then just show it and do not show the blurred image. 
- Also removed the `isFluid` JsDoc param from the image markup utilities
=> TE-1406: Just load the image if it exists in the cache

src/components/property-page-widgets/PaymentInformation/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PaymentInformation/component.js, src/components/property-page-widgets/PaymentInformation/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1447)
If the relevant props for the row are undefined, then the row will not be rendered.
- Also refactored the `PaymentInformation` specs to use snapshot testing
=> TE-1447: Hide rows if relevant props are undefined in PaymentInformation

src/components/property-page-widgets/RoomType/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/RoomType/component.js, src/components/property-page-widgets/RoomType/utils/__snapshots__/getModalContentMarkup.spec.js.snap, src/components/property-page-widgets/RoomType/utils/getModalContentMarkup.js, src/components/property-page-widgets/RoomType/utils/getModalContentMarkup.spec.js, src/styles/semantic/themes/livingstone/modules/modal.overrides, src/styles/semantic/themes/livingstone/modules/modal.variables, src/styles/semantic/themes/livingstone/views/card.overrides, src/styles/semantic/themes/livingstone/views/card.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1468)
Restricts the RoomType slideshow image sizes and adds a graceful fallback for IE 11. Hides the bullet navigation when there is only one image in the slideshow.
** Modal **
** Standard **
** Mobile ** 
** Modal **
** Standard **
** Mobile **
=> TE-1468 RoomType image size

src/components/collections/Hero/Readme.md, src/components/collections/Hero/__snapshots__/component.spec.js.snap, src/components/collections/Hero/component.js, src/components/collections/Hero/constants.js, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/media/FullBleed/Readme.md, src/components/media/FullBleed/__snapshots__/component.spec.js.snap, src/components/media/FullBleed/component.js, src/components/media/FullBleed/constants.js, src/components/property-page-widgets/PropertyPageHero/component.js, src/components/property-page-widgets/PropertyPageHero/constants.js, src/styles/semantic/themes/livingstone/elements/segment.overrides, src/styles/semantic/themes/livingstone/elements/segment.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1460)
Reduce the height of the `PropertyPageHero` to accommodate the fixed search bar
- Updated the `Hero` and the `FullBleed` to support a prop called `bottomOffset`. The purpose of `bottomOffset` is to reduce the height of the `FullBleed`.
- Relies on CSS variables 
- The height of the hero has been reduced by `85px`
=> TE-1460: Reduce the PropertyPageHero height

src/components/collections/Form/Readme.md, src/components/collections/Form/component.js, src/components/collections/Form/component.spec.js, src/components/collections/Form/utils/getIsRequiredErrorThenSetState.js, src/components/collections/Form/utils/getIsRequiredErrorThenSetState.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1426)
Applies the `isRequired` error validation to the `handleInputChange`.
- Also updated the Form documentation to have an empty string option for the `Dropdown` to demonstrate the required state.
- This bug is specific to the Dropdown.
- We only rely on the blur event to handle the required state, and the change event is only used to handle the isValid state.
- So when a value was changed in the `Dropdown`, the change event would override the state to set the field as valid without taking the required state into account.
- Once the user interacted with the Dropdown again without changing the value, the blur event would then apply the required state if the value was an empty string.
=> TE-1426: In the Form, handle the required validation onChange

src/components/collections/Hero/__snapshots__/component.spec.js.snap, src/components/general-widgets/FeaturedProperty/__snapshots__/component.spec.js.snap, src/components/general-widgets/FeaturedRoomType/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/Promotion/__snapshots__/component.spec.js.snap, src/components/general-widgets/Promotion/component.js, src/components/media/FullBleed/__snapshots__/component.spec.js.snap, src/components/media/FullBleed/component.js, src/components/media/Gallery/component.js, src/components/media/ResponsiveImage/Readme.md, src/components/media/ResponsiveImage/__snapshots__/component.spec.js.snap, src/components/media/ResponsiveImage/component.js, src/components/media/ResponsiveImage/component.spec.js, src/components/media/ResponsiveImage/utils/__snapshots__/getImageMarkup.spec.js.snap, src/components/media/ResponsiveImage/utils/__snapshots__/getPlaceHolderImageMarkup.spec.js.snap, src/components/media/ResponsiveImage/utils/getImageMarkup.js, src/components/media/ResponsiveImage/utils/getImageMarkup.spec.js, src/components/media/ResponsiveImage/utils/getPlaceHolderImageMarkup.spec.js, src/components/media/ResponsiveImage/utils/getPlaceholderImageMarkup.js, src/components/property-page-widgets/Pictures/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Pictures/component.js, src/styles/semantic/themes/livingstone/elements/image.overrides, src/styles/semantic/themes/livingstone/elements/segment.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1489)
Switches `source` for `srcSet` in `ResponsiveImage`. This removes the awkward `picture` element and plays nicely with the graceful loading functionality.
=> TE-1489 Switch `source` for `srcset` in `ResponsiveImage` 

package.json, src/components/property-page-widgets/Pictures/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Pictures/component.js
Use `props.pictures.imageUrl`, which is required by the child `Thumbnail` to build key.
This will fix the following breaking bug in staging:
```
Uncaught TypeError: Cannot read property 'toString' of undefined
at buildKeyFromStrings.js:14
at Array.map (<anonymous>)
at buildKeyFromStrings (buildKeyFromStrings.js:13)
at component.js:58
at Array.map (<anonymous>)
at Component (component.js:52)
at mountIndeterminateComponent (react-dom.development.js:14563)
at beginWork (react-dom.development.js:15063)
at performUnitOfWork (react-dom.development.js:17820)
at workLoop (react-dom.development.js:17860)
```
=> TE-1533 Pictures: use imageUrl to build key

src/components/collections/Header/__snapshots__/component.spec.js.snap, src/components/collections/Header/utils/__snapshots__/getDesktopMenuMarkup.spec.js.snap, src/components/collections/Header/utils/__snapshots__/getMobileMenuMarkup.spec.js.snap, src/components/collections/Hero/__snapshots__/component.spec.js.snap, src/components/elements/Submenu/component.spec.js, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/Promotion/__snapshots__/component.spec.js.snap, src/components/layout/ShowOn/__snapshots__/component.spec.js.snap, src/components/layout/ShowOn/component.js, src/components/layout/ShowOn/component.spec.js, src/components/property-page-widgets/Description/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Location/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Pictures/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageHero/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageSearchBar/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Rates/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/RoomType/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/RoomTypes/__snapshots__/component.spec.js.snap, src/styles/semantic/themes/livingstone/globals/site.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1538)
Removes `display: flex` which was disrupting a number of components.
The styles are flipped from hiding by default to showing by default.
=> TE-1538 ShowOn: remove `display: flex`

src/styles/semantic/definitions/third-party-components/react-dates-datepicker.less
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1523)
The calendar days don't highlight when hovering over each day.
=> TE-1523 Disable availability calendar interactivity styles

src/components/collections/Header/utils/__snapshots__/getLogoMarkup.spec.js.snap, src/components/collections/Header/utils/__snapshots__/getMobileMenuMarkup.spec.js.snap, src/components/collections/Header/utils/getLogoMarkup.js, src/components/collections/Hero/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageHero/__snapshots__/component.spec.js.snap
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1548)
Displays the logo in the header and all components consuming header.
- ResponsiveImage's `<figure />` tag was affecting how the `<a />` was inheriting its size.
**before**
**after**
**before**
**after**
**before**
**after**
**before**
**after**
=> TE-1548 Fix Header logo image

src/styles/semantic/themes/livingstone/modules/dropdown.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1528)
Adapts all versions of the dropdown component to behave appropriately with `width: 100%` property.
=> TE-1528 Fix text width for footer dropdowns

src/styles/semantic/themes/livingstone/globals/site.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1590)
Removes an obsolete media query that was introduced to work with the `ShowOnDesktop`, `ShowOnMobile` responsive wrappers. This was causing the removal of the datepicker; which left an empty space for the `Button` to fall all the way to the left. 
* Another PR will be opened in templates-ssr in order change the button justification.
=> TE-1590 Fix PropertyPageSearchbar

src/components/layout/HorizontalGutters/component.js, src/components/property-page-widgets/Pictures/Readme.md, src/components/property-page-widgets/Pictures/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Pictures/component.js, src/components/property-page-widgets/Pictures/component.spec.js, src/components/property-page-widgets/Pictures/mock-data/images.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1601)
Exposes `props.galleryImages` and `props.thumbnailImages` on the `Pictures` component to allow consuming components to pass different size images for each display case.
=> TE-1601 `Pictures`: expose `props.galleryImages` and `props.thumbnailImages`

src/components/collections/Footer/__snapshots__/component.spec.js.snap, src/components/collections/Header/__snapshots__/component.spec.js.snap, src/components/collections/Header/utils/__snapshots__/getDesktopMenuMarkup.spec.js.snap, src/components/elements/Submenu/component.js, src/components/elements/Submenu/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1597)
Adds `props.scrolling` to `Submenu` so that submenus have a max height.
This is a straightforward implementation of https://react.semantic-ui.com/modules/dropdown/#variations-scrolling
=> TE-1597 Add `props.scrolling` to `Submenu`

src/styles/semantic/themes/livingstone/elements/segment.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1660)
Removes the one pixel border from the hero.
When a segment is the last child it removes the border. In the case of FullBleed being used as a hero at the top of the document it's the first child so will have a border bottom.
The recordings have an empty `<div>` after the segment to demonstrate the border.
=> TE-1660 Hero remove 1px border

src/components/inputs/Dropdown/Readme.md, src/components/inputs/Dropdown/component.js, src/components/inputs/Dropdown/mock-data/options.js, src/styles/semantic/themes/livingstone/modules/dropdown.overrides, src/styles/semantic/themes/livingstone/modules/dropdown.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1658)
Upgrades `Dropdown` indentation to  accept integers between 0 and 5 inclusive
=> TE-1658 Dropdown indentation accepts 0 to 5 integers inclusive

src/components/property-page-widgets/HostProfile/component.js, src/components/property-page-widgets/HostProfile/utils/__snapshots__/getDescription.spec.js.snap, src/components/property-page-widgets/HostProfile/utils/getDescription.js, src/components/property-page-widgets/HostProfile/utils/getDescription.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1686)
Makes the `description` prop not required in `HostProfile`; then, implements `getDescription` util to handle `undefined`
=> TE-1686 HostProfile Description is not required

src/components/collections/Header/__snapshots__/component.spec.js.snap, src/components/collections/Header/mock-data/navigationItems.js, src/components/collections/Header/utils/__snapshots__/getHiddenMenuMarkup.spec.js.snap, src/components/collections/Header/utils/__snapshots__/getStandardMenuMarkup.spec.js.snap, src/components/collections/Header/utils/getHiddenMenuMarkup.js, src/components/collections/Header/utils/getStandardMenuMarkup.js, src/styles/semantic/themes/livingstone/collections/menu.overrides, src/styles/semantic/themes/livingstone/collections/menu.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1691)
Reverts the changes made in https://github.com/lodgify/lodgify-ui/pull/481 so that submenus in header have no link.
=> TE-1691 Header: revert to submenu trigger having no link

src/components/collections/Header/__snapshots__/component.spec.js.snap, src/components/collections/Header/utils/__snapshots__/getHiddenMenuMarkup.spec.js.snap, src/components/collections/Header/utils/__snapshots__/getLogoMarkup.spec.js.snap, src/components/collections/Header/utils/getHiddenMenuMarkup.js, src/components/collections/Header/utils/getLogoMarkup.js, src/components/collections/Hero/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageHero/__snapshots__/component.spec.js.snap, src/styles/semantic/themes/livingstone/collections/menu.overrides, src/styles/semantic/themes/livingstone/collections/menu.variables, src/styles/semantic/themes/livingstone/modules/modal.overrides, src/styles/semantic/themes/livingstone/modules/modal.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1685)
First, modifies the structure of `getHiddenMenuMarkup` and `getLogoMarkup`; then, applies styling to meet the Youtrack card behaviour.
=> TE-1685 Desktop Menu Modal layout fix

src/components/collections/Header/__snapshots__/component.spec.js.snap, src/components/collections/Header/utils/__snapshots__/getHiddenMenuMarkup.spec.js.snap, src/components/collections/Header/utils/__snapshots__/getLogoMarkup.spec.js.snap, src/components/collections/Header/utils/getLogoMarkup.js, src/components/collections/Hero/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageHero/__snapshots__/component.spec.js.snap, src/styles/semantic/themes/livingstone/collections/menu.overrides, src/styles/semantic/themes/livingstone/collections/menu.variables, src/styles/semantic/themes/livingstone/modules/modal.overrides, src/styles/semantic/themes/livingstone/modules/modal.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1685)
Fixes the regression caused by the merge of the mentioned ticket.
=> TE-1685 Fix Desktop Menu Modal layout

src/index.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1690)
Adds missing export for the `Viewport` component.
=> TE-1690 Footer should be at the bottom of the page

src/components/property-page-widgets/RoomType/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/RoomType/utils/getRoomFeaturesMarkup.js, src/components/property-page-widgets/RoomTypes/__snapshots__/component.spec.js.snap
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1805)
Roomtype feature icons are horizontally inline
=> TE-1805 Roomtype icons are horizontally inline 

src/components/general-widgets/HTML/Readme.md, src/components/general-widgets/HTML/component.js, src/components/general-widgets/HTML/component.spec.js, src/components/general-widgets/HTML/mock-data/examples.js, src/styles/semantic/themes/livingstone/globals/site.overrides, src/styles/semantic/themes/livingstone/globals/site.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1754)
Implements new styles for the `HTML` component in order to prevent content and image overflow; then, updates `HTML` docs with a nested image case.
=> TE-1754 HTML component content is not respecting parent width.

src/components/elements/BlockPlaceholder/__snapshots__/component.spec.js.snap, src/components/elements/BlockPlaceholder/component.js, src/components/general-widgets/FeaturedRoomType/__snapshots__/component.spec.js.snap, src/components/general-widgets/FeaturedRoomTypes/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Rates/utils/getTablePlaceholderMarkup.js, src/components/property-page-widgets/RoomType/Readme.md, src/components/property-page-widgets/RoomType/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/RoomType/component.js, src/components/property-page-widgets/RoomType/component.spec.js, src/components/property-page-widgets/RoomTypes/Readme.md, src/components/property-page-widgets/RoomTypes/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/RoomTypes/component.js, src/components/property-page-widgets/RoomTypes/component.spec.js, src/components/property-page-widgets/RoomTypes/constants.js, src/styles/semantic/themes/livingstone/globals/site.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1755)
Adds placeholders to `RoomTypes`
I changed the behaviour of `BlockPlaceholder` to fill container height when `props.isFluid` is true.
I made all the consequent changes to make sure this doesn't disrupt existing consumption of `BlockPlaceholder`.
=> TE-1755 Add placeholders to`RoomTypes`

src/components/elements/Divider/__snapshots__/component.spec.js.snap, src/components/elements/Divider/component.js, src/components/elements/Divider/component.spec.js, src/components/media/Gallery/__snapshots__/component.spec.js.snap, src/components/media/Gallery/component.js, src/components/property-page-widgets/Pictures/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Pictures/component.js, src/components/property-page-widgets/PropertyPageHero/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Rates/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Rates/utils/__snapshots__/getCardsPlaceholderMarkup.spec.js.snap, src/components/property-page-widgets/Rates/utils/getCardsPlaceholderMarkup.js, src/styles/semantic/themes/livingstone/elements/divider.overrides, src/styles/semantic/themes/livingstone/elements/divider.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1883)
Dividers with a size of large have decreased in size and Dividers of size huge have replaced the previous large size.
- The css selector has been changed because `is-size-small` class wasn't getting any css applied to it.
- Size `large` has been changed to `@20px` and `huge` was added with `@40px`
=> TE-1883 Divider standardise margins

src/styles/semantic/definitions/third-party-components/react-dates-datepicker.less, src/styles/semantic/themes/default/third-party-components/react-dates-datepicker.variables, src/styles/semantic/themes/livingstone/modules/dropdown.overrides, src/styles/semantic/themes/livingstone/modules/dropdown.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1859)
Icons no longer appear above dropdown menus or date range picker inputs.
=> TE-1859 Fix z-index for input icons

src/styles/semantic/themes/livingstone/elements/container.overrides, src/styles/semantic/themes/livingstone/elements/container.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1876)
Increases the header max width greater to that of the container.
- There is a 40px padding on either side so that is taken into account which is why it's 1430px and not 1350px.
=> TE-1876 Header max width increase to 1350px

src/components/general-widgets/CookieAlert/__snapshots__/component.spec.js.snap, src/components/general-widgets/HTML/component.js, src/components/general-widgets/HTML/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1888)
Html attribute `target` is no longer sanitised in HTML component
=> TE-1888 Respect target attr html

src/styles/semantic/themes/livingstone/globals/site.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1874)
Implements word-break for every single ui header.
=> TE- 1874 Heading widgets do not break words and overlap on low width

src/components/collections/Footer/component.js, src/components/collections/Footer/utils/getMenuItemMarkup.js, src/components/collections/Footer/utils/getMenuItemMarkup.spec.js, src/components/collections/Header/component.js, src/components/collections/Header/utils/getHiddenMenuMarkup.js, src/components/collections/Header/utils/getLinkMarkup.js, src/components/collections/Header/utils/getLinkMarkup.spec.js, src/components/collections/Header/utils/getStandardMenuMarkup.js, src/components/elements/Submenu/component.js, src/components/general-widgets/CookieAlert/__snapshots__/component.spec.js.snap, src/components/general-widgets/CookieAlert/component.js, src/components/general-widgets/CookieAlert/utils/__snapshots__/getFormMarkup.spec.js.snap, src/components/general-widgets/CookieAlert/utils/getFormMarkup.js, src/components/general-widgets/FeaturedProperties/__snapshots__/component.spec.js.snap, src/components/general-widgets/FeaturedProperty/__snapshots__/component.spec.js.snap, src/components/general-widgets/FeaturedProperty/component.js, src/components/general-widgets/FeaturedRoomType/__snapshots__/component.spec.js.snap, src/components/general-widgets/FeaturedRoomType/component.js, src/components/general-widgets/FeaturedRoomTypes/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/component.js, src/components/property-page-widgets/PropertyPageHero/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1913)
Menu items now have the option to open in a new tab.
- `CookieAlert` more info link now opens in a new tab as requested.
Showing examples of working implementation for `Submenu`, `Header`, `FeaturedProperty`, `FeaturedRoomType` and `CookieAlert` as the rest are just pass throughs.
=> TE-1913 Expose target props

src/components/collections/Header/__snapshots__/component.spec.js.snap, src/components/collections/Header/component.js, src/components/collections/Header/component.spec.js, src/components/collections/Header/utils/__snapshots__/getHiddenMenuMarkup.spec.js.snap, src/components/collections/Header/utils/__snapshots__/getLogoMarkup.spec.js.snap, src/components/collections/Header/utils/getHiddenMenuMarkup.js, src/components/collections/Header/utils/getLogoMarkup.js, src/components/collections/Header/utils/getLogoMarkup.spec.js, src/components/collections/Hero/__snapshots__/component.spec.js.snap, src/components/collections/Hero/component.js, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/component.js, src/components/property-page-widgets/PropertyPageHero/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageHero/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1940)
Exposes `logoHref` and `headerLogoHref` prop in `Header`, `Hero`, `HomepageHero` and `PropertyPageHero` so that consumers can choose where the logo link takes someone on click.
=> TE-1940 Expose header logo href

src/components/general-widgets/Review/__snapshots__/component.spec.js.snap, src/components/general-widgets/Review/utils/getReviewerNameAndLocationString.js, src/components/general-widgets/Review/utils/getReviewerNameAndLocationString.spec.js, src/components/property-page-widgets/Reviews/__snapshots__/component.spec.js.snap
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1941)
Swaps  the order of `reviewerLocation` and `reviewerName`
=> TE-1941 Review component: Change the order for reviewerLocation and reviewerName

src/styles/semantic/themes/livingstone/modules/rating.overrides, src/styles/semantic/themes/livingstone/modules/rating.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1943)
Removes the focus outline for all `Rating` components that are not an input
=> TE-1943 Remove focus state from Rating components which are not an input

src/components/collections/Form/utils/setInputState.js, src/components/collections/Form/utils/setInputState.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1938)
Fixes the way `Form` updates input states. Passes a function to `setState` to maintain ordering of state changes
=> TE-1938 Fix `SingleDatePicker` validation

src/styles/semantic/themes/livingstone/elements/segment.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1915)
`Promotion`: respect background image aspect ratio
For these examples I am using the same image as https://npreview-mos-eisley.lodgifyintegration.com/en/1208320/promotion-widget ...
=> TE-1915 Promotion: respect background image aspect ratio

src/components/collections/Footer/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1856)
Remove `.isRequired` from `Footer.props.phoneNumber`
The other changed required in the ticket has already been solved in some other PR.
=> TE-1856 Remove `.isRequired` from `Footer.props.phoneNumber`

src/components/collections/Header/__snapshots__/component.spec.js.snap, src/components/collections/Header/component.js, src/components/collections/Header/component.spec.js, src/components/collections/Hero/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageHero/__snapshots__/component.spec.js.snap, src/styles/semantic/themes/livingstone/collections/menu.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1967)
Makes `Header` content transparent by default. 
Removes dependency on JS running to achieve transparency.
=> TE-1967 Fix header opacity

package.json
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1848)
Removes Terser from dev dependencies as it's no longer needed as a work around for a problem within webpack.
=> TE-1848 Remove terser from dev dependencies

src/styles/semantic/themes/livingstone/views/card.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1991)
Removes the underline from all text in a card that is wrapped by an `<a>`.
The issue was caused by the `text-decoration-line` property which isn't supported by ie 11 or older versions of safari. `text-decoration: none;` didn't seem to cause any regression.
=> TE-1991 Remove underline from cards wrapped by <a> on Safari

src/styles/semantic/themes/livingstone/modules/modal.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1908)
Fixes the regression caused by https://github.com/lodgify/lodgify-ui/pull/564.
Header image is restricted to a maximum height.
=> TE-1908 Modal header image regression

src/components/general-widgets/CallMeBack/__snapshots__/component.spec.js.snap, src/components/general-widgets/Contact/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/component.js, src/components/general-widgets/SearchBar/__snapshots__/component.spec.js.snap, src/components/general-widgets/SearchBar/component.js, src/components/general-widgets/SearchBar/component.spec.js, src/components/general-widgets/SearchBar/utils/__snapshots__/getFormFieldMarkup.spec.js.snap, src/components/inputs/Dropdown/component.js, src/components/inputs/Dropdown/component.spec.js, src/components/property-page-widgets/Availability/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageSearchBar/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageSearchBar/component.js, src/components/property-page-widgets/Rates/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Rates/utils/__snapshots__/getRoomTypeDropdownMarkup.spec.js.snap
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1904)
- Removes unnecessary `defaultValue` from `Dropdown`.
- Adds initial values for `SearchBar` state inputs.
- Fixes `HomepageHero` and `PropertySearchBar` guest input PropTypes.
=> TE-1904 Persist search value with a cookie

src/components/general-widgets/Contact/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/component.js, src/components/general-widgets/SearchBar/__snapshots__/component.spec.js.snap, src/components/general-widgets/SearchBar/component.js, src/components/general-widgets/SearchBar/utils/__snapshots__/getFormFieldMarkup.spec.js.snap, src/components/general-widgets/SearchBar/utils/getFormFieldMarkup.js, src/components/inputs/DateRangePicker/__snapshots__/component.spec.js.snap, src/components/inputs/DateRangePicker/component.js, src/components/inputs/DateRangePicker/component.spec.js, src/components/property-page-widgets/PropertyPageSearchBar/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageSearchBar/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-1996)
Exposes a functional prop called when `DateRangePicker` focus state changes.
=> TE-1996 `SearchBar`: expose `props.datesInputOnFocusChange`

src/styles/semantic/definitions/third-party-components/react-dates-datepicker.less
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2083)
Implements the requested styles for `DateRangePicker`; blocked and unblocked dates on hover. 
The following bug was solved in this PR:
=> TE-2083 DateRangePicker: change styles for blocked and unblocked days

src/components/property-page-widgets/RoomType/utils/__snapshots__/getModalContentMarkup.spec.js.snap, src/components/property-page-widgets/RoomType/utils/getModalContentMarkup.js, src/components/property-page-widgets/RoomType/utils/getModalContentMarkup.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2029)
Removes the Room Amenities `headingText` when there are no items.
=> TE-2029 Hide amenities bar when there's nothing to display

src/components/property-page-widgets/PropertyPageHero/Readme.md, src/components/property-page-widgets/PropertyPageHero/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageHero/component.js, src/components/property-page-widgets/PropertyPageHero/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2139)
Decouples the background image from the gallery images in `PropertyPageHero` so we can deal with categorised gallery images better.
The component API now matches that of `HomepageHero` so there is nothing controversial in the way this is laid out.
=> TE-2139 PropertyPageHero: Accept gallery images with categories

src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/component.js, src/components/general-widgets/SearchBar/component.js, src/components/general-widgets/SearchBar/utils/getFormFieldMarkup.js, src/components/inputs/DateRangePicker/__snapshots__/component.spec.js.snap, src/components/inputs/DateRangePicker/component.js, src/components/inputs/DateRangePicker/component.spec.js, src/components/inputs/DateRangePicker/utils/getFocusedInput.js, src/components/inputs/DateRangePicker/utils/getFocusedInput.spec.js, src/components/property-page-widgets/PropertyPageSearchBar/component.js
`DateRangePicker`: expose `props.focusedInput`. This allows controlling components to control the timing of the change of focused input and in turn the timing of the call of `props.getIsDayBlocked`
=> TE-2084 `DateRangePicker`: expose `props.focusedInput`

src/styles/semantic/themes/livingstone/collections/menu.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2032)
Eliminates the style rules for the `first-child` of `Accordion` dropdowns.
=> TE-2032 Folder first child arrow icon does not respect its intended style.

src/styles/semantic/themes/livingstone/elements/button.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2062)
Prevents button texts to fall into a second line.
=> TE-2062 Do not allow buttons to have more than one line of text

src/styles/semantic/themes/livingstone/collections/menu.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2047)
Solves the regression of menu item overflow by switching its selector.
=> TE-2047 When there are more than 7 options available in a dropdown, the last ones are not inside the style box

src/components/collections/Header/component.js, src/components/collections/Header/component.spec.js, src/components/collections/Header/utils/__snapshots__/getStandardMenuMarkup.spec.js.snap, src/components/collections/Header/utils/getHiddenMenuMarkup.js, src/components/collections/Header/utils/getStandardMenuMarkup.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2073)
Implements `activeNavigationItemIndex` to `Header` state.
=> TE-2073 Header folder links are permanently outlined

src/styles/semantic/definitions/third-party-components/react-dates-datepicker.less
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2158)
Overrides the blocked date styles, when the date is also selected.
=> TE-2158 CheckIn - CheckOut styles are overriden after the blocked dates are recalculated

src/components/collections/Header/Readme.md, src/components/collections/Header/__snapshots__/component.spec.js.snap, src/components/collections/Header/component.js, src/components/collections/Header/utils/__snapshots__/getHiddenMenuMarkup.spec.js.snap, src/components/collections/Header/utils/__snapshots__/getLogoMarkup.spec.js.snap, src/components/collections/Header/utils/getHiddenMenuMarkup.js, src/components/collections/Header/utils/getLogoMarkup.js, src/components/collections/Header/utils/getLogoMarkup.spec.js, src/components/collections/Hero/__snapshots__/component.spec.js.snap, src/components/collections/Hero/component.js, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/component.js, src/components/property-page-widgets/PropertyPageHero/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageHero/component.js, src/styles/semantic/themes/livingstone/collections/menu.overrides, src/styles/semantic/themes/livingstone/collections/menu.variables, src/styles/semantic/themes/livingstone/modules/modal.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2098)
Header, Hero, PropertyPageHero and HomepageHero can display a tagline under the header.
=> TE-2098 header logo tagline

src/components/general-widgets/CallMeBack/Readme.md, src/components/general-widgets/CallMeBack/__snapshots__/component.spec.js.snap, src/components/general-widgets/CallMeBack/component.js, src/components/general-widgets/Contact/Readme.md, src/components/general-widgets/Contact/__snapshots__/component.spec.js.snap, src/components/general-widgets/Contact/component.js, src/components/general-widgets/OwnerSignUp/Readme.md, src/components/general-widgets/OwnerSignUp/__snapshots__/component.spec.js.snap, src/components/general-widgets/OwnerSignUp/component.js, src/components/inputs/Checkbox/__snapshots__/component.spec.js.snap, src/components/inputs/Checkbox/component.js, src/components/inputs/InputController/component.js, src/components/property-page-widgets/Reviews/Readme.md, src/components/property-page-widgets/Reviews/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Reviews/component.js, src/components/property-page-widgets/Reviews/utils/getModalFormMarkup.js, src/styles/semantic/themes/livingstone/elements/input.overrides, src/styles/semantic/themes/livingstone/elements/input.variables, src/styles/semantic/themes/livingstone/modules/checkbox.overrides, src/utils/default-strings/constants.js, src/utils/get-privacy-consent-label/__snapshots__/getPrivacyConsentLabel.spec.js.snap, src/utils/get-privacy-consent-label/getPrivacyConsentLabel.js, src/utils/get-privacy-consent-label/getPrivacyConsentLabel.spec.js, src/utils/get-privacy-consent-label/index.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2178)
CallMeBack, Contact, Reviews and OwnerSignup expose privacy consent props to create a label with a link next to the privacy consent checkbox.
=> TE-2178 Form privacy consent

src/styles/semantic/themes/livingstone/globals/site.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2184)
Prevents lodgify-ui from making a Arial font request to google fonts.
`loadFonts` is required by `semantic-ui-less` so the fix is forcing the condition. 
```less
.loadFonts() when (@importGoogleFonts) {
@import url('@{googleProtocol}fonts.googleapis.com/css?family=@{googleFontRequest}');
}
```
=> TE-2184 Arial request to google fonts

src/components/general-widgets/EmailCapture/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2195)
Hides the checkbox if component receives `errorMessage` prop.
=> TE-2195 Hide privacy checkbox if error is passed

src/components/layout/LazyLoader/Readme.md, src/styles/semantic/definitions/third-party-components/react-image-gallery.less
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2225)
- Slideshow in `RoomTypes` show the images.
- Example for `LazyLoader` shows preview without error.
=> TE-2225 fix slideshow

src/components/general-widgets/CallMeBack/__snapshots__/component.spec.js.snap, src/components/general-widgets/Contact/__snapshots__/component.spec.js.snap, src/components/general-widgets/EmailCapture/__snapshots__/component.spec.js.snap, src/components/general-widgets/EmailCapture/utils/__snapshots__/getPrivacyCheckboxMarkup.spec.js.snap, src/components/general-widgets/OwnerSignUp/__snapshots__/component.spec.js.snap, src/components/inputs/Checkbox/__snapshots__/component.spec.js.snap, src/components/inputs/Checkbox/component.js, src/components/property-page-widgets/Reviews/utils/getModalFormMarkup.spec.js, src/styles/semantic/themes/livingstone/elements/input.overrides, src/styles/semantic/themes/livingstone/elements/input.variables, src/styles/semantic/themes/livingstone/modules/checkbox.overrides, src/utils/get-privacy-consent-label/__snapshots__/getPrivacyConsentLabel.spec.js.snap, src/utils/get-privacy-consent-label/getPrivacyConsentLabel.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2198)
- Checkbox no longer has an `isValid` state.
- Checkbox label can be clicked to toggle it's value.
=> TE-2198 Checkbox bug fixes

src/components/property-page-widgets/Summary/utils/__snapshots__/getPricePerPeriodAndLocationMarkup.spec.js.snap, src/components/property-page-widgets/Summary/utils/__snapshots__/getPricePerPeriodAndRatingMarkup.spec.js.snap, src/components/property-page-widgets/Summary/utils/getPricePerPeriodAndLocationMarkup.js, src/components/property-page-widgets/Summary/utils/getPricePerPeriodAndLocationMarkup.spec.js, src/components/property-page-widgets/Summary/utils/getPricePerPeriodAndRatingMarkup.js, src/components/property-page-widgets/Summary/utils/getPricePerPeriodAndRatingMarkup.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2250)
fix(Summary): hide rating if the rating value is falsy
=> TE-2250 PropertypageSearchBar hide rating if not passed

src/components/collections/Header/utils/HiddenMenu/component.js, src/components/collections/Header/utils/HiddenMenu/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2169)
Only updates state if the clicked component is different from what's stored in the state. The clicked accordion item is always in state.
=> TE-2169 Fullpage modal scroll

src/utils/react-google-maps/component.js, src/utils/react-google-maps/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2209)
refactor(react-google-maps): directly import assets
=> TE-2209 Import react-google-maps assets directly

src/styles/semantic/themes/livingstone/elements/segment.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2247)
Promotion images fill available space and the widget takes the theme colour if set.
=> TE-2247 Fix promotion images

src/styles/semantic/themes/livingstone/views/card.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2267)
The header forms an ellipsis when the text is too long.
=> TE-2267 Featured property header ellipsis

.babelrc, package.json, tools/babel/plugin-react-dates-transform-imports.js, tools/babel/preset.js
[Related YouTrack issue TE-2199](https://youtrack.lodgify.net/issue/TE-2199)
[Related YouTrack issue TE-2204](https://youtrack.lodgify.net/issue/TE-2204)
[Related YouTrack issue TE-2206](https://youtrack.lodgify.net/issue/TE-2206)
1. Exposes the whole library as es6 modules at `lib/es`
2. Imports es6 modules from `semantic-ui-react`
3. Imports es6 modules from `react-dates`
Looks like this shaves around 13% off our main bundle.
=> TE-2199 TE-2204 TE-2206 ES6 modules FTW

src/components/general-widgets/PropertySearchResult/__snapshots__/component.spec.js.snap, src/components/general-widgets/PropertySearchResult/component.js, src/components/general-widgets/PropertySearchResult/component.spec.js, src/components/general-widgets/PropertySearchResult/index.js, src/components/general-widgets/PropertySearchResultList/Readme.md, src/components/general-widgets/PropertySearchResultList/__snapshots__/component.spec.js.snap, src/components/general-widgets/PropertySearchResultList/component.js, src/components/general-widgets/PropertySearchResultList/component.spec.js, src/components/general-widgets/PropertySearchResultList/constants.js, src/components/general-widgets/PropertySearchResultList/index.js, src/utils/default-strings/constants.js
Adds `PropertySearchResultList` consuming dummy `PropertySearchResult`s
=> TE-2326 Add `PropertySearchResultList`

src/components/collections/Hero/__snapshots__/component.spec.js.snap, src/components/general-widgets/FeaturedProperties/__snapshots__/component.spec.js.snap, src/components/general-widgets/FeaturedProperty/__snapshots__/component.spec.js.snap, src/components/general-widgets/FeaturedRoomType/__snapshots__/component.spec.js.snap, src/components/general-widgets/FeaturedRoomTypes/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/Promotion/__snapshots__/component.spec.js.snap, src/components/layout/LazyLoader/__snapshots__/component.spec.js.snap, src/components/layout/LazyLoader/component.js, src/components/layout/LazyLoader/component.spec.js, src/components/layout/LazyLoader/utils/getComponentPosition.js, src/components/layout/LazyLoader/utils/getComponentPosition.spec.js, src/components/layout/LazyLoader/utils/getIsBottomComponentVisible.js, src/components/layout/LazyLoader/utils/getIsBottomComponentVisible.spec.js, src/components/layout/LazyLoader/utils/getIsTopComponentVisible.js, src/components/layout/LazyLoader/utils/getIsTopComponentVisible.spec.js, src/components/media/FullBleed/__snapshots__/component.spec.js.snap, src/components/media/ResponsiveImage/Readme.md, src/components/media/ResponsiveImage/__snapshots__/component.spec.js.snap, src/components/media/ResponsiveImage/component.js, src/components/media/ResponsiveImage/component.spec.js, src/components/media/Thumbnail/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/HostProfile/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Pictures/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageHero/__snapshots__/component.spec.js.snap, src/utils/with-lazy-load/__snapshots__/withLazyLoad.spec.js.snap, src/utils/with-lazy-load/withLazyLoad.js, src/utils/with-lazy-load/withLazyLoad.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2253)
Makes all `ResponsiveImage` components to have lazyload by default.
=> TE-2253 Responsive image defaults to lazyload

src/components/general-widgets/Contact/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/SearchBar/__snapshots__/component.spec.js.snap, src/components/general-widgets/SearchBar/utils/__snapshots__/getFormFieldMarkup.spec.js.snap, src/components/general-widgets/SearchBar/utils/getFormFieldMarkup.js, src/components/inputs/NumberInput/__snapshots__/component.spec.js.snap, src/components/inputs/NumberInput/component.js, src/components/property-page-widgets/PropertyPageSearchBar/__snapshots__/component.spec.js.snap, src/styles/semantic/themes/livingstone/elements/input.overrides, src/styles/semantic/themes/livingstone/elements/input.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2343)
Adds the missing `guests` icon to `SearchBar`.
=> TE-2343 Fix icon and width of SearchBar Guests NumberInput

src/index.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2340)
Exposes `PropertySearchResultList`and `PropertySearchResult` so they can be consumed in `templates-ssr`
=> TE-2340 Implement `PropertySearchResultList` on `all-properties` page

src/styles/semantic/definitions/third-party-components/react-dates-datepicker.less, src/styles/semantic/themes/default/third-party-components/react-dates-datepicker.variables, src/styles/semantic/themes/livingstone/modules/checkbox.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2378)
Configures `DateRangePicker` to take the theme colours if they're set.
=> TE-2378 DateRangePicker hover colours.

src/styles/semantic/themes/livingstone/elements/segment.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2406)
Bumps any `Hero` up one z-index so that its children show above `Hero`'s lower siblings.
=> TE-2406 Hero: show dropdown above other elements

src/styles/semantic/themes/livingstone/globals/site.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2407)
Logo sub title text takes the sub title font variable value. It is the only text which uses this variable.
=> TE-2407 Logo subtitle font

src/components/collections/Hero/__snapshots__/component.spec.js.snap, src/components/general-widgets/FeaturedProperties/__snapshots__/component.spec.js.snap, src/components/general-widgets/FeaturedRoomTypes/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/Promotion/__snapshots__/component.spec.js.snap, src/components/media/FullBleed/__snapshots__/component.spec.js.snap, src/components/media/ResponsiveImage/__snapshots__/component.spec.js.snap, src/components/media/ResponsiveImage/component.js, src/components/media/ResponsiveImage/component.spec.js, src/components/media/ResponsiveImage/constants.js, src/components/media/Thumbnail/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/HostProfile/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Pictures/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageHero/__snapshots__/component.spec.js.snap
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2393)
For `ResponsiveImage`, lazyLoads `placeholderImageUrl`, this preventing it from loading on page load.
=> TE-2393 "Lazy" images are being loaded on page load anyway

src/components/collections/Hero/__snapshots__/component.spec.js.snap, src/components/general-widgets/FeaturedProperties/__snapshots__/component.spec.js.snap, src/components/general-widgets/FeaturedRoomTypes/__snapshots__/component.spec.js.snap, src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/Promotion/__snapshots__/component.spec.js.snap, src/components/layout/LazyLoader/utils/getIsBottomComponentVisible.js, src/components/layout/LazyLoader/utils/getIsBottomComponentVisible.spec.js, src/components/layout/LazyLoader/utils/getIsTopComponentVisible.js, src/components/layout/LazyLoader/utils/getIsTopComponentVisible.spec.js, src/components/media/FullBleed/__snapshots__/component.spec.js.snap, src/components/media/ResponsiveImage/__snapshots__/component.spec.js.snap, src/components/media/ResponsiveImage/component.spec.js, src/components/media/Thumbnail/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/HostProfile/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Pictures/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PropertyPageHero/__snapshots__/component.spec.js.snap, src/utils/with-lazy-load/__snapshots__/withLazyLoad.spec.js.snap, src/utils/with-lazy-load/withLazyLoad.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2393)
Prevents `LazyLoader` to render responsive images if component is on position 0.
=> TE-2393 "Lazy" images are being loaded if component offset is zero

src/components/general-widgets/PropertySearchResultList/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2326)
Amends the prop description for `renderShowingResultsText` and `resultsCountText`
=> TE-2326 Fix renderShowingResultsText and resultsCountText prop description

src/components/general-widgets/PropertySearchResult/Readme.md, src/components/general-widgets/PropertySearchResult/__snapshots__/component.spec.js.snap, src/components/general-widgets/PropertySearchResult/component.js, src/components/general-widgets/PropertySearchResult/component.spec.js, src/components/general-widgets/PropertySearchResultList/Readme.md, src/components/general-widgets/PropertySearchResultList/__snapshots__/component.spec.js.snap, src/components/general-widgets/PropertySearchResultList/mock-data/mock-data.js, src/styles/semantic/themes/livingstone/views/card.overrides, src/styles/semantic/themes/livingstone/views/card.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2428)
Exposes `isCompact` prop for `PropertySearchResult`
=> TE-2428 PropertySearchResult exposes an `isCompact` prop

src/components/collections/Footer/__snapshots__/component.spec.js.snap, src/components/collections/Footer/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2476)
fix(Footer): pass email not faxNumber to href
=> TE-2476 fix(Footer): pass email not faxNumber to href

src/components/general-widgets/FeaturedProperty/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2482)
`FeaturedProperty` renders no rating when `prop.ratingNumber` is a falsy value.
=> TE-2482 FeaturedProperty rating not required

src/components/general-widgets/SearchBar/component.js, src/components/general-widgets/SearchBar/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2472)
Inputs values are no longer cleared when values are changed by a controlled component.
=> TE-2472 search bar inputs

src/styles/semantic/themes/livingstone/elements/input.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2473)
Stops the label on `PhoneInput` bouncing around weirdly.
=> TE-2473 PhoneInput:  fix loony label behaviour

src/components/general-widgets/HomepageHero/__snapshots__/component.spec.js.snap, src/components/general-widgets/SearchBar/__snapshots__/component.spec.js.snap, src/components/inputs/DateRangePicker/__snapshots__/component.spec.js.snap, src/components/inputs/DateRangePicker/component.js, src/components/inputs/DateRangePicker/component.spec.js, src/components/inputs/DateRangePicker/utils/getIsVisible.js, src/components/inputs/DateRangePicker/utils/getIsVisible.spec.js, src/components/property-page-widgets/PropertyPageSearchBar/__snapshots__/component.spec.js.snap
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2554)
Ignores calls to onFocusChange for date range pickers which are not visible on the page.
=> TE-2554 DateRangePicker: fix loony focus change behaviour

src/components/general-widgets/PropertySearchResultList/__snapshots__/component.spec.js.snap, src/components/general-widgets/PropertySearchResultList/component.js, src/components/general-widgets/PropertySearchResultList/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2511)
PropertySearchResultList: expose props.onChange
=> TE-2511 PropertySearchResultList: expose props.onChange

src/styles/semantic/themes/livingstone/collections/menu.overrides, src/styles/semantic/themes/livingstone/elements/label.overrides, src/utils/google-map-react/constants/constants.js, src/utils/google-map-react/constants/index.js, src/utils/google-map-react/utils/getMapOptions.js, src/utils/google-map-react/utils/getMapOptions.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2601)
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2599)
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2600)
- `GoogleMapReact` controls are smaller.
- `Pagination` active item color contrasts with background.
- `PriceLabel` color contrast only on hover.
=> TE-2601 Search app optimisations

src/components/collections/ToggleInputSegment/__snapshots__/component.spec.js.snap, src/components/collections/ToggleInputSegment/component.js, src/components/collections/ToggleInputSegment/component.spec.js, src/components/collections/ToggleInputSegment/utils/getIsToggleCheckedControlled.js, src/components/collections/ToggleInputSegment/utils/getIsToggleCheckedControlled.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2377)
Prevents additional calls to `onChange` when the component's `isToggleChecked` value is controlled.
=> TE-2377 instant booking filter

src/components/inputs/InputController/component.js, src/components/inputs/InputController/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2659)
Fix the problem with labels in input that overlap the value when the input is dirty.
|before|after|
|-|-|
|![input-before](https://user-images.githubusercontent.com/49396812/65157104-7a7fec00-da30-11e9-8596-1c5efb1d1461.gif)|![input after](https://user-images.githubusercontent.com/49396812/65157125-853a8100-da30-11e9-9e41-ecda26bb8484.gif)|
=> TE-2659 Fix Input label behaviour

src/utils/google-map-react/components/GoogleMapReact/component.js, src/utils/google-map-react/components/GoogleMapReact/component.spec.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2668)
Fires `onBoundsChange` event every time the user `zooms` or `drags` the map.
=> TE-2668 Search app - Event triggers on second interaction

src/components/property-page-widgets/Amenities/Readme.md, src/components/property-page-widgets/Amenities/component.js, src/components/property-page-widgets/Amenities/utils/getCategoryMarkup.js, src/components/property-page-widgets/Amenities/utils/getExtraItemsMarkup.js, src/components/property-page-widgets/Amenities/utils/getFormattedAmenityItems.js, src/components/property-page-widgets/Amenities/utils/getFormattedAmenityItems.spec.js, src/components/property-page-widgets/RoomType/Readme.md, src/components/property-page-widgets/RoomType/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/RoomType/component.js, src/components/property-page-widgets/RoomType/component.spec.js, src/components/property-page-widgets/RoomType/utils/__snapshots__/getModalContentMarkup.spec.js.snap, src/components/property-page-widgets/RoomTypes/__snapshots__/component.spec.js.snap, src/utils/default-strings/constants.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2669)
Implements a prop for `More info` translation for both `RoomType` and `RoomTypes` component.
Implements a prop for the conjunction which unites the last and the penultimate amenity items
=> TE-2669 Fix missing translations

src/components/property-page-widgets/RoomType/Readme.md, src/components/property-page-widgets/RoomType/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/RoomType/component.js, src/components/property-page-widgets/RoomType/component.spec.js, src/components/property-page-widgets/RoomType/utils/__snapshots__/getModalContentMarkup.spec.js.snap, src/components/property-page-widgets/RoomType/utils/getModalContentMarkup.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2669)
Fixes the hardcoded `Room Amenities` string; left behind in my previous PR.
=> TE-2669 Consume amenitiesHeadingText in RoomType component

src/components/property-page-widgets/Amenities/utils/getExtraItemsMarkup.js, src/components/property-page-widgets/RoomType/Readme.md, src/components/property-page-widgets/RoomType/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/RoomType/component.js, src/components/property-page-widgets/RoomType/utils/__snapshots__/getModalContentMarkup.spec.js.snap, src/components/property-page-widgets/RoomType/utils/getModalContentMarkup.js, src/components/property-page-widgets/RoomType/utils/getModalContentMarkup.spec.js, src/components/property-page-widgets/RoomTypes/__snapshots__/component.spec.js.snap
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2669)
* Allows `RoomType` to consume `amenitiesConjunctionText`
* Amends a regression caused by my previous PR.
Before
After
=> TE-2669 Add amenitiesConjunctionText to RoomType

src/components/property-page-widgets/Availability/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Availability/component.js, src/components/property-page-widgets/Rates/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Rates/component.js, src/styles/semantic/themes/livingstone/modules/dropdown.overrides, src/styles/semantic/themes/livingstone/modules/dropdown.variables
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2684)
Adds styles for the dropdown with text labels.
Availability, Rates and PhoneInput dropdowns aren't clearable
=> TE-2684 dropdown styles

src/components/property-page-widgets/Rates/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Rates/utils/__snapshots__/getRoomTypeDropdownMarkup.spec.js.snap, src/components/property-page-widgets/Rates/utils/getRoomTypeDropdownMarkup.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2684)
Adds styles for the dropdown with text labels.
Availability, Rates and PhoneInput dropdowns aren't clearable
=> TE-2684 roomtype dropdown is not clearable

src/styles/semantic/definitions/lodgify-ui-components/flex-container.less
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2617)
Removes unnecessary margin from `HomePageHero` h1.
=> TE-2617 Homepage - Hero headingText is off center

src/styles/semantic/definitions/lodgify-ui-components/search-bar.less
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2644)
Searchbar input widths adjust with device size
=> TE-2644 Search bar responsive layouts

src/styles/semantic/definitions/third-party-components/react-image-gallery.less, src/styles/semantic/themes/default/third-party-components/react-image-gallery.variables, src/styles/semantic/themes/livingstone/modules/modal.overrides, src/styles/semantic/themes/livingstone/modules/modal.variables, src/styles/semantic/themes/livingstone/views/card.overrides
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2732)
Sets the modal `RoomType` image to the height of its container for each viewport.
=> TE-2732 Property Page picture fit image section to image size

src/components/general-widgets/PropertySearchResultList/__snapshots__/component.spec.js.snap, src/components/general-widgets/PropertySearchResultList/component.js
[Related YouTrack issue](https://youtrack.lodgify.net/issue/TE-2704)
Exposes a class prop for the `FlexContainer` wrapping the sort dropdown.
=> TE-2704 Expose class prop for sort wrapper

.github/PULL_REQUEST_TEMPLATE.md, src/styles/semantic/definitions/lodgify-ui-components/html.less, src/styles/semantic/themes/default/lodgify-ui-components/html.variables
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-519)
Image based content doesn't extend passed the width of the component
=> WEB-519 HTML widget max width

src/components/general-widgets/Review/__snapshots__/component.spec.js.snap, src/components/general-widgets/Review/component.js, src/components/general-widgets/Review/utils/getReviewerCategoryAndStayDateString.js, src/components/general-widgets/Review/utils/getReviewerCategoryAndStayDateString.spec.js, src/components/general-widgets/Review/utils/getReviewerNameAndLocationString.js, src/components/general-widgets/Review/utils/getReviewerNameAndLocationString.spec.js, src/components/property-page-widgets/Reviews/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Reviews/component.js, src/components/property-page-widgets/Reviews/utils/transformReviewFactory.js, src/components/property-page-widgets/Reviews/utils/transformReviewFactory.spec.js, src/utils/default-strings/constants.js
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-496)
Reviews can now miss some parameters without showing the `undefined` value
During the execution of this task I noticed a string fixed inside the review. So I made it a params of the reviews list
|before|after|
|---|---|
|<img width="700" alt="image" src="https://user-images.githubusercontent.com/5032333/68657358-dac47300-0533-11ea-8d83-78d508ed6df1.png">|<img width="688" alt="image" src="https://user-images.githubusercontent.com/5032333/68657516-2d9e2a80-0534-11ea-882d-724a2cc7347f.png">|
=> WEB-496: review empty props

src/components/general-widgets/Review/__snapshots__/component.spec.js.snap, src/components/general-widgets/Review/utils/getReviewerCategoryAndStayDateString.js, src/components/general-widgets/Review/utils/getReviewerCategoryAndStayDateString.spec.js, src/components/property-page-widgets/Reviews/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Reviews/component.js
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-496)
Remove the separator in the bottom reviews when only one of the two value is present.
|   |   |
|---|---|
|<img width="658" alt="image" src="https://user-images.githubusercontent.com/5032333/68770580-b39a9e00-0626-11ea-98a2-78b5d771bddf.png">|<img width="661" alt="image" src="https://user-images.githubusercontent.com/5032333/68770746-083e1900-0627-11ea-83c3-cf4e44935544.png">|
=> WEB-496: remove separator when there aren't two values

src/styles/semantic/definitions/lodgify-ui-components/html.less
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-516)
Add width rule for iframe inside HTML to avoid horizontal scroll on mobile
|before|after|
|---|---|
|<img width="447" alt="image" src="https://user-images.githubusercontent.com/5032333/68784466-dcc62900-063c-11ea-8e9e-fcba200c79e1.png">|<img width="447" alt="image" src="https://user-images.githubusercontent.com/5032333/68784421-ccae4980-063c-11ea-90ac-3e9ba2fc79e1.png">|
=> fix(HTML): add width rules for iframes

src/components/property-page-widgets/Amenities/component.js, src/components/property-page-widgets/Availability/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Availability/component.js, src/components/property-page-widgets/Description/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Description/component.js, src/components/property-page-widgets/Location/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Location/component.js, src/components/property-page-widgets/Pictures/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Pictures/component.js, src/components/property-page-widgets/Reviews/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Reviews/component.js, src/components/property-page-widgets/RoomType/utils/__snapshots__/getModalContentMarkup.spec.js.snap
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-743)
Exposes `id` prop for all the property page components related with the sticky menu.
PO details
The link menu bar contains the links:
Description → link to the section Description
Pictures → link to the section Property Pictures
Amenities → link to the section Amenities
Location → link to the section Location / Map
Availability → link to the section Availability
Reviews → link to the section Reviews
=> WEB-743 Expose id for property page components

src/styles/semantic/definitions/lodgify-ui-components/html.less
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-506)
Images nested in the HTML widget no longer fit the width of the parent.
=> WEB-506 html nested images

src/components/collections/Characteristics/__snapshots__/component.spec.js.snap, src/components/collections/CheckboxInputSegment/__snapshots__/component.spec.js.snap, src/components/collections/Footer/__snapshots__/component.spec.js.snap, src/components/general-widgets/EmailCapture/__snapshots__/component.spec.js.snap, src/components/general-widgets/Promotion/__snapshots__/component.spec.js.snap, src/components/general-widgets/Review/__snapshots__/component.spec.js.snap, src/components/layout/GridColumn/component.js, src/components/property-page-widgets/Availability/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Description/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/HostProfile/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Location/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Location/utils/__snapshots__/getLocationDescription.spec.js.snap, src/components/property-page-widgets/Pictures/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/PolicyAndNotes/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Rates/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Reviews/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/RoomType/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/RoomType/utils/__snapshots__/getModalContentMarkup.spec.js.snap, src/components/property-page-widgets/RoomTypes/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Rules/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Rules/utils/__snapshots__/getCheckInAndCheckOutMarkup.spec.js.snap
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-571)
Exposes id to `GridColumn` in order to attach a component id to every column that acts as a container in `ssr`.
=> WEB-571 Expose id to GridColumn

src/styles/semantic/themes/livingstone/modules/rating.overrides
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-X)
Set a default system font (Courier New, monospace) to the rating component in order to not be affected by the custom font of the website.
=> WEB-797: Rating stars will have always the same system font

src/components/property-page-widgets/Availability/__snapshots__/component.spec.js.snap, src/components/property-page-widgets/Availability/component.js
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-846)
Increases the size of the `Availability` component title.
=> WEB-846 Optimize Availability title

src/components/collections/Form/utils/getEmptyState.js, src/components/collections/Form/utils/getEmptyState.spec.js
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-734)
Makes all the `Contact` inputs empty after submission.
* Discovered an issue where, after submission, recaptcha is not refreshed causing the form to error on a second submission; even if all fields are correct.
[Related Jira Issue](https://lodgify.atlassian.net/browse/WEB-856?atlOrigin=eyJpIjoiMTQ3NmQ3ZjhiZmNkNGI1OWJjZDQ5ODljNWQ3NWIxODMiLCJwIjoiaiJ9)
=> WEB-734 Contact empties all inputs after submission

src/components/collections/ContactHeader/MobileHeader/component.js, src/components/collections/ContactHeader/Readme.md
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-918)
Corrects the mapping of the links in the `ContactHeader` mobile menu.
=> WEB-918 Fix mobile menu links

src/components/collections/HorizontalMenu/component.js, src/components/general-widgets/ContactHomeHero/__snapshots__/component.spec.js.snap, src/styles/semantic/definitions/lodgify-ui-components/horizontal-menu.less, src/styles/semantic/themes/default/lodgify-ui-components/horizontal-menu.variables
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-958)
Habilitates the overflow only on `Header` components making sure it doesn't collide with any other component
=> WEB-958 Remove overflow for HorizontalMenu in PropertySubMenu

src/components/collections/StickyMenu/component.js, src/hooks/useScroll.js
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-916)
Removes the debounce interval for the `StickyMenu`.
=> WEB-916 Increase the activation speed of the sticky menu items

src/components/collections/StickyMenu/component.js, src/components/collections/StickyMenu/component.spec.js
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-917)
Exposes a className to StickyMenu so it can be modified by `websites-template-selector`
=> WEB-917 Expose className to stickyMenu

src/styles/semantic/themes/livingstone/views/card.overrides, src/styles/semantic/themes/livingstone/views/card.variables
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-957)
Featured image heights in cards don't obscure the content if the image is big.
=> WEB-957 Featured image height

src/components/collections/ContactHeader/component.js, src/components/collections/HorizontalMenu/component.js, src/components/collections/HorizontalMenu/constants.js, src/components/collections/StickyMenu/component.js, src/components/general-widgets/ContactHomeHero/__snapshots__/component.spec.js.snap, src/styles/semantic/definitions/lodgify-ui-components/contact-header.less, src/styles/semantic/definitions/lodgify-ui-components/horizontal-menu.less, src/styles/semantic/definitions/lodgify-ui-components/logo.less, src/styles/semantic/themes/default/lodgify-ui-components/contact-header.variables, src/styles/semantic/themes/default/lodgify-ui-components/horizontal-menu.variables, src/styles/semantic/themes/default/lodgify-ui-components/logo.variables
[Related Jira issue](https://lodgify.atlassian.net/browse/WEB-865)
* Removes the navigation arrows of the `HorizontalMenu` component when the number of items does not require navigation.
* Also, hides the scrolling bar from the menu.
* Also, makes a couple more fixes for Capucine paddings in order to make paddings and margins more consistent. 
NOTE: For all of this to work properly, another PR in `websites-template-selector` will need to be approved as well. Some styles where removed from there in order to make components easier and more consistent.
=> WEB-865 Remove arrows from Contact Menu when content does not overflow
